#176454681 add vendor certification for lawyer verification
Highrachy/ballers-api pull request #100
Opened 2021-01-16 10:48 UTC by tobieeniafe

#### What does this PR do?
Add vendor certification for lawyer verification

#### Description of Task to be completed?
Add vendor certification for lawyer verification

#### How should this be manually tested?
`PUT /api/v1/user/vendor/certify`

#### What are the relevant pivotal tracker stories?
#176454681

2021-01-16 12:05 UTC, andela-hpopoola requested changes
Thank you for working on this. I left a few comments to ensure we test for all edge cases.

2021-01-16 12:05 UTC, andela-hpopoola commented on server/services/user.service.js
> +    throw new ErrorHandler(httpStatus.PRECONDITION_FAILED, 'Vendor has not been verified');
Might want to use the company name here too to make the message more personalized.


```suggestion
      throw new ErrorHandler(httpStatus.PRECONDITION_FAILED, `${user.vendor.companyName} must be verified before approval as a certified vendor`);
```

2021-01-16 12:05 UTC, andela-hpopoola commented on server/services/user.service.js
> +  if (!user) {
Let's add a test for this 🙏🏽

2021-01-16 12:05 UTC, andela-hpopoola commented on server/services/user.service.js
> +  if (user.role !== USER_ROLE.VENDOR) {
Let's add a test for this too 🙏🏽

2021-01-16 21:45 UTC, tobieeniafe commented on server/services/user.service.js
> +    throw new ErrorHandler(httpStatus.PRECONDITION_FAILED, 'User is not a vendor');
if the user role is not vendor, then the user can't have `user.vendor.companyName`

2021-01-18 08:06 UTC, andela-hpopoola approved these changes
Looks good to me. Thank you for your hard work on this. I left 2 non-blocking comments, feel free to merge after resolving.

2021-01-18 08:06 UTC, andela-hpopoola commented on server/services/user.service.js
> +    throw new ErrorHandler(httpStatus.PRECONDITION_FAILED, 'User is not a vendor');
That is so true 🤦🏽 .  Let's use `User is not a registered vendor`

2021-01-18 08:06 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +        const unverifiedVendor = UserFactory.build(
```suggestion
        const unVerifiedVendor = UserFactory.build(
```

2021-01-18 08:49 UTC, merged