#176533740 make vendor unverified when info changes
Highrachy/ballers-api pull request #102
Opened 2021-01-18 09:43 UTC by tobieeniafe

#### What does this PR do?
Change vendor to unverified when info changes

#### Description of Task to be completed?
Change vendor to unverified when info changes

#### How should this be manually tested?
`PUT /api/v1/user/vendor/update`
`PUT /api/v1/user/vendor/director`

#### What are the relevant pivotal tracker stories?
#176533740

2021-01-18 16:47 UTC, andela-hpopoola requested changes
Thank you for working on this. 

For this to work effectively, as we would want the vendor to also update some of his information without putting him back to an `Unverified` status. Remember that `Unverified` will make the user unable to do basic stuff.

I think we need to update the `/user/update/` endpoint to support the updates for the following vendor information:
- adding of directors
- website
- adding of social media (updating and deleting should be done via a different endpoint)

We can do the social media story in a different PR when we need it though.

Thank you.

2021-01-18 16:47 UTC, andela-hpopoola commented on server/services/user.service.js
> +        'vendor.verified': false,
I don't think we need to update this to false as it would prevent vendors from adding new directors and signatories.

2021-01-18 22:55 UTC, tobieeniafe commented on server/services/user.service.js
> +        'vendor.verified': false,
I believe editing a director info should make the vendor `unverified`. A case scenario where there a verified director's info is edited into fake information is very possible and would be missed. Which circumvents the whole process of director verification

2021-01-18 23:02 UTC, tobieeniafe commented
> Thank you for working on this.
> 
> For this to work effectively, as we would want the vendor to also update some of his information without putting him back to an `Unverified` status. Remember that `Unverified` will make the user unable to do basic stuff.
> 
> I think we need to update the `/user/update/` endpoint to support the updates for the following vendor information:
> 
> * adding of directors
> * website
> * adding of social media (updating and deleting should be done via a different endpoint)
> 
> We can do the social media story in a different PR when we need it though.
> 
> Thank you.

A vendor would be able update `phone` and `address` from `/user/update` without becoming unverified tho

2021-01-19 07:32 UTC, andela-hpopoola requested changes
Thank you for the updates. I believe this shouldn't affect the previous service for updating vendor information. I left a few comments on this, though. Thank you.

2021-01-19 07:32 UTC, andela-hpopoola commented on server/services/user.service.js
> +    delete updatedUser.phone;
Not sure why you are deleting this and others below.

2021-01-19 07:32 UTC, andela-hpopoola commented on server/services/user.service.js
> +    const stepToReview = {
The  purpose of adding the non essential items here is to allow vendors update their information without triggering a review from the admin. Not sure why you reintroduced it here again?

2021-01-19 07:32 UTC, andela-hpopoola commented on server/services/user.service.js
> +    vendor.verification = { ...vendor.verification, ...stepToReview.verification };
I believe this service shouldn't touch the verification step.

2021-01-19 07:32 UTC, andela-hpopoola commented on server/services/user.service.js
> +  // if (
Not sure why you are removing this here. This is necessary during the initial verification step.

2021-01-19 07:32 UTC, andela-hpopoola commented on server/services/user.service.js
> +    // (updatedVendor.vendor.socialMedia && updatedVendor.vendor.socialMedia.length > 0) ||
Social media and website are necessary too during the initial verification.

2021-01-19 07:32 UTC, andela-hpopoola commented on server/services/user.service.js
> +  // if (
Can we return this, please?

2021-01-19 07:32 UTC, andela-hpopoola commented on server/services/user.service.js
> +        'vendor.verified': false,
Thank you for the observation. After much thought, I have the following comments:

1. Directors information are needed before verification to ensure the vendor is legit
2. Directors are no longer needed after verification. However, Signatories will still be used for offer letters.
3. Adding and Updating a director information into fake information doesn't add value to a scammer as the director is not used anywhere else. It might affect the signatory because that would mean that a fake signature will be on the offer letter but I don't think it is a major concern.
4. My major concern is that making the vendor `unverified` after they have been verified just because the director's information (like phone number) was updated is a major deal breaker because this would prevent the vendor from doing every major thing like confirming payments, allowing people to view their properties, updating their properties e.t.c
5. Even if we want to make them unverified, it should be only when a signatory is added not because a director is added.

2021-01-19 07:47 UTC, andela-hpopoola commented on server/services/user.service.js
> +  const updatedUser = updateInfo;
We could make use of updatedUser from the parameter 🤷🏽‍♂️

2021-01-19 09:47 UTC, closed without merging