#176630222 add role and merge get all users & vendor functions
Highrachy/ballers-api pull request #112
Opened 2021-01-28 21:17 UTC by tobieeniafe

#### What does this PR do?
Add `role` as parameter and merge get all users & vendor functions. Deprecate `/api/v1/user/vendor/all` endpoint.

#### Description of Task to be completed?
Add `role` as parameter and merge get all users & vendor functions. Deprecate `/api/v1/user/vendor/all` endpoint.

#### How should this be manually tested?
`GET /api/v1/user/all`

#### What are the relevant pivotal tracker stories?
#176630222

2021-01-29 05:38 UTC, andela-hpopoola requested changes
Thank you for working on this. Awesome job as usual, I believe this will be a good stepping stone for the filter implementation. 

I also believe that we might still deprecate the `getAllRegisteredUsers` service and use an encompassing solution to cater for similar endpoints.

2021-01-29 05:38 UTC, andela-hpopoola commented on server/controllers/user.controllers.js
>    getAllRegisteredUsers(req, res, next) {
We might need to deprecate this service too and create a `getAllUsers` that works with filter and do all of the hardwork for services like this. 

In the new implementation, we can do the following to get this
- to get all vendors, we will use the `role=2` filter (we can also use role=vendor from the request and map to 2 in the services)
- to get all certified users, we will use the `registered=true` filter
- to get registered vendors, we will use the `role=2&registered=true` filter
- to get all certified vendors, we will use the `role=2&certified=true` filter e.t.c.

2021-01-29 05:38 UTC, andela-hpopoola commented on server/services/user.service.js
> +    userOptions.unshift({
Not sure if this will still be needed if we are listing all users.

2021-01-29 05:38 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +    context('when role for vendor is passed', () => {
Can we ensure we test for editors too and admin roles too.

2021-02-01 07:49 UTC, andela-hpopoola commented on server/controllers/user.controllers.js
> +    const {
I think it is better to leave the destructuring for the service so that we have just one point to update the query information instead of multiple places.

2021-02-01 08:09 UTC, andela-hpopoola requested changes
Thank you for the updates. Added a few comments to guide you. Thank you.

2021-02-01 08:09 UTC, andela-hpopoola commented on server/services/user.service.js
> +  role,
You might just destructure page and limit and pass the rest to query to prevent multiple updates as the remaining values will be later grouped.

```js
export const getAllUsers = async ({ page = 1, limit = 10, ...query} => ....
```

2021-02-01 08:09 UTC, andela-hpopoola commented on server/services/user.service.js
> +          { role: role ? parseInt(role, 10) : { $exists: true } },
Can you create a loop so that we add the property only if it is needed. 

Another pointer is to group all the filters into different data types and use a loop to create the object.

For example:

```js
// Disclaimer: This is just a thought process, this code is not intended as the final code so it is not safe or tested. Please feel free to change everything or the whole implementation into something better

// all queries are saved here
let filterQuery = [];

// we would have boolean keys, time keys e.t.c.
// any property that doesn't satisfy any of this group, we would handle them individually
const stringKeys = [
'firstName',
'lastName',
'email'
'phone'
'referralCode',
];
// loop that will be repeated for each group
  stringKeys.forEach((key) => {
    if (query[key]) { // query is destructed from above comment
      filterQuery.push { [key]: ({ $regex: key, $options: 'i' });
    }
  });

 // same loop is done for time-based filters, boolean filters, number filters, and special filters

// After the loop, you could can use filterQuery on line 282:
  $match: {
        $and: filterQuery
  }
...

```

2021-02-01 08:09 UTC, andela-hpopoola commented on test/services/user.service.test.js
> +        const users = await getAllUsers({});
Can we set a default object for the service so that we don't edit this test.

2021-02-01 08:09 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +
We need a comprehensive test for the filters
1. A looped test to test all the filters one by one
2. Another test to test combined filters and ensure they work as expected.

2021-02-01 18:19 UTC, tobieeniafe commented on server/helpers/constants.js
> +    default: null,
if the default isn't null, adding `address` to the filter would return not return newly registered users that haven't added their addresses.

2021-02-01 18:20 UTC, tobieeniafe commented on server/services/user.service.js
> +  companyName,
adding fields that are not added on creation, breaks the filter because of the `{ $exists: true }` field which acts as a wildcard search

2021-02-01 18:37 UTC, andela-hpopoola commented on server/services/user.service.js
> +  companyName,
I am not sure I understand your point. I feel we should not add { $exists: true } as a default for filters that are not given in a request. If the only property in `req.query` is `firstName` then the query should run with `firstName` only and not use `$exists: true` for other ones. 

At the end of the day the generated `and` query should be like if a user searches for the firstName only:
```js
$and: [
{ firstName: { $regex: firstName, $options: 'i' }  }
]
```

If it is `firstName` and `lastName`, then the generated query should look like this:
```js
$and: [
{ firstName: { $regex: firstName, $options: 'i' }  },
{ lastName: { $regex: lastName, $options: 'i' }  },
]
```

I believe the query should only **include what is needed**, we should not set a default for what the user is not searching for. I don't see any reason why we should use `exists: true` if a field is not given in the query.

The same thing applies to the address comment above this.

2021-02-01 18:38 UTC, andela-hpopoola commented on server/services/user.service.js
> +  role,
Achieving the above comment is possible with the logic explained here:
https://github.com/Highrachy/ballers-api/pull/112#discussion_r567625021

2021-02-02 07:09 UTC, andela-hpopoola requested changes
Thank you for working on this. I left a few comments and would also explain more concepts that could be used to simplify the filter process during standup.

2021-02-02 07:09 UTC, andela-hpopoola commented on server/services/user.service.js
> +  const filterQuery = [{ role: query.role ? parseInt(query.role, 10) : { $exists: true } }];
`role` should be added as an optional filter too. It can be added as `integerKeys`

2021-02-02 07:09 UTC, andela-hpopoola commented on server/services/user.service.js
> +  const stringKeys = ['firstName', 'lastName', 'email', 'phone', 'referralCode'];
`phone2` is missing here

2021-02-02 07:09 UTC, andela-hpopoola commented on server/services/user.service.js
> +  const vendorStringKeys = ['companyName'];
`entity` and `redanNumber` are missing here

2021-02-02 07:09 UTC, andela-hpopoola commented on server/services/user.service.js
> +
Address filters are missing here.

2021-02-02 07:09 UTC, andela-hpopoola commented on server/services/user.service.js
> +
We are supposed to add date filters but it is more complicated. Maybe when this has finally taken shape.

2021-02-02 07:09 UTC, andela-hpopoola commented on server/services/user.service.js
> +      filterQuery.push({ [key]: { $regex: query[key], $options: 'i' } });
The next step is to create a generic function to generate for each datatype. I will explain better during standup.

2021-02-02 07:09 UTC, andela-hpopoola commented on test/services/user.service.test.js
> +        const users = await getAllUsers({});
Can you please fix this before resolving or let me know the challenges involved that is preventing the fix?

2021-02-02 07:09 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +            [method](`${endpoint}?role=${user}`)
Nice work here, however, we need to write tests for all the filters used in the code to ensure that they work as expected.

2021-02-02 10:43 UTC, tobieeniafe commented on test/services/user.service.test.js
> +        const users = await getAllUsers({});
the object can be empty, the function was only adjusted due to the switch from optional parameters `page` & `limit` to an object

2021-02-02 21:36 UTC, andela-hpopoola requested changes
Thank you for working on this. This is really taking shape and we are almost through with the implementation. Apart from the single tests, every other thing looks legit and almost done. Nice work.

2021-02-02 21:36 UTC, andela-hpopoola commented on server/helpers/filters.js
> +  let pre = '';
The 4 lines can be converted into 1 when a ternary operator is used.

```js
  const pre = prefix.length > 0 ? `${prefix}.` : '';
```

2021-02-02 21:36 UTC, andela-hpopoola commented on server/helpers/filters.js
> +      filterQuery.push({ [`${pre}${key}`]: { $regex: query[key], $options: 'i' } });
It is bad practice to mutate variables outside a function. It is better to return the result so that it can be used as needed.

2021-02-02 21:36 UTC, andela-hpopoola commented on server/helpers/filters.js
> +export const filterIntegerKeys = (filterQuery, integerArray, query, prefix = '') => {
These functions have lots of repetition. I think we can compress them into one. Here is the update I came up with for the filter.js helper

```js
export const FILTER_TYPE = {
  BOOLEAN: 'boolean',
  INTEGER: 'integer',
  STRING: 'string',
};

export const buildFilterQuery = (stringArray, query, type, prefix = '') => {
  const pre = prefix.length > 0 ? `${prefix}.` : '';

  return stringArray.reduce((acc, key) => {
    if (query[key]) {
      switch (type) {
        case FILTER_TYPE.BOOLEAN:
          acc.push({ [`${pre}${key}`]: query[key] === 'true' });
          break;

        case FILTER_TYPE.INTEGER:
          acc.push({ [`${pre}${key}`]: parseInt(query[key], 10) });
          break;

        case FILTER_TYPE.STRING:
          acc.push({ [`${pre}${key}`]: { $regex: query[key], $options: 'i' } });
          break;

        default:
          break;
      }
    }
    return acc;
  }, []);
};


```

2021-02-02 21:36 UTC, andela-hpopoola commented on server/services/user.service.js
> +  filterStringKeys(filterQuery, stringKeys, query);
For the above  comment, instead of mutating the filterQuery variable, we can get the build it with the function above:

```js
  const filterQuery = [
    ...buildFilterQuery(booleanKeys, query, FILTER_TYPE.BOOLEAN),
    ...buildFilterQuery(integerKeys, query, FILTER_TYPE.INTEGER),
    ...buildFilterQuery(stringKeys, query, FILTER_TYPE.STRING),
    ...buildFilterQuery(addressStringkeys, query, FILTER_TYPE.STRING, 'address'),
    ...buildFilterQuery(vendorBooleanKeys, query, FILTER_TYPE.BOOLEAN, 'vendor'),
    ...buildFilterQuery(vendorStringKeys, query, FILTER_TYPE.STRING, 'vendor'),
  ];
```

Even though they look similar, this will be easier to debug since the function is a pure function. When you are chanced, you can try to read more on mutations and pure functions.

2021-02-02 21:36 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +            expectsPaginationToReturnTheRightValues(res, {
Tests for single filters are still missing.

2021-02-03 02:19 UTC, tobieeniafe commented on test/services/user.service.test.js
> +        const users = await getAllUsers({});
the function takes in an object parameter, which contains two default values `page` & `limit`. Calling the function without the object in it makes `page` & `limit` undefined. Thereby causing an error.

2021-02-03 05:31 UTC, andela-hpopoola requested changes
Thank you for the updates. We are almost getting there 💪🏽

2021-02-03 05:31 UTC, andela-hpopoola commented on server/helpers/filters.js
> +export const buildFilterQuery = (arrayWithKeys, query, type, prefix = '') => {
Lets use `filterKeys` here, `arrayWithKeys` is not descriptive.

```suggestion
export const buildFilterQuery = (filterKeys, query, type, prefix = '') => {
```

2021-02-03 05:31 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +      const filteredUrl = JSON.stringify(dummyVendor1Details)
I think it is better to use the queryString to generate the filter params. Also, the name should be filteredParams as it contains a list of parameters not the entire URL.

```suggestion
      const filteredUrl = querystring.stringify(dummyVendor1Details);
```

You need to import querystring at the top of the test file to use the above

```js
import querystring from 'querystring';
```

Please take a minute to go through it in the documentation since it contains lots of valuable information to cater for query strings.

https://nodejs.org/api/querystring.html

2021-02-03 05:38 UTC, andela-hpopoola commented on test/services/user.service.test.js
> +        const users = await getAllUsers({});
I think I understand you now but I still dont think you understood my point. You could have fixed this by using a default parameter for getAllUsers.

For example, adding a default parameter here (= {}) should fix the issue:

```js
export const getAllUsers = async ({ page = 1, limit = 10, ...query } = {}) => {
```

2021-02-03 06:05 UTC, andela-hpopoola commented
Can we update the title of the PR to reflect the functionality being implemented in it.

```
implement filter functionality for `GET users/all` endpoint
```

2021-02-03 21:26 UTC, andela-hpopoola requested changes
Thank you for working on this. I left a few more comments, especially on the tests arrangement and to ensure the tests are actually touching everypart needed for filter so that they will be easier to duplicate in the future.

Nice work and thank you for making adequate efforts to work on the udpates.

2021-02-03 21:26 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +    context('sending single parameter', () => {
Instead of repeating this statement, you could have grouped similar tests under just one heading.

2021-02-03 21:26 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +              expectsPaginationToReturnTheRightValues(res, {
I think you will also need to test that the right value is returned. For example, For `firstName` as `vendor1`, it is better to test that the returned object has a firstName of `vendor1`.

2021-02-03 21:26 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +    context('sending single parameter', () => {
I think this should be used be `when sending multiple parameters`.

2021-02-03 21:26 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +    context('sending single parameter', () => {
I think it is better to define all the fields of a single user here and use a loop to confirm that the exact field is returned. I noticed that you defined just 2 fields for `filterToReturnOneResult`; there should be no compromise here, we need to define everything used for the filter.

For this part, You will create a user containing all the parts we used in filter and send the request to confirm that it is returned.

Also, it is better for the user to be defined in this block to make it easier to understand to our future selves or anyone going reading the code in the future. Don't forget the code is over 3000 lines, it can be very difficult to find variables especially when it is not written by you.

2021-02-03 21:26 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +    context('sending single parameter', () => {
For this, you can just add two users with the same multiple parameters and use a single test to confirm that the two users are returned. We don't need a loop here since the test for a single parameter already ensures that all parameters work as expected.

Also, apart from pagination, you want to also test that the right values are returned.

2021-02-03 21:26 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +    context('sending single parameter', () => {
This is not needed. The above test already covers this. Instead we should write test for when no parameter is satisfied, it should return an empty result.

2021-02-03 21:26 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +    const filterToReturnOneResult = {
Definitions like this are better defined inside their tests assertion so that they are easier to locate.

2021-02-03 21:26 UTC, andela-hpopoola commented on server/helpers/filters.js
>          case FILTER_TYPE.BOOLEAN:
It looks like you have not added the DATE datatype.

2021-02-04 06:08 UTC, andela-hpopoola requested changes
Thank you for working on this. The tests still need some perfection to increase our confidence level, so I dropped a few comments on the best way to go about it. Thank you.

2021-02-04 06:08 UTC, andela-hpopoola commented on server/services/user.service.js
I think the following are still needed for the filter:
```
- banned status - necessary to search to banned user if an admin wants to unban
- VendorInfo status - necessary to search for pending vendor verification based on some criteria
```

2021-02-04 06:08 UTC, andela-hpopoola commented on server/services/user.service.js
> +    ...buildFilterQuery(dateKeys, query, FILTER_TYPE.DATE),
Since this is sorted alphabetically, dateKeys should come after booleanKeys. Same with the one below too 😏 .

2021-02-04 06:08 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +      context('sending single parameter', () => {
I dont think this is needed, not sure why we need to separate or test role only here when we have a test that loops through every single parameter.

2021-02-04 06:08 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +              expect(res.body.result[0]._id).to.be.eql(dummyVendor1._id.toString());
We also want to add tests to ensure the filtered parameters are returned.

2021-02-04 06:08 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +          it('returns matched users', (done) => {
You also need to test that it is only one result that is returned.

2021-02-04 06:08 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +        const singleParameterFilers = {
This should contain all the properties in the filter parameter as recommended in previous comments.

All of this

```js
  const stringKeys = ['firstName', 'lastName', 'email', 'phone', 'phone2', 'referralCode'];
  const integerKeys = ['role'];
  const booleanKeys = ['activated'];
  const vendorBooleanKeys = ['verified', 'certified'];
  const vendorStringKeys = ['companyName', 'entity', 'redanNumber'];
  const addressStringkeys = ['city', 'country', 'state', 'street1', 'street2'];
```

You can define all the values in an Object and use the Object to create the user.

2021-02-04 06:24 UTC, andela-hpopoola commented
To be more explicit, the test format should satisfy the following:

- When no filter is used, it returns all users in the database (necessary to ensure that no filter is not blocking the gell all users service). This has already been implemented in the `User pagination` test case
- When an unknown filter is used, it still returns all users in the database
- When a known filter with no result is used, it returns 0 user
- When a single filter is used, it returns the user that satisfied the filter. To ease this, we can use one user with predefined filters and loop over each filter. This is the most important part of the test as this will test all the filters we have used to ensure they are working as expected
- When a single filter is used that satisfies multiple users, it returns the multiple users. The test for the roles satisfies this, we only need to properly explain it in the test.
- When multiple filters are used, it returns the users that satisfy the multiple filters are returned.

Note that I used `When` to start all of my statements above to denote the `context` block. Similar contexts should be grouped together. Thank you.

2021-02-04 19:11 UTC, tobieeniafe commented on server/services/user.service.js
adding banned would require us to change the user model from `banned.status` to `banned.banned` to make it usable in the filter function as passing `status` alone as a parameter isn't descriptive

2021-02-04 20:11 UTC, andela-hpopoola commented on server/services/user.service.js
Changing the user model because of filter is not a good idea.  Are you going to change for other models too because they don't conform to the function we have written. We can always improve the function to cater for this. 

For now, lets treat `banned` as a special variable, so we don't need to include it among the keys used for the function but create another function to generate its own filter. 

Also, we might need to change the filter function to support this type of parameter in the future. Maybe when the PR sounds good to go, I will rewrite the function to cater for cases like this. 

For now, change the `filterQuery` variable to `let` instead of `const`, after generating all the filter queries with the `buildFilterQuery` functions, check if `banned` is included in `req.query`, and push the generated `banned` filter query into the `filterQuery` variable.

2021-02-05 05:41 UTC, andela-hpopoola requested changes
Wow. We are 98% there. Thank you for the hard work. This looks good and almost ready to launch. The pending stuff is to rewrite the buildFilterQuery function and ensure that the filter is case insensitive. 💪🏽

2021-02-05 05:41 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +          companyName: 'dangote plc',
Not sure why this is changed but can we use the proper casing 🙏🏽

2021-02-05 05:41 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +        companyName: 'google nigeria',
Same comment as above.

2021-02-05 05:41 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +          companyName: 'go',
Lets leave this as this to ensure that the filter is case insensitive. Remember, the admin doesn't even know the case the used to save the data, so we must ensure that this is case insensitive.

2021-02-05 05:41 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +        const singleParameterFilters = {
All of this can be placed in their own context too for easier grouping.

```js
     context('when sending single parameter', () => {
         context('when root parameters are sent', () => {
            ...
         })
         context('when banned parameters are sent', () => {
            ...
         })
         context('when vendor parameters are sent', () => {
            ...
         })
     })

```

2021-02-06 16:16 UTC, andela-hpopoola requested changes
Thank you for working on this. We are like 99.5% done. The only thing remaining is to ensure you update the tests to use a single loop for a single filter.

I should approve when this has been done. Thank you and Nice work.

2021-02-06 16:16 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +          Object.keys(singleParameterFilters).map((field) =>
Can we consolidate all of the single tests and use `USER_FILTERS` to filter through all of the filters defined for `Users` as discussed. This has the advantages of ensuring that we don't miss any of the defined filters, makes it easier to update in the future, and makes writing other tests a piece of cake.

2021-02-06 16:16 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +          const singleParameterFilters = {
Can we use a single `Vendor` user instead of an editor  as discussed on Friday to make using the loop possible?

2021-02-06 16:16 UTC, andela-hpopoola commented on test/services/user.service.test.js
> +        const users = await getAllUsers({});
You have not fixed this too? ☝🏽

2021-02-06 17:15 UTC, tobieeniafe commented on test/controllers/user.controller.test.js
> +          Object.keys(singleParameterFilters).map((field) =>
I don't understand?

2021-02-06 17:22 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +          Object.keys(singleParameterFilters).map((field) =>
We discussed this on Friday. We agreed to use just one loop for the single filters test. We discussed removing one vendor from the roles test to enable us to use vendor to test for everything involving user filters (by looping through USER_FILTERS). 

I mentioned on the call that this would enable you to understand how to use the `Object.entries` loop. Apart from the fact that it makes the test easier (as everything will be in one place), the best part is that it forces us to test for all the filters in case we add a new filter in the future and we forget to add a test to it.

USER_FILTERS already has the necessary `keys` and `filter` fields needed for this test, we don't need to split the single test into multiple contexts when we can use just one loop to achieve the same thing in a better way. I hope you understand now.

2021-02-06 17:24 UTC, tobieeniafe commented on test/controllers/user.controller.test.js
> +          Object.keys(singleParameterFilters).map((field) =>
Oh yes, I do. Thanks

2021-02-06 17:29 UTC, tobieeniafe commented on test/controllers/user.controller.test.js
> +          Object.keys(singleParameterFilters).map((field) =>
Could you remind me of the code snippet? Can't seem to remember it ☹️

2021-02-06 17:46 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +          Object.keys(singleParameterFilters).map((field) =>
Sure. The code snippets should be similar to this

https://github.com/Highrachy/ballers-api/blob/9fbca5d3f3e9f060aab0c1dff55e9aa627160c32/server/helpers/filters.js#L11

Here is the algorithm (but using similar variable names from the above link).

1. Get the entries of USER_FILTER
2. Get the `queryKey` from the USER_FILTER entry, and get the **value** of the` queryKey` from the `Vendor` object via the `filterKey`. So the result will be like `[method](`${endpoint}?${queryKey}=${vendorUser[filterKey]}`)`. Not 100% about `vendorUser[filterKey]` though, let me know if you have problems with it.
3. The step above should be used to build the request you are sending to the database
4. Test that the result is equal to Vendor[filterKey] 

I didn't test this, but it should be helpful enough to guide you through the implementation.

2021-02-07 01:10 UTC, tobieeniafe commented
I was able to attempt this and make it run at once, but it passes all except the vendor verification steps.

2021-02-07 09:33 UTC, andela-hpopoola approved these changes
Thank you for your hard work. I have updated the test for the single user and I think everything should be good to go. 

The only thing expected from you is to update the details in the Pull Request description as you didn't explain how the filter will work in the description (you only listed the parameters).

Feel free to merge when ready. 👍🏽

2021-02-07 09:33 UTC, andela-hpopoola commented on server/helpers/filters.js
> +  bankDetailsStatus: { key: 'vendor.verification.bankDetails.status', type: FILTER_TYPE.STRING },
Updated this and similar queryKeys to `bankDetailsStatus` to make it more explicit and understandable.

2021-02-07 09:33 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +const futureDate = add(new Date(), { days: 5 });
Updating other dates to a future date to enable us to filter via today's date. Not 100% sure about the date implementation in the filter though, we can always fix it later.

2021-02-07 09:33 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +          const processNestedObject = (parentObject, objPath) =>
This enables us to read nested property from the object. Necessary for properties like `vendor.companyName`. I didn't place this in a different function because I believe we can make this test a function to test for single properties for other models too.

2021-02-07 09:33 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +                expect(res.body.result[0]._id.toString()).to.be.eql(dummyVendor._id.toString());
This ensures the right user is returned for all the tests.

2021-02-07 19:06 UTC, merged