#176735770 paginate & implement filter functionality for `GET /api/v1/property/all` endpoint
Highrachy/ballers-api pull request #118
Opened 2021-02-07 22:14 UTC by tobieeniafe

#### What does this PR do?
Implement filter functionality for `GET property/all` endpoint

#### Description of Task to be completed?
-Paginate `GET /api/v1/property/all`
-Implement filter functionality for `GET property/all` endpoint.
-Deprecate `/api/v1/property/added-by/:id` endpoint.

#### How should this be manually tested?
`GET /api/v1/property/all?filterKey=value`

#### What are the relevant pivotal tracker stories?
#176735770

2021-02-07 22:18 UTC, andela-hpopoola requested changes
Thank you for working on this. I did a quick look and this looks good to me. Waiting for the filter so that I can approve asap. Nice work.

2021-02-07 22:18 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +              expectResponseToContainNecessaryPropertyData(res.body.result[0]);
Nice one here 🙌🏽

2021-02-07 22:23 UTC, tobieeniafe commented
@andela-hpopoola the property filter seems to be a little bit more complex compared to the user filter. I'm considering deprecating `/api/v1/property/added-by/:id` and `/api/v1/property/search` endpoints, since this endpoint would be able to cater for them all. But I'm also considering user access level rights. Eg a vendor using `/api/v1/property/all?addedBy=anotherVendorId` and other related cases. Thoughts?

2021-02-07 22:58 UTC, andela-hpopoola commented
Nice observations. Thank you for raising this. 

> I'm considering deprecating /api/v1/property/added-by/:id and /api/v1/property/search endpoints, since this endpoint would be able to cater for them all

Let's do this in another PR when we have sorted out the filter functionality

>  But I'm also considering user access level right issues. Eg a vendor or a user using /api/v1/property/all?addedBy=anotherVendorId and other related cases. Thoughts?

I don't think this should be a major issue. We will define different Filters constant based on the access level. That means we will have 3 filters constant to cater to the different access level. Even if a vendor tries use `addedBy`, as long as it is not defined for the vendor role in the vendor filter constant, it will be naturally ignored and will give us no security issues. We should also add tests to verify that this works as expected after implementation.

Thank you for raising this and asking 👍🏽

2021-02-08 20:14 UTC, tobieeniafe commented
@andela-hpopoola the test for `createdAt` seems to be failing as it's generating a new property `id` can't seem to figure out why. Perhaps a fresh set of eyes might. Also, I added the `bathrooms` to the property model in this PR as I needed to test it with the filter.

2021-02-09 06:03 UTC, andela-hpopoola requested changes
Thank you for working on this. As you have noticed, all our hard work paid off for filters and the filter functionality looks fun to work with 😉.

I left a few comments on this to start with. We still have some edge cases we need to consider but we can do those ones gradually.


Next time, I think it would be better to do the bathroom inclusion in a later PR. We can merge that PR first while you include the filter implementation here. You are able to get away with it, but it might make the PR more complex in the future.

We shouldn't deprecate user search for the `GET /property/all` as the endpoint is not targeted for users. Also, looking through the search service, the implementation is tailored towards a more customized search (involving areas, price, and others) which we didn't cover here.

I believe that we should be able to deprecate the `addedBy` vendor endpoint in a later PR.

Also, we need to implement a functionality to cater for greater than, less than, and equal to for some query parameters.

2021-02-10 01:33 UTC, tobieeniafe commented on test/controllers/property.controller.test.js
> +        createdAt: futureDate,
the issue is the format of `futureDate`. The endpoint expects the date in `yyyy-mm-dd` format.  `futureDate` returns the date in words causing an invalid date on the endpoint.

2021-02-10 02:06 UTC, tobieeniafe commented on test/controllers/property.controller.test.js
> +          user: vendorUser,
the vendor becomes unverified in the helper file. (see `test/helpers.js` line `346`

2021-02-10 02:09 UTC, tobieeniafe commented on server/services/property.service.js
>      propertiesOptions.unshift({ $match: { addedBy: ObjectId(user._id) } });
Tests to cover this already exist. see `property.controller.test.js` lines `1501` & `1518`

2021-02-10 05:47 UTC, andela-hpopoola requested changes
Thank you for the hard work on this. Just a few comments, this should be ready to go after the fix.

2021-02-10 05:47 UTC, andela-hpopoola commented on test/helpers.js
> +export const expectResponseToContainNecessaryPropertyData = (data, object) => {
With the current naming, it is difficult to differentiate the response data from the actual property data.
```suggestion
export const expectResponseToContainNecessaryPropertyData = (response, property) => {
```

2021-02-10 05:47 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +        createdAt: '2021-12-21',
Can we revert this to `futureDate` to ensure that it works as expected. If the problem is with future date, then it is better to fix it than having to use a workaround.

2021-02-10 05:47 UTC, andela-hpopoola commented on test/helpers.js
> +      token = await addUser({ ...user, vendor: { ...user.vendor, verified: false } });
Not sure why you are making all the users here unverified. If we need an unverified vendor, it is better to pass them into the function than forcing all users to be unverified. 

```suggestion   
   token = await addUser(user)
```

2021-02-10 05:47 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +      context('Unknown Filters', () => {
This should be a `describe` block with the updates.

```suggestion
	      describe('Unknown Filters', () => {
```

2021-02-10 05:47 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +      createdAt: new Date(),
Can we add this to the property factory instead?

2021-02-11 00:19 UTC, tobieeniafe commented on test/controllers/property.controller.test.js
> +      createdAt: new Date(),
No we can't. Joi would flag it.

2021-02-11 05:53 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +      createdAt: new Date(),
Thanks for pointing this out.

2021-02-11 06:04 UTC, andela-hpopoola approved these changes
This looks good to go. Thank you for ensuring that this works as expected.

2021-02-11 08:32 UTC, merged