#176843012 add more processes for visitation
Highrachy/ballers-api pull request #119
Opened 2021-02-09 01:40 UTC by tobieeniafe

#### What does this PR do?
Add routes to reschedule and resolve visitations

#### Description of Task to be completed?
Add routes to reschedule and resolve visitations

#### How should this be manually tested?
`PUT /api/v1/visitation/reschedule`
`PUT /api/v1/visitation/resolve`

#### What are the relevant pivotal tracker stories?
#176843012

2021-02-09 06:35 UTC, andela-hpopoola requested changes
Thank you for working on this. The implementation looks solid and you have made lots of thoughts in making this as concise as possible. Thank you for the awesome job.

However, my evil twin decided to make it a little bit more complex 👻  to ensure we have logs of all rescheduled that has been made. In real life scenerio, you never can tell when this will be handy, it is better to have them then to ignore them.

Also, after implementation and adding tests, I believe this should  be good to go. Can't really see a big blocker on this. Thank you and Nice work.

2021-02-09 06:35 UTC, andela-hpopoola commented on mailer/index.js
> +      'Your visitation for property [property name], has been recheduled for [new date]. Visit your dashboard for more information.',
The visitation to [property name] on [previous visitation date], has been rescheduled for [new date] by [user that rescheduled]. [Reason]. Visit your dashboard for more information.

2021-02-09 06:35 UTC, andela-hpopoola commented on server/controllers/visitation.controllers.js
> +        const contentTop = `Your visitation for property ${response.property.name}, has been recheduled for ${visitation.visitDate}. Visit your dashboard for more information.`;
I have updated this, so you might want to include the previous date to make it more clear to the user.

2021-02-09 06:35 UTC, andela-hpopoola commented on server/services/visitation.service.js
> +  const response = { mailDetails, property };
This is not needed since they are not reused, it is easier to read if we write the output out directly instead of assigning them to response.

2021-02-09 06:35 UTC, andela-hpopoola commented on server/services/visitation.service.js
> +    return { visitation: rescheduledVisitation, response };
```suggestion
    return { visitation: rescheduledVisitation, mailDetails, property };
```

2021-02-09 06:35 UTC, andela-hpopoola commented on server/controllers/visitation.controllers.js
> +      .then(({ visitation, response }) => {
I don't think we need response here. Can't think of an added advantage of using it over getting the variables directly 🤸🏽‍♂️

2021-02-09 06:35 UTC, andela-hpopoola commented on server/services/visitation.service.js
> +export const rescheduleVisitation = async ({ user, visitationInfo }) => {
Let's add a reschedule reason here to make the other party know why the reschedule was necessary. This might not look necessary but from experience, you will want to keep as much information as possible for cases when users complain a vendor is not around or a vendor complains that a user is not serious. This will allow the admin to know the real fact.

This should be an array that contains the following:

```
reschedule : [{
  reason: ..., // the reason the reschedule was made
  rescheduleFrom: .. // previous date in the db
  rescheduleTo: // new date the reschedule moved to
  date: ...,  // date the reschedule was made. Should be datetime format
  rescheduleBy: // String => Vendor / User. (we can get their ID from the visitation id, so no need to use an id here.
}]
```

2021-02-10 06:05 UTC, andela-hpopoola requested changes
Thank you for working on this. This looks very good and thoughtful. 

However, when reviewing the code, I noticed that it might be better to allow a user to cancel a visitation too so that the reason can be stated in the rescheduleLog (not sure if we should give the vendor the same power so you might have to confirm this with Nnamdi 😜 ). Thank you.

2021-02-10 06:05 UTC, andela-hpopoola commented on test/controllers/visitation.controller.test.js
> +        expect(sendMailStub).to.have.be.calledWith(EMAIL_CONTENT.RESCHEDULE_VISIT);
Can we test that the mail is sent to the right person - user or vendor. We don't want to mix this up, so it is better to have a test to ensure this sends the mail to the right person.

2021-02-10 15:50 UTC, tobieeniafe commented on test/controllers/visitation.controller.test.js
> +        expect(sendMailStub).to.have.be.calledWith(EMAIL_CONTENT.RESCHEDULE_VISIT);
How do you propose we go about this? Adding the `vendor` or `user` object throws an error.

2021-02-10 16:55 UTC, andela-hpopoola requested changes
Thank you for working on this and making the necessary updates. I left a few comments, the most important is combining the services for `cancelVisitation` and `rescheduleVisitation`. Once this has been fixed, we should be able to merge this with no issues. Thank you.

2021-02-10 16:55 UTC, andela-hpopoola commented on server/services/visitation.service.js
> +  const mailDetails = await getUserById(visitation.vendorId);
Lets update this to `vendorDetails` or something similar

2021-02-10 16:55 UTC, andela-hpopoola commented on mailer/index.js
> +      'The visitation to [property name] on [previous visitation date], has been cancelled by [user that rescheduled]. [Reason]. Visit your dashboard for more information.',
```suggestion
      'The visitation to [property name] on [previous visitation date], has been cancelled by [user]. [Reason]. Visit your dashboard for more information.',
```

2021-02-10 16:55 UTC, andela-hpopoola commented on server/controllers/visitation.controllers.js
> +        const contentTop = `The visitation to ${property.name} on ${visitation.visitDate}, has been cancelled by ${user.lastName} ${user.firstName}. Reason: ${visitation.rescheduleLog[0].reason}. Vis
Not sure if we should use the `LastName FirstName` naming convention. In the international market, it is always presented as `FirstName LastName`. Maybe we should have an helper function to generate someone's full name so that it will be easier to update irrespective of the format.

```suggestion
        const contentTop = `The visitation to ${property.name} on ${visitation.visitDate}, has been cancelled by ${user.firstName} ${user.lastName}. Reason: ${visitation.rescheduleLog[0].reason}. Visit your dashboard for more information.`;
```

2021-02-10 16:55 UTC, andela-hpopoola commented on test/controllers/visitation.controller.test.js
> +              expect(res.body.message).to.be.eql('The visitation has already been resolved');
Can we add `mailStubCount` to these tests to be sure that the mails are not sent if there are errors?

2021-02-10 16:55 UTC, andela-hpopoola commented on server/controllers/visitation.controllers.js
> +          visitation.rescheduleLog[0].rescheduleFrom
This should be converted into a human-readable date.

2021-02-10 16:55 UTC, andela-hpopoola commented on server/services/visitation.service.js
> +export const cancelVisitation = async ({ userId, visitationInfo }) => {
The` rescheduleVisitation` service and the `cancelVisitation` service have so much in common that I feel it is better to combine them together into one function like `processVisitation` service that takes an action. They should have their different endpoints to ensure that `cancelVisitation` is only accessible by the user.

```js
export const processVisitation = async ({ userId, visitationInfo, action }) => {
```
`action` would be used to determine if the service should set the log as RESCHEDULED OR CANCELLED.

2021-02-10 16:55 UTC, andela-hpopoola commented on server/services/visitation.service.js
> +  if (!visitation) {
Not too important (for improved coverage), can we add a test for this?

2021-02-10 16:57 UTC, andela-hpopoola commented on test/controllers/visitation.controller.test.js
> +        expect(sendMailStub).to.have.be.calledWith(EMAIL_CONTENT.RESCHEDULE_VISIT);
Feel free to ignore, currently too busy to troubleshoot this now.

2021-02-11 06:23 UTC, andela-hpopoola approved these changes
Thank you for your hard work on this. I left a few comments but feel free to merge when you resolve them. Awesome job bro, you deserve a :hi5:.

![](https://media.giphy.com/media/kwedEuRomWtlMqh16v/giphy-downsized.gif)

2021-02-11 06:23 UTC, andela-hpopoola commented on server/controllers/visitation.controllers.js
> +          user.vendor.companyName ? user.vendor.companyName : `${user.firstName} ${user.lastName}`
Lets create a function for this so that it would be easier to update the name format in the future. 

```suggestion
          user.vendor.companyName ? user.vendor.companyName : `${getUserName(user)}`
```

2021-02-11 06:23 UTC, andela-hpopoola commented on server/services/visitation.service.js
> +      rescheduleFrom: action === 'reschedule' ? visitation.visitDate : null,
Lets define the actions in a constant to make it consistent and save us from unintended bug 🙏🏽 

```js
const PROCESS_VISITATION_ACTION = {
   CANCEL: 0,
   RESCHEDULE: 1,
}
```

2021-02-11 06:23 UTC, andela-hpopoola commented on server/helpers/dates.js
> +export const convertDateToWords = (date) => format(date, 'd MMM yyyy');
We should use the Long format in emails so that it is more explicit. The short one can be used for other API messages that require a human-readable format.
```suggestion
export const convertDateToLongHumanFormat  = (date) => format(date, 'dddd, Do MMMM YYYY');
export const convertDateToShortHumanFormat = (date) => format(date, 'ddd, MMM D, YYYY');
```

2021-02-11 06:23 UTC, andela-hpopoola commented on server/services/visitation.service.js
> +  let update;
```suggestion
  let visitationInfo;
```

2021-02-11 10:53 UTC, merged