#176955705 generate next payment dates for offer
Highrachy/ballers-api pull request #127
Opened 2021-02-18 00:44 UTC by tobieeniafe

#### What does this PR do?
Generate next payment dates for offer

#### Description of Task to be completed?
Generate next payment dates for offer

#### How should this be manually tested?
`POST /api/v1/offer/create`

#### What are the relevant pivotal tracker stories?
#176955705

2021-02-18 06:57 UTC, andela-hpopoola requested changes
Thank you for working on this. This looks like a good start and we can always work on improving the necessary stuff in other PRs. I left a couple of comments, I want us to do this one at a time, so let's focus more on writing tests to be certain that the payment schedules work as expected.

#### Next PR implementation

The next payment should focus on how to get the next payment and resolve old payments for previously saved in the next payment model. This model is super necessary for cron jobs so we should be some thoughts on how/when to generate a new record here and the necessary fields to put. 

Since you worked on the spike, you should know the other things I might have missed. However, I am sure we will need the following 
- offerId (to connect the payment to the model)
- userId (for sending mails)
- propertyId (if we can easily get property info via offerId, then this is not necessary)
- vendorId (enables us to show the vendor the next payment they are expecting)
- amount (the next payment to be made)
- expiresOn (the date the next payment expires) We can use this to send a mail/ message before a payment expires. Sending of mails can be based on predefined days like a day before, 7 days before, 30 days before and 60 days before expiry date
- status (open or closed, a row can be closed by 2 ways, automatically or via a transaction. We should automatically close open rows that have expired, we need to  think on the best way to generate another one the next expiry date and amount if we close automatically -- maybe a cron job to close and create a new nextPayment row 🤷🏽‍♂️ )

// not sure how much of this we would need
- resolvedViaTransaction - (is it resolved by cronjob or transaction)
- transactionId - (Id of transaction used to resolve this)
- resolvedDate - (date the payment was resolved)

I am sure I might still be missing some stuff or edge cases since I didn't do a complex deep dive into this but I hope you can fill gaps and make this work as expected. 

Please note that this is still complicated to me too as your spike didn't cover much technical base, so expect a few changes even after implementing some stuff. I will prefer we take this slow and steady to totally get what we are doing. 

Thank you.

2021-02-18 06:57 UTC, andela-hpopoola commented on server/services/offer.service.js
> +  const { paymentFrequency } = offer;
This can be defined after paymentDates so as to get the variables for `numberOfPaymentsToBeMade`.

```suggestion
  const { paymentFrequency, totalAmountPayable, initialPayment, periodicPayment  } = offer;
```

2021-02-18 06:57 UTC, andela-hpopoola commented on server/services/offer.service.js
> +    const paymentDate = format(
We need the paymentDate with the amount they will pay. Don't forget that initial payment details should come first

2021-02-18 06:57 UTC, andela-hpopoola commented on server/services/offer.service.js
> +      paymentDates,
On a better thought, we might not even need to save this in the database as we can always calculate it when it is needed. Also, we don't know everything we need to save now, so it is better not to waste time implementing this.

2021-02-18 06:57 UTC, andela-hpopoola commented on server/services/offer.service.js
> +      paymentDates,
In another PR, let's save the next payment in the `nextPayment` model. We will need to calculate the next payment to be made and save it in the model.

Here are the events I think would trigger updating the nextPayment model:

1. A user accepts an offer letter
2. A users payment is confirmed
3. Expiry date of the payment has been exceeded

These are the ones I can think of for now, there might be more but we would keep updating them later.

2021-02-18 06:57 UTC, andela-hpopoola commented on server/services/offer.service.js
> +const generatePaymentDates = (offer) => {
```suggestion
const generatePaymentSchedules = (offer) => {
```

This PR is already getting messy, lets conclude this PR by writing services tests to confirm that this function works as expected. Lets test it with various cases like:

1. When totalAmountPayable is equal to  initial payment
2. When totalAmountPayable is slightly bigger than initial payment (i.e different is not up to periodic payment) 
3. When totalAmountPayable is greater than initial Payment so that we can have a couple of payments to be made
4. Testing same values with other paymentFrequency to be sure they work as expected
5. Other tests you feel is necessary to ensure this works as expected.

2021-02-18 17:02 UTC, andela-hpopoola commented on server/services/offer.service.js
> +      offer.handOverDate === 'string' ? parseISO(offer.handOverDate) : offer.handOverDate;
I think it is better to remove this since we already know the cause of the failing tests. It is an hot fix, so we should only use it if it is becoming difficult to troubleshoot the root cause.

Also, this should be 
```suggestion
      typeof offer.handOverDate === 'string' ? parseISO(offer.handOverDate) : offer.handOverDate;
```

2021-02-19 06:19 UTC, andela-hpopoola requested changes
Thank you for working on this. I left a few comments but I am more concerned about ensuring that we return dates for the payment dates and not string. Thank you.

2021-02-19 06:19 UTC, andela-hpopoola commented on server/services/offer.service.js
> +  const paymentDates = [{ date: format(offer.handOverDate, 'yyyy-MM-dd'), amount: initialPayment }];
Can we make the date be in date format instead of a string to make date comparison easier in the future.

2021-02-19 06:19 UTC, andela-hpopoola commented on server/services/offer.service.js
> +      paymentDates.push({ date: paymentDate, amount: periodicPayment });
This didn't cater for when last payment is not equal to periodic payment.

2021-02-19 06:19 UTC, andela-hpopoola commented on test/services/offer.service.test.js
> +        expect(paymentDates[0].date).to.have.string('2020-12-11');
This would be better as dates not string.

2021-02-19 06:19 UTC, andela-hpopoola commented on test/services/offer.service.test.js
> +    const offer1 = OfferFactory.build(
Offer1, offer2, and offer3 are vague and don't really convene any meaning; Since these offers are used once in each test, it is better to define them in the context they are used to make the tests easier to read and update.

2021-02-19 06:19 UTC, andela-hpopoola commented on test/services/offer.service.test.js
> +    const demoUser = UserFactory.build({ role: USER_ROLE.USER }, { generateId: true });
I think you approached this like controllers tests.  This is not needed as it is not used in the service.

2021-02-19 06:19 UTC, andela-hpopoola commented on test/services/offer.service.test.js
> +    const property = PropertyFactory.build(
This is not needed too.

2021-02-19 06:19 UTC, andela-hpopoola commented on test/services/offer.service.test.js
> +    const enquiry = EnquiryFactory.build(
This is not needed too.

2021-02-19 06:19 UTC, andela-hpopoola commented on test/services/offer.service.test.js
> +        enquiryId: enquiry._id,
enquiryId and vendorId are not needed for this service too.

2021-02-19 06:19 UTC, andela-hpopoola commented on test/services/offer.service.test.js
> +    beforeEach(async () => {
I don't think this is needed too.

2021-02-19 06:19 UTC, andela-hpopoola commented on test/services/offer.service.test.js
> +      beforeEach(async () => {
This too is not necessary.

2021-02-19 06:19 UTC, andela-hpopoola commented on test/services/offer.service.test.js
> +        initialPayment: 95000,
Lets make this 75000, it will make you notice an important section not covered by the code.

2021-02-19 23:30 UTC, tobieeniafe commented on test/services/offer.service.test.js
> +    const enquiry = EnquiryFactory.build(
It's needed if we want the `addEnquiry` to work see `enquiry.service.js:19`

2021-02-19 23:31 UTC, tobieeniafe commented on test/services/offer.service.test.js
> +    const property = PropertyFactory.build(
It's needed if we want the `addEnquiry` to work see `enquiry.service.js:19`

2021-02-20 07:41 UTC, andela-hpopoola requested changes
Thank you for working on this. I left a few comments, this should be ready to go when you have fixed the comments.

2021-02-20 07:41 UTC, andela-hpopoola commented on test/services/offer.service.test.js
> +    beforeEach(async () => {
I still believe this can be removed (You might want to give a reason instead of resolving this without implementing it)

2021-02-20 07:41 UTC, andela-hpopoola commented on test/services/offer.service.test.js
> +      beforeEach(async () => {
This too ☝🏽

2021-02-20 07:41 UTC, andela-hpopoola commented on test/services/offer.service.test.js
>        beforeEach(async () => {
This too. This is a service with no database interaction.

2021-02-20 07:41 UTC, andela-hpopoola commented on test/services/offer.service.test.js
> +        expect(paymentDates[0].date).to.eql(new Date('2021-03-01T00:00:00.000Z'));
We are already parsing the Date, so it should be safe to pass in a human readable date. Let's update this in all instance 🙏🏽 

```suggestion
        expect(paymentDates[0].date).to.eql(new Date('2021-03-01'));
```

2021-02-21 06:22 UTC, andela-hpopoola approved these changes
Thank you for working on this. This looks good to me.

2021-02-21 18:28 UTC, merged