#176955705 add next payment schema
Highrachy/ballers-api pull request #128
Opened 2021-02-19 01:30 UTC by tobieeniafe

#### What does this PR do?
Add nextPayment schema

#### Description of Task to be completed?
Add nextPayment schema

#### How should this be manually tested?
NA

#### What are the relevant pivotal tracker stories?
#176955705

2021-02-19 06:26 UTC, andela-hpopoola requested changes
Thank you for working on this. The next step is to add next payment to the database when a user accepts an offer. Thank you.

2021-02-19 06:26 UTC, andela-hpopoola commented on server/models/nextPayment.model.js
> +      type: String,
Lets make this a boolean.

2021-02-19 06:26 UTC, andela-hpopoola commented on server/models/nextPayment.model.js
> +    status: {
We can also change this to resolved so that we can use a boolean here that defaults to false. Saves us the stress of importing the values of open and close each time.

2021-02-20 07:20 UTC, andela-hpopoola commented on server/models/nextPayment.model.js
> + *          resolved:
Let's make this come after propertyId to stick with the alphabetical order 😼

2021-02-21 06:25 UTC, andela-hpopoola commented
Thank you for making the changes.

>  The next step is to add next payment to the database when a user accepts an offer

Can we add step above ☝🏽  to this PR to increase our confidence that we are on the right track 🙏🏽

2021-02-22 07:20 UTC, andela-hpopoola requested changes
Thank you for working on this. I left a few comments but I am mostly concerned about testing that the `nextPayment` has been saved as expected and with the right values. I am currently not sure if it is better to test this via services or controller test (the choice is yours as long as your tests are optimal and tests for the required stuff)

2021-02-22 07:20 UTC, andela-hpopoola commented on server/services/offer.service.js
> +    responseDate: add(Date.now(), { days: 0 }),
Not sure if I am right here, but the initialPayment should be due on the day the offer letter expires. Maybe you need to ask Nnamdi to be 100% sure.

2021-02-22 07:20 UTC, andela-hpopoola commented on server/services/offer.service.js
> +          paymentSchedule,
I still feel we might not need to save the `paymentSchedule` since we can regenerate it from `generatePaymentSchedules` when needed. 

Do you have a good reason why you think it is better to save it?

2021-02-22 07:20 UTC, andela-hpopoola commented on server/services/offer.service.js
> +    await addNextPayment(nextPayment);
Can we  add tests to confirm this 🙏🏽

2021-02-22 14:37 UTC, tobieeniafe commented on server/services/offer.service.js
> +    responseDate,
The initial code was using the `handOverDate` to calculate the dates. But the current one uses the date the offer is accepted from, hence the `responseDate`. The `responseDate` was added here instead of spreading it in the `generatePaymentSchedules` method.

2021-02-22 15:09 UTC, tobieeniafe commented on server/services/offer.service.js
> +    responseDate: add(Date.now(), { days: 0 }),
Just spoke to Nnamdi, and the offer is supposed to contain an `initialPaymentDate` in the offer. Stating when the first payment is supposed to be made. Would make the appropriate changes to the model and tests.

2021-02-22 15:18 UTC, tobieeniafe commented on server/services/offer.service.js
> +    responseDate,
This has been resolved as Nnamdi explained that the calculation should use the `initialPaymentDate`

2021-02-22 17:08 UTC, tobieeniafe commented on server/services/offer.service.js
> +          paymentSchedule,
Wanted to be sure the right dates are generated. But found a way around it without saving it

2021-02-22 17:51 UTC, andela-hpopoola approved these changes
Thank you for working on this. This looks good to me for now. Feel free to merge when ready. 

Here are the remaining stories in my opinion.
1. Handle the events when a user's payment has been confirmed. Not sure we have everything needed for this but after a user makes any payment and the payment has been approved, we should generate the next payment. Past payments should be taken into consideration when generating a new NextPayment as we don't want to overgenerate or under generate the next payment.
2. After the above story, the next story is to handle any expired next payment. When this endpoint is accessed it takes the next expired next payment in the nextPayment model, related necessary information is also retrieved to generates a new NextPayment.

3. Create an endpoint to send reminders. Let's stick with 60 days, 30days, 14days, 7days, 1 day for now. This will send a mail reminder while we integrate the SMS reminder later in the future.

Thank you.

2021-02-22 18:38 UTC, merged