#176955814 make provisions for multiple floor plans
Highrachy/ballers-api pull request #129
Opened 2021-02-20 02:04 UTC by tobieeniafe

#### What does this PR do?
Make provisions for multiple floor plans

#### Description of Task to be completed?
Make provisions for multiple floor plans

#### How should this be manually tested?
`POST /api/v1/property/add`
`PUT /api/v1/property/update`

#### What are the relevant pivotal tracker stories?
#176955814

2021-02-20 06:59 UTC, andela-hpopoola requested changes
Thank you for working on this. However, I think we can improve your current implementation to make it an optimal solution. 

The problem here is how a user would easily delete or update a floor plan (I thought I explained this when I compared it to the gallery implementation). Most times when we are dealing with array, we should always keep in mind how the user would update or remove an entry from the array.

The floorplan model should look like this imho:

```js
floorPlans: {
[ {name: String, plan: String} ]
}
```
I believe it would be more manageable if we have a different endpoint to add, update and remove a floor plan. Unfortunately, this implementation doesn't cater for this.

2021-02-20 07:14 UTC, andela-hpopoola commented
To fix this, lets create endpoints for the floorplans to cater for these implementation:

```
POST /property/:id/floorplan
PUT /property/:id/floorplan
DELETE /property/:id/floorplan
```

The best part is that we would use the same implementation for gallery.

2021-02-20 14:06 UTC, tobieeniafe commented
> To fix this, lets create endpoints for the floorplans to cater for these implementation:
> 
> ```
> POST /property/:id/floorplan
> PUT /property/:id/floorplan
> DELETE /property/:id/floorplan
> ```
> 
> The best part is that we would use the same implementation for gallery.

The floorPlan can be updated directly from the update property route. Is there a need to create a route solely just for this purpose?

2021-02-21 06:40 UTC, andela-hpopoola commented
> The floorPlan can be updated directly from the update property route. Is there a need to create a route solely just for this purpose?

Yes, please. Updating the floor plan with the generic update property route doesn't cater to the necessary checks when updating floor plans and this is prone to multiple errors since this will have to be handled by the agent that is accessing the endpoint. The test you added caters for total replacement, not actual updates 😏 

Also, the additional endpoint saves time and makes it easier to work with floor plans without the complexities of properties themselves. To update or delete a floorplan, it is easier to send the information of the floor plan you wish to change with the id of the floor plan instead of sending the whole floor plans 🤷🏽‍♂️ 

Lastly, the implementation shouldn't be time-consuming as we have similar implementations for directors in user models.

Thank you.

2021-02-25 05:52 UTC, andela-hpopoola approved these changes
Thank you for working on this. My only comment is ensuring we send the data directly instead of enclosing them in the `floorPlan` object. Feel free to merge after resolving this.

2021-02-25 05:52 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +    const data = {
Since we are working with the floor plan endpoint, I think it is better to just send the properties without the additional floor plan.

```js
const data = {
    name: 'Second Floor',
    plan: 'https://ballers.ng/secondfloor.png',
}
```
```

2021-02-25 05:52 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +      floorPlan: {
Same comment here to make it easier to manage.

```js
const data = {
    name: 'Bottom Floor',
    plan: 'https://ballers.ng/bottomfloor.png'
    floorPlanId: property.floorPlans[1]._id
}
```

2021-02-25 09:55 UTC, merged