#176955779 update neighborhood for properties
Highrachy/ballers-api pull request #130
Opened 2021-02-21 00:11 UTC by tobieeniafe

#### What does this PR do?
Update neighborhood for properties

#### Description of Task to be completed?
Update neighborhood for properties

#### How should this be manually tested?
`POST /api/v1/property/add`

#### What are the relevant pivotal tracker stories?
#176955779

2021-02-21 07:10 UTC, andela-hpopoola requested changes
Thank you for working on this. I know we can use the `update property` route to manipulate the neighborhood object but it cannot be easily manipulated as you have portrayed it in the tests. 

For the neighbourhood, we would also need the CRUD endpoints to handle. Trying to update this from the property update route is too complicated and would be prone to error (it is also difficult to test).

In the frontend (or anywhere the endpoint is consumed), we would want a user to click on an `x` icon to cater for deleting a neighborhood entry, sending the whole neighbourhood object back is not an ideal solution. Also adding a new neighbourhood entry is easier without sending the whole object to the `property update` endpoint. 


Let's create individual endpoints to cater for this please:

```
POST /property/:id/neighborhood - the agent consuming the endpoint will need to specify the type of neighborhood they wish to add out of the 6 defined categories
PUT /property/:id/neighborhood - neighbourhood type and and actual id is needed here to know the right property we are updating
DELETE /property/:id/neighborhood - same as above
```

Thank you.

2021-02-21 07:10 UTC, andela-hpopoola commented on test/helpers.js
> +  // expect(response.neighborhood).to.be.eql(property.neighborhood);
If this is problematic here, we can remove it and write the necessary tests for confirming that the neighbourhood actions are done in the right way.

2021-02-23 06:03 UTC, andela-hpopoola requested changes
Thank you for working on this. I left a few comments on consistency and best practices. Thank you.

2021-02-23 06:03 UTC, andela-hpopoola commented on server/controllers/property.controllers.js
> +  updateNeighborhood(req, res, next) {
Also, can we add functionality to add a new entry and delete an existing entry and add tests for them too?

2021-02-24 05:49 UTC, andela-hpopoola approved these changes
Thank you for working on this. This looks good to me and should be safe to merge when you fix the comments. Thank you and Nice work.

2021-02-24 05:49 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +            longitude: 123.22,
Let's use different longitude and latitude for each items here 🙏🏽

2021-02-24 05:49 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +          schools: [
It would have been more preferable to add 2 types here. Maybe schools and shoppingMalls.

2021-02-24 05:49 UTC, andela-hpopoola commented on server/services/property.service.js
> +  let neighborhood = property.neighborhood[neighborhoodInfo.type];
I noticed you are always removing a delete entry yourself by using filters, do you have any important reasons for doing this.  

I think it is safe to remove this and use `pull` to remove the entry from the database:

https://docs.mongodb.com/manual/reference/operator/update/pull/

2021-02-24 05:49 UTC, andela-hpopoola commented on server/services/property.service.js
> +      { $set: { [`neighborhood.${neighborhoodInfo.type}`]: neighborhood } },
```suggestion
 { $pull: { [`neighborhood.${neighborhoodInfo.type}`]: { _id: neighborhoodInfo.typeId } } },
```

2021-02-24 05:49 UTC, andela-hpopoola commented on server/schemas/property.schema.js
> +  neighborhood: neighborhoodInfo,
I think the endpoint should be used to add one neighborhood at a time (like the updateSchema below). The purpose of this endpoint is to do a one-off simple transaction not multiple.

2021-02-24 08:47 UTC, tobieeniafe commented on server/schemas/property.schema.js
> +  neighborhood: neighborhoodInfo,
That was initially the idea. But a situation where the vendor decides to add multiple neighborhoods, this reduces the number of requests to be made. As one neighborhood can also be added through this same endpoint.

2021-02-24 10:00 UTC, merged