#176955812 admin to flag property
Highrachy/ballers-api pull request #135
Opened 2021-03-15 20:35 UTC by tobieeniafe

#### What does this PR do?
Add route to allow admin flag a reported or suspicious property

#### Description of Task to be completed?
Add route to allow admin flag a reported or suspicious property

#### How should this be manually tested?
`POST /api/v1/property/flag`

#### What are the relevant pivotal tracker stories?
#176955812

2021-03-16 05:43 UTC, andela-hpopoola requested changes
Thank you for working on this. 

However, the purpose of flagging is to stop people from seeing the property (either via search or recommendations) because there is an issue that needs to be resolved with the property. 

To ensure that this works as expected, flagged should support many cases (please take note of each sentence below and you can create them as multiple PRs if you wish)
  - someone complained the property doesn't align with the image uploaded (reason) 
  - when the admin sees this, he flags the property, vendor receives a mail
  -  vendor updates the image and request that admin should unflag
  - when user searches for property, the flagged property is not found
  - admin sees that vendor has made the correction and unflag property (the previous reason why the property was flagged is still saved in the database, the new reason is also saved)
  - user searches for property, user can now see property as it is unflagged
  - user noticed that the number of bedrooms is wrong and reports property again
  -  admin flags again (he can see that the property has been previously flagged and other info) 
  - vendor receives mail again, user cannot see flagged property, vendor fixes, admin unflag ... 
  - the cycle continues

I hope you get the gist. Thank you.

2021-03-16 05:43 UTC, andela-hpopoola commented on server/models/property.model.js
> +    flagged: {
Can we use the same schema pattern used for `banned` users

https://github.com/Highrachy/ballers-api/blob/473f54577d072df37324429a6d9291bf12a53463/server/models/user.model.js#L101-L113

2021-03-16 05:43 UTC, andela-hpopoola commented on server/routes/property.routes.js
> +router.post(
We would also need another endpoint to unflag

2021-03-16 05:43 UTC, andela-hpopoola commented on server/schemas/property.schema.js
> +  reportId: requiredObjectId('Report id'),
I believe `ReportId` should be optional. A property can be flag even without a report. Not sure if the `notes` should be compulsory so that we would know the exact reason why the admin has flagged the property.

2021-03-16 05:43 UTC, andela-hpopoola commented on server/models/property.model.js
> +    flagged: {
Don't forget to also add `flagged.status` to property filter to ensure that all flagged properties can be gotten with no issues.

Also, we need to return all flagged information for a property, don't forget to add tests to ensure that it is returned when a we get a property.

2021-03-20 06:41 UTC, andela-hpopoola approved these changes
Thank you for helping out with this. I have approved this PR but left a few comments that need to be resolved.

PS: I might miss a few things as I am not 100% back, please bear with me if I point out things here in the future that needs to be resolved.

Overall, this is a great code and you covered all the bases. Thank you.

2021-03-20 06:41 UTC, andela-hpopoola commented on server/services/property.service.js
> +      notes: propertyInfo.notes || propertyInfo.reason,
It seems like you resolved `reason` and `notes` to notes here. It doesn't feel right, as `property.notes` will be used instead of reason if notes is available in the request. The confusing stuff is that `property.notes` is optional and shouldn't override `property.reason` which is compulsory.

If we want to use `reason` and `notes`, let us resolve them separately as they are different entities else lets stick with `property.reason` alone and remove `propertyInfo.notes`.

2021-03-20 06:41 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +    context('with a valid token & id', () => {
Can we also add a test to confirm that the report Id is resolved when a property is flagged?

2021-03-20 06:41 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +      context('when reportId is empty', () => {
Can we also add tests to confirm that if the reportId is missing the property is flagged appropriately?

2021-03-20 11:40 UTC, tobieeniafe commented on test/controllers/property.controller.test.js
> +    context('with a valid token & id', () => {
Already done `property.service.test.js` line `220`

2021-03-20 12:07 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +    context('with a valid token & id', () => {
No wahala. That fixes this comment.

2021-03-20 12:41 UTC, tobieeniafe commented on server/services/property.service.js
> +      notes: propertyInfo.notes || propertyInfo.reason,
In this case, it's for resolving the report made. So where there isn't a note specifically for why the report was resolved, we'd use the reason for flagging the property.

2021-03-20 13:02 UTC, merged