#176955705 get all next payment dates for user and vendor
Highrachy/ballers-api pull request #136
Opened 2021-03-20 02:47 UTC by tobieeniafe

#### What does this PR do?
Get all next payment dates for user and vendor

#### Description of Task to be completed?
Get all next payment dates for user and vendor

#### How should this be manually tested?
`GET /api/v1/user/next-payments`

#### What are the relevant pivotal tracker stories?
#176955705

2021-03-20 06:56 UTC, andela-hpopoola requested changes
Thank you for working on this. The implementation is still in progress so I left a few comments to unblock you. I hope that helps, please let me know if you need more help so that we can proceed a little bit faster. Thank you.

2021-03-20 06:56 UTC, andela-hpopoola commented on server/services/nextPayment.service.js
> +  if (totalPaid > offer.totalAmountPayable) {
Not sure why you changed this here when we have tests to cater for this? If it is important you change it, please add tests to catch why we missed the bug.

2021-03-20 06:56 UTC, andela-hpopoola commented on server/services/user.service.js
> +  const activeOffers = await getActiveOffers(user._id).catch((error) => {
Nice concept here but I feel this is a wrong approach to get next payments.

We have the next payments table in the database and this is based on active offers; a user cannot have a next payment record unless they have a transaction/ active offer, they cannot make a transaction unless they have an active offer, so it is safe to assume that next payment would only be generated for active offers.

This is how I will implement mine:

1. For users: Get all next payments in  with the userId that has not been resolved (`resolved is false`) and aggregate it to get the offer details, property details and other necessary information
2. For vendors: Get all next payments in  with the vendorId that has not been resolved (`resolved is false`) and aggregate it to get the offer details, property details and other necessary information
3. For admins: Get all next payments that has `resolved is false`.

Pagination, filters and others can then be included when I have implemented the above functionality.

I hope this helps.

2021-03-22 00:01 UTC, tobieeniafe commented on server/services/nextPayment.service.js
> +  if (totalPaid > offer.totalAmountPayable) {
This was done in error. The reason the tests are failing. Thanks for pointing it out.

2021-03-23 05:28 UTC, andela-hpopoola requested changes
Thank you for working on this, this looks almost done. I left a few comments on ensuring that an admin can also get the next payments (as discussed in our call) and adding appropriate tests to ensure that the right values are returned. Thank you.

2021-03-23 05:28 UTC, andela-hpopoola commented on server/services/nextPayment.service.js
> +    { $match: { [accountType.matchKey]: ObjectId(user._id) } },
We want the admin to get the next payments too, can we update this to accommodate an admin too. Admins should get all unresolved next payments (it is better to add it now than later).

2021-03-23 05:28 UTC, andela-hpopoola commented on server/routes/user.routes.js
> +router.get('/next-payments', authenticate, isUserOrVendor, UserController.getNextPayments);
This should be under nextpayments route `/all` as we have always done for others 😏

2021-03-23 05:28 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +      const inValidNextPayments = NextPaymentFactory.buildList(3, {
These are not invalid, rather they are `resolved`

2021-03-23 05:28 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +    describe('Get All Next Payments', () => {
Test should be in nextPayments controller

2021-03-23 05:28 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +
I have always mentioned that the pagination test does not cover testing that the right things are returned. Can you please keep this in mind to prevent mentioning this over and over again? 

We need to test that the offer information, user information (for both user and vendor), and the right property information are returned.

2021-03-23 20:16 UTC, andela-hpopoola approved these changes
Thank you for working on this. I left a few comments but overall this looks good to me. Thank you for helping with this. Feel free to merge after fixing the comments.

2021-03-23 20:16 UTC, andela-hpopoola commented on server/routes/index.js
> +  app.use('/api/v1/next-payments', nextPayment);
I noticed that we used singular naming for all routes here. Can we do the same for next payments too 🙏🏽 

```suggestion
  app.use('/api/v1/next-payment', nextPayment);
```

2021-03-23 20:16 UTC, andela-hpopoola commented on server/services/nextPayment.service.js
> +  if (user.role === USER_ROLE.VENDOR || user.role === USER_ROLE.ADMIN) {
I believe we can simplify this by making the `user.role` decision come first and use an else statement for this:

```js
if (user.role === USER_ROLE.USER) {
...
} else { // this caters for vendor and admin 
...
}

```

2021-03-23 21:59 UTC, merged