#177431730 return next payment when viewing portfolio
Highrachy/ballers-api pull request #138
Opened 2021-03-24 23:44 UTC by tobieeniafe

#### What does this PR do?
Return next payment when viewing portfolio

#### Description of Task to be completed?
Return next payment when viewing portfolio

#### How should this be manually tested?
`GET /api/v1/property/:id`

#### What are the relevant pivotal tracker stories?
#177431730

2021-03-25 07:22 UTC, andela-hpopoola requested changes
Thank you for working on this. I left a few comments on ensuring that we have a different endpoint for viewing a portfolio so that we can make the matches via the offerId.

2021-03-25 07:22 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +              expect(res.body.property.nextPaymentsInfo[0].userId).to.be.eql(
![Group 882](https://user-images.githubusercontent.com/26963369/112431812-4893c800-8d40-11eb-8a2f-f31292491e7f.png)

From the mockup, we would need to return everything needed to build this component. The most important stuff is:

1. Next Payment Expected Amount - from `NextPayment` model
2. Due Date of Next Payment - from `NextPayment` model
3. Equity Amount - from `offer` model
4. Amount Contributed - From `transaction` model

2021-03-25 07:22 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +            .get(`/api/v1/property/${property._id}`)
We have already discussed this that this endpoint is not visible for owned portfolio and that we would need a different endpoint based on offerId for users with multiple properties. 

Can you create a different endpoint (a new service might be needed) and test that important information is returned in this endpoint (something like visitation schedule is not needed).

2021-03-25 07:22 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +    context('when next payment exists', () => {
We should also add a test to check what is returned if a user has completed his payment. In this case, there should be no next payment returned but `Equity Amount` and `Amount Contributed` should still be returned.

2021-03-25 07:22 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +      context('when request is sent by admin', () => {
Since the endpoint is based on a portfolio, I believe an admin should be able to view the next payment (might be necessary for support if a customer writes in to complain).

2021-03-25 07:22 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +              expect(res.body.property.nextPaymentsInfo.length).to.be.eql(2);
Since this is now based on the offerId, I believe a vendor, user, and admin should see the same information regarding nextPayments. We only need to confirm that the vendor and user are the owner/custodian of the offerId before they can view it.

2021-03-25 07:22 UTC, andela-hpopoola commented on server/services/property.service.js
> +                  { $eq: ['$propertyId', '$$propPropertyId'] },
When writing the new service, we might need to use the `offerId` to match here. This will enable us to use the same condition for the user, admin, and vendor.

2021-03-26 05:33 UTC, andela-hpopoola requested changes
Thank you for making the updates. On a closer look, I discovered that we had similar endpoints, can we ensure we properly deprecate these endpoints and upgrade/reuse some of the services used there. Here are the endpoints:

https://github.com/Highrachy/ballers-api/blob/c86a20bd4dd17b691b2390304fc54c4ca4a4cfc3/server/routes/property.routes.js#L254

https://github.com/Highrachy/ballers-api/blob/c86a20bd4dd17b691b2390304fc54c4ca4a4cfc3/server/routes/property.routes.js#L228

If we are using `property/portfolio/:id` then it makes complete sense to update `property/assigned` to `property/portfolio/all` to cater for all assigned properties in the admin, vendor and user point of view.

I hope this helps. Thank you and Nice work.

2021-03-26 05:33 UTC, andela-hpopoola commented on server/services/property.service.js
> +    return [];
Hmmm, I believe it is better to return 'Not Found' when the portfolio is not found and also return an error if the portfolio is viewed by a wrong user or a wrong vendor. 

I don't see a use case where it is better to return an [] since we are trying to retrieve a single portfolio 🤷🏽‍♂️

2021-03-26 05:33 UTC, andela-hpopoola commented on server/services/property.service.js
> +    // {
If this would be difficult to get, we can get the transaction sum with another query. 

I believe it might be possible to get it here using the last example here but if it is too tricky, it might be better to retrieve the sum separately.

2021-03-26 16:32 UTC, tobieeniafe commented on server/services/property.service.js
> +    return [];
This is handled in the controller `property.controller.js` line `277`

2021-03-28 06:21 UTC, andela-hpopoola requested changes
Thank you for working on this. I left more comments on ensuring we get this right. If this is getting more complex than expected, feel free to break it down into multiple PRs but please let me know the ones you are skipping in this PR so that I don't expect them.

2021-03-28 06:21 UTC, andela-hpopoola commented on server/routes/property.routes.js
> +  isUserOrVendor,
I think this endpoint should also support an `Admin` since it is the only way an Admin can have access to any assigned property in a portfolio.

2021-03-28 06:21 UTC, andela-hpopoola commented on server/services/property.service.js
> +export const getAssignedProperties = async (user) => {
When getting assigned properties, we would also want to paginate, filter and sort them. Maybe in another PR 🤷🏽‍♂️

2021-03-28 06:21 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +      beforeEach(async () => {
Can you write the reason why we are faking the date in the context so that we would understand it in the future.

I understand that this is needed for `nextPayment` so it makes more sense to explain (via description in context) the reason we are faking date. For instance, on line 2391, I understand that the tests is checking when the user has completed his payment, but here, it is difficult to understand if the payment is made on the first cycle, last cycle or you had other idea in mind.

2021-03-28 06:21 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +              expect(res.body.portfolio.outstandingBalance).to.be.eql(
This is not needed in the backend. Even though it might look harmless to add them, the reason why are removing them is to 
* reduce the payload we are sending for the request
* we have already sent all the needed information to generate it so it is useless to calculate it from the endpoint
* it doesn't make sense trying too hard to conform with the frontend as the frontend is not a fixed design and would change without notice. The only thing we should care about is sending the right information from the endpoint which has been done

2021-03-28 06:21 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +    context('without wrong vendor token', () => {
We should also test for a wrong user.  A loop can be used for the two tests.

2021-03-29 07:55 UTC, andela-hpopoola requested changes
Thank you for making the updates. Code looks good for now, I will review it again when you have written the tests for the new changes and fixed other pending comments. Thank you.

2021-03-29 07:55 UTC, andela-hpopoola commented on server/controllers/property.controllers.js
> +  getPortfolio(req, res, next) {
Lets make this `getOnePortfolio` so that it can be more descriptive. Same thing with the service name below on line 255,

```suggestion
  getOnePortfolio(req, res, next) {
```

2021-03-30 05:59 UTC, andela-hpopoola requested changes
Thank you for helping out with this. I believe this is almost completed, I left a few comments just to be sure we are not missing anything and to fix a few nits. Thank you.

2021-03-30 05:59 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +    context('without wrong token without access', () => {
Not sure of this your statement means, can you try to rewrite in a more readable format.

```suggestion
    context('with a different user', () => {
```

2021-03-30 05:59 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +        it('returns portfolio', (done) => {
```suggestion
        it('doesn't return the portfolio', (done) => {
```

2021-03-30 05:59 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
>                expect(res.body.portfolio.amountContributed).to.be.eql(
We need a test here to ensure that the right `totalAmountPayable` is returned. We removed `equityAmount` because it is already returned in the offer, however, we need to write a test to ensure that this is truly available in the offer.

2021-03-30 05:59 UTC, andela-hpopoola commented on server/controllers/property.controllers.js
>    getAssignedProperties,
Lets update this to `getAllPortfolios` so that we can always relate it with `getOnePortfolio` in the future.

2021-03-30 05:59 UTC, andela-hpopoola commented on server/services/property.service.js
> +  const filterQuery = buildFilterQuery(OFFER_FILTERS, query);
We might need to create a PORTFOLIO_FILTERS in the future but I think this works for now.

2021-03-30 05:59 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> -    context('when no transaction has been made', () => {
Can we also add a test to check that the right values are returned when no transaction has been made.

2021-03-30 05:59 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
Can we update the description here to reflect that we are getting all portfolios. Please update it to `Get All Portfolios`.

https://github.com/Highrachy/ballers-api/blob/82a918d4dd3e2961d3765f2104e05696f5eae5d6/test/controllers/property.controller.test.js#L2488

2021-03-30 05:59 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
Also, it looks like pagination tests are missing here. Can you please add the generic pagination tests just to be safe that it works when we have more than the limit?

2021-03-30 05:59 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +  describe('View User Portfolio', () => {
```suggestion
  describe('Get One Portfolio', () => {
```

2021-03-31 01:40 UTC, tobieeniafe commented on test/controllers/property.controller.test.js
Currently working on this, looking for the best way to generate them with the `OFFER_STATUS`

2021-03-31 05:29 UTC, andela-hpopoola approved these changes
Thank you for working on this. Apart from the skipped test, this looks good to go. Feel free to merge 👍🏽

2021-03-31 05:29 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +    context.skip('when no payment has been made', () => {
I believe this is related to the pending next payments fix 😼

2021-03-31 09:48 UTC, tobieeniafe commented on test/controllers/property.controller.test.js
> +    context.skip('when no payment has been made', () => {
Haha yes, it 😅. It's in the second cycle and no payment has been made, so we expect the date to be the expiry of the first cycle, but the sum of both expected payments.

2021-03-31 18:52 UTC, merged