[#177431810, #177431798] offline payment confirmation
Highrachy/ballers-api pull request #141
Opened 2021-04-01 00:37 UTC by tobieeniafe

#### What does this PR do?
Add routes to add, resolve and get all offline payments

#### Description of Task to be completed?
Add routes to add, resolve and get all offline payments

#### How should this be manually tested?
`POST /api/v1/offline-payment/add`
`PUT /api/v1/offline-payment/resolve/:id`
`GET /api/v1/offline-payment/all`

#### What are the relevant pivotal tracker stories?
[#177431810, #177431798]

2021-04-01 06:02 UTC, andela-hpopoola requested changes
Thank you for working on this. This is a good start for offline payments. Nice work.

Next time, can you try to resist the urge of merging 2 stories together in 1 PR. I have explained that the purpose of a pull request is to update a reasonable chunk of the code. If the updates made are too much, it will make it more difficult to review and catch probably future bugs. 

The additional time in adding the code to this PR can be spent on completing the tests. If you have more additional time after completing this, then you can create the commit of the new story from this commit. That is, you will create the new branch from the old one (you have spent over 1 year working on Git, so I expect you to understand how to do all of this with no hassle).

You can merge stories in the future (even though it is not best practices), but this should be for tiny changes (like changing 2 lines of code, typo fixes, or minor nit fixes).

Can you remove the `admin resolve` code in your commit (no worries, you can still copy them from the first commit here on GitHub) so that we can focus more on getting the offline payments model right without getting confused with too much code? Also, don't forget to update the PR title to reflect the right Pivotal Tracker story id. Thank you.

2021-04-01 12:43 UTC, tobieeniafe commented on server/services/offlinePayment.service.js
> +// eslint-disable-next-line import/no-cycle
The error `dependency cycle detected` usually comes up when a file within the same directory is imported into the services folder.

2021-04-04 19:12 UTC, andela-hpopoola requested changes
Thank you for working on this. Can you try to wrap this up and get them merged asap before the next sprint planning (with the other related PR after splitting)? Thank you.

2021-04-04 19:12 UTC, andela-hpopoola commented on server/models/offlinePayment.model.js
> +    comments: [
This is missing from the swagger docs above

2021-04-04 19:12 UTC, andela-hpopoola commented on server/routes/offlinePayment.routes.js
> +router.get('/all', authenticate, isAdmin, OfflinePaymentController.getAll);
This should be available for a user too. A user should be able to view all the offline payments he has filled, this is the only way they can edit it.

2021-04-06 17:26 UTC, andela-hpopoola requested changes
Thank you for working on this. I left a few comments, but we should be almost ready to merge this when you fix them. Thank you.

2021-04-06 17:26 UTC, andela-hpopoola commented on server/schemas/offlinePayment.schema.js
> +  amount: requiredNumber('Amount'),
Is there any reason why we are making these entries required? I thought we agreed that they would be required when adding but optional when updating if they are not stated. Please see the implementation of other schemas for more information.

2021-04-06 17:26 UTC, andela-hpopoola commented on server/services/offlinePayment.service.js
> +// eslint-disable-next-line import/no-cycle
No, I think I will disagree with you here. I believe this error will only come up if you import `offer.service` in `offlinePayment.service` and you import `offlinePayment.service` too in `offer.service`.

Since you didn't import `offlinePayment.service` in the `offer.service` file, I believe there should be no error. 

Let me know if otherwise is the case.

2021-04-06 17:26 UTC, andela-hpopoola commented on server/services/offlinePayment.service.js
> +    return await new OfflinePayment({ ...offlinePayment, userId: offer.userId }).save();
Can you import the user information here and use the userId here instead of using the id from offer.userId. 

I understand that this might look like the same thing, but getting the userId from where the service is used gives 100% assurance that we are using the Id of the user calling the service not the one that ones the offer. 

We are talking about money here, so we should be extra careful with security 😼 .

2021-04-06 17:26 UTC, andela-hpopoola commented on server/services/offlinePayment.service.js
> +export const getAllOfflinePayments = async (user, { page = 1, limit = 10 }) => {
We might want to also add filters and sort here too.

2021-04-06 17:26 UTC, andela-hpopoola commented on test/controllers/offlinePayment.controller.test.js
> +      context('when no offers exists in db', () => {
```suggestion
      context('when no offline payments exists in db', () => {
```

2021-04-06 17:26 UTC, andela-hpopoola commented on test/controllers/offlinePayment.controller.test.js
> +    describe('when payments exist in db', () => {
```suggestion
    describe('when offline payments exist in db', () => {
```

2021-04-07 05:14 UTC, andela-hpopoola approved these changes
Thank you for working on this. This looks good to me. Feel free to merge 👍🏽

2021-04-07 09:51 UTC, merged