#177638827 update `/property/search` endpoint to use filters and sorting
Highrachy/ballers-api pull request #149
Opened 2021-04-09 01:12 UTC by tobieeniafe

#### What does this PR do?
Update `/property/search` endpoint to use filters and sorting

#### Description of Task to be completed?
Update `/property/search` endpoint to use filters and sorting

#### How should this be manually tested?
`GET /api/v1/property/search`

#### What are the relevant pivotal tracker stories?
#177638827

2021-04-09 05:43 UTC, andela-hpopoola requested changes
Thank you for working on this. The initial startup looks good to me, but I am more interested in the tests. We would need to be more comprehensive with our tests here because this is a very important part of the application. You would need to add tests for these sections and ensure they are comprehensive (combine them with existing sections)

1. Searched Properties - Ensure that the right property is returned with different search terms. This should also include ranged tests like price greater than/ less than a specific value.
2. Pagination - Normal pagination helper class should be enough here
3. Sorting: Ensure that most of the entries work as expected when sorted
4. Filters: Ensure that property can be filtered

2021-04-10 21:02 UTC, andela-hpopoola requested changes
Thank you for working on this. This looks good and the tests looks great too 👍🏽 .

However, can we add the following tests too:

1. Tests to ensure that sorting works as expected for a searched property. At least, try sorting by createdAt (necessary to sort old and newly added property), price (this is the man of the match), and maybe state.
2. Tests to ensure that searching, filtering, and sorting work together with a single request. That is, the test should search for a property, add filters, and sort parameters to confirm that this would work too.
3. Try testing for ranges too for numeric values like price, bathroom, bedrooms, toilets. At least, add a test to confirm that a user can search for houses from the range of 30 million to 50 million to confirm that this works as expected.

Thank you for the hard work.

2021-04-12 00:03 UTC, tobieeniafe commented on test/controllers/property.controller.test.js
> +            endpoint,
This break the function tests, such that we'd have queries like `/api/v1/property/search?country=a?limit=1`

2021-04-12 16:14 UTC, andela-hpopoola requested changes
Thank you for working on this. This looks good to me. I dropped a few comments (mostly nits on using a better test description). The pending stuff is adding filtering by VendorId with test. After that, we are good to go 💯 .

2021-04-12 23:21 UTC, tobieeniafe commented on server/helpers/filters.js
> +  units: { type: FILTER_TYPE.INTEGER },
No, not yet. The only feasible solution I could come up with is, editing the property model and adding the vendor's name as a field.

2021-04-13 05:23 UTC, andela-hpopoola commented on server/helpers/filters.js
> +  units: { type: FILTER_TYPE.INTEGER },
Not totally sure what you mean by this, We already have the vendorId, please let's use that. I was speaking from the frontend angle (apologies), I should have been more explicit to say that we should allow a user to search by `vendorId `(which is addedBy in the property model)

2021-04-13 05:24 UTC, andela-hpopoola requested changes
Thank you for making the changes. Still waiting for you to add the `vendorId` stuff (with tests)  as commented here https://github.com/Highrachy/ballers-api/pull/149#discussion_r612137831 and fix failing tests (I didn't look at why it is failing though) so that I can approve.

2021-04-13 16:09 UTC, andela-hpopoola approved these changes
Thank you for working on this. This looks good to me. I left a single non-blocking comment otherwise, this is ready to be merged 💯

2021-04-13 16:09 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +              vendor: invalidVendorUser,
I think the best thing is to use a vendor's Id here, maybe a new vendor's Id. Using an `invalidVendorUser` here makes it seem like we can create vendor with invalid vendors 🤷🏽‍♂️

2021-04-13 21:51 UTC, merged