#177755633 make expiry date close end of day
Highrachy/ballers-api pull request #159
Opened 2021-04-20 13:00 UTC by tobieeniafe

#### What does this PR do?
Make expiry date close end of day

#### Description of Task to be completed?
Make expiry date close end of day

#### How should this be manually tested?
`POST /api/v1/offer/create`
`PUT /api/v1/offer/reactivate`

#### What are the relevant pivotal tracker stories?
#177755633

2021-04-20 16:41 UTC, andela-hpopoola requested changes
Thank you for working on this. Once you have fixed the tests, can you update the following fields too in this models to use endOfDay:

- offer.model.js - `initialPaymentDate` (you fixed `expires` in this PR)
- enquiry.model.js - `investmentStartDate`
- nextPayment.model.js - `expiresOn`

Thank you.

2021-04-20 16:41 UTC, andela-hpopoola commented on test/controllers/offer.controller.test.js
> +              expect(res.body.offer.expires).to.have.string('22:59:59.999');
Not currently sure if the converted date format (expires) is the issue but the end of the day should be `23:59:59.999` since we have 24 hours. 

Likely issue is that `expires` is supposed to be in GMT+1 format to correspond with our own date.

https://date-fns.org/v2.21.1/docs/endOfDay
```suggestion
              expect(res.body.offer.expires).to.have.string('23:59:59.999');
```

2021-04-20 16:41 UTC, andela-hpopoola commented on test/controllers/offer.controller.test.js
> +    describe('Reactivate Expired Offer', () => {
Not sure why we had so much tests for `Reactivated Expired Offer` 🤷🏽‍♂️

2021-04-21 01:29 UTC, tobieeniafe commented on test/controllers/offer.controller.test.js
> +              expect(res.body.offer.expires).to.have.string('22:59:59.999');
This is actually correct but in a tricky way. The expiry date is set with respect to the user's timezone. So the issue with this is, the server's clock is at GMT and the machine is at GMT+1. So the date returned is correct (for the server) with respect to the user's clock.

2021-04-21 01:39 UTC, tobieeniafe commented
> Thank you for working on this. Once you have fixed the tests, can you update the following fields too in this models to use endOfDay:
> 
> * offer.model.js - `initialPaymentDate` (you fixed `expires` in this PR)
> * enquiry.model.js - `investmentStartDate`
> * nextPayment.model.js - `expiresOn`
> 
> Thank you.

I don't think  `enquiry.model.js` - `investmentStartDate` should be here

2021-04-21 07:22 UTC, andela-hpopoola commented on test/controllers/offer.controller.test.js
> +              expect(res.body.offer.expires).to.have.string('22:59:59.999');
>  the server's clock is at GMT and the machine is at GMT+1

I am sorry, I have to disagree with this ☝🏽 as the test is run on Travis CI which I believe serves as the server and machine (or whatever you mean by this). 

The returned end-of-day time in the test is `22:59:59.999`, the response doesn't have any reference to the GMT or GMT+1, so I believe this is wrong. Even if it will return `22:59:59.999`, then the GMT should be specified else the time should be in GMT+1 to ensure consistency when it is being viewed from different parts of the world.

2021-04-21 07:37 UTC, andela-hpopoola reviewed
Thank you for working on this. 

> I don't think enquiry.model.js - investmentStartDate should be here

I added `investmentStartDate` to make it consistent with `initialPaymentDate` since the `investmentStartDate` is used to generate the `initialPaymentDate`.

2021-04-21 07:37 UTC, andela-hpopoola commented on package.json
> +    "date-fns-tz": "^1.1.4",
Where is this used 🤷🏽‍♂️ ?

2021-04-21 17:46 UTC, tobieeniafe commented on package.json
> +    "date-fns-tz": "^1.1.4",
I added it to try to manipulate the timezones, but it didn't work out. Forgot to remove it. My bad 🤦🏾‍♂️

2021-06-14 06:28 UTC, andela-hpopoola commented
@tobieeniafe I have created a few hotfixes for the dates and I think they are manageable for now. I have 1 pending edge case:
- the current end of the day uses the server's the end of day and not for Nigeria

However, every other thing relating to the date issues we had looks and works as expected. I will keep on testing it to be able to unravel more edge cases.

This works for all timezones for now and I think it is safe to merge. Thank you.

2021-06-14 06:29 UTC, merged