#177810751 create notification for users
Highrachy/ballers-api pull request #160
Opened 2021-04-22 00:48 UTC by tobieeniafe

#### What does this PR do?
1. Add service to generate notifications.
2. Create route to mark a notification as read

#### Description of Task to be completed?
1. Add service to generate notifications.
2. Create route to mark a notification as read

#### How should this be manually tested?
`PUT /api/v1/user/notification/:id`

#### What are the relevant pivotal tracker stories?
#177810751

2021-04-22 06:46 UTC, andela-hpopoola requested changes
Thank you for working on this. I did some quick analysis and noticed that it is better to create a different model for notifications. Please let me know if you have any further questions on this. Thank you.

2021-04-22 06:46 UTC, andela-hpopoola commented on server/services/user.service.js
> +export const markNotificationAsRead = async ({ userId, notificationId }) => {
Awesome. We would also need another endpoint to mark all notifications as READ.

2021-04-22 06:46 UTC, andela-hpopoola commented on server/services/user.service.js
> +      description: notification.description,
Adding a notification does not pass through any validation, so it makes sense to use the optional chaining (?.) and defaults when any of the values are missing.

2021-04-22 06:46 UTC, andela-hpopoola commented on server/services/user.service.js
> +      type: notification.type,
Notification type should be one of the following (DANGER is the default):

```js
export const NOTIFICATION_TYPE = {
  DANGER: 0,
  CONTENT: 1,
  INFO: 2,
  SUCCESS: 3,
};
```

2021-04-22 06:46 UTC, andela-hpopoola commented on server/services/user.service.js
> +      description: notification.description,
A similar file like this should be created for notifications (maybe under helpers folder)

https://github.com/Highrachy/ballers-api/blob/ft-create-notifications-177810751/mailer/index.js

This would enable us to define notifications in one place and know the content for each notification.

```js
const NOTIFICATIONS = {
  ACTIVATE_YOUR_ACCOUNT: {
    description:
      'Your ballers.ng account has been successfully created.',
    type: NOTIFICATION_TYPE.INFO,
     url: '/login'
  },
...
```

2021-04-22 06:46 UTC, andela-hpopoola commented on server/routes/user.routes.js
> + * /user/notification/:id:
On a closer look, I noticed that it would be best to create a different model for notifications instead of embedding it in the user model. My reasons are:

1. I noticed that the notifications of an ADMIN could be more than expected, so it is better to load only the needed notifications, maybe the first 20 to save bandwidth and make the application faster.
2. Saving it in its own model gives us the luxury of adding pagination, filters and sorting which is very important for long time users.

2021-04-22 07:47 UTC, andela-hpopoola commented on server/services/user.service.js
> +export const markNotificationAsRead = async ({ userId, notificationId }) => {
We would also need another endpoint to read a single Notification.

2021-04-22 16:29 UTC, andela-hpopoola requested changes
Thank you for working on this. I left a few more comments on ensuring that we are moving in the right direction. Nice work 👍🏽

2021-04-22 16:29 UTC, andela-hpopoola commented on notifications/index.js
> +  WELCOME_MESSAGE: {
In this part, you are meant to add all of the contents in the mailer field here. I believe you should be able to deduce the description from the content top. Moreover, we can always update it later even if the contents are invalid.

2021-04-22 16:29 UTC, andela-hpopoola commented on server/controllers/notification.controllers.js
> +  getOneNotification(req, res, next) {
I thought we have agreed that this is no longer needed. Feel free to remove this (if you like).

2021-04-22 16:29 UTC, andela-hpopoola commented on server/controllers/notification.controllers.js
> +  markNotificationAsRead(req, res, next) {
Don't forget to add the `Mark All Notifications As Read` endpoint

2021-04-22 16:29 UTC, andela-hpopoola commented on server/models/notification.model.js
> + *            type: number
I think this should be a `string` or do we want to enter the description in binary numbers 😂

2021-04-22 16:29 UTC, andela-hpopoola commented on server/helpers/filters.js
> +  status: { type: FILTER_TYPE.INTEGER },
Since this is just 2 digits, let's change it to `read` and make it `BOOLEAN` for better understanding.

2021-04-22 16:29 UTC, andela-hpopoola commented on server/models/notification.model.js
> +    URL: {
Let's make this be in lowercase to conform with other values 🙏🏽 

```suggestion
    url: {
```

2021-04-22 16:29 UTC, andela-hpopoola commented on server/services/user.service.js
> +    await createNotification({ userId: savedUser._id, description: 'WELCOME_MESSAGE' }).catch(
This looks weird as you didn't make the best use of the constants 🤷🏽‍♂️ 

Rather, lets get the content of the notification we want to add and pass it into the function directly:

```js
await createNotification(NOTIFICATIONS.WELCOME_MESSAGE, savedUser._id)
```

See the implementation of mailer service here:

https://github.com/Highrachy/ballers-api/blob/00513ad263ab539443397e76fd85c2663eaf795c/server/services/mailer.service.js#L53

2021-04-22 16:29 UTC, andela-hpopoola commented on server/services/notification.service.js
> +      description: NOTIFICATIONS[data.description].description,
This implementation looks confusing. If you pass the notification object as advised above, you should be able to use it as 

I didn't use the question mark here because I am destructuring from the parameter.

```js
export const createNotification = async ({ description, type, url}, userId) => {
 try {
    const notification = await new Notification({ description, type, userId, url}).save()
```

2021-04-22 16:31 UTC, andela-hpopoola commented on server/services/user.service.js
> +export const markNotificationAsRead = async ({ userId, notificationId }) => {
Can you resolve this only when you have implemented the requested endpoint 😏

2021-04-23 00:19 UTC, tobieeniafe commented on server/controllers/notification.controllers.js
> +  getOneNotification(req, res, next) {
But you mentioned that you needed it so you could be able to mark a notification as read. Or did I miss something?

2021-04-23 06:54 UTC, andela-hpopoola requested changes
Thank you for working on this. I left more comments but this should be good to go when you have written the tests.

One last thing though, can we aggregate unread notifications to the returned values  in the `user/who-am-i` endpoint. This is to make it easier for users to know when they have a new notification without visiting the get all notifications endpoint. This can be done in a different PR though. Thank you.

2021-04-23 06:54 UTC, andela-hpopoola commented on server/services/notification.service.js
> +      { $set: { read: NOTIFICATION_STATUS.READ } },
I feel this is more readable as true or false
```suggestion
    { $set: { read: true } },
```

2021-04-23 06:54 UTC, andela-hpopoola commented on server/services/notification.service.js
> +      { $set: { read: NOTIFICATION_STATUS.READ } },
Same comment as above

2021-04-23 06:54 UTC, andela-hpopoola commented on server/helpers/constants.js
> +export const NOTIFICATION_STATUS = {
This can be removed so that we can use the true and false directly.

2021-04-23 06:54 UTC, andela-hpopoola commented on notifications/index.js
> +    description: 'Complete your registration by verifying your email',
```suggestion
    description: 'Your account has been successfully created',
```

2021-04-23 06:54 UTC, andela-hpopoola commented on notifications/index.js
> +    description: 'Visitation to property cancelled',
We need to add the property name here.

```suggestion
    description: 'The visitation to [property] property has been cancelled',
```

2021-04-23 06:54 UTC, andela-hpopoola commented on notifications/index.js
> +    type: NOTIFICATION_TYPE.INFO,
```suggestion
    type: NOTIFICATION_TYPE.DANGER,
```

2021-04-23 06:54 UTC, andela-hpopoola commented on notifications/index.js
> +    type: NOTIFICATION_TYPE.INFO,
```suggestion
    type: NOTIFICATION_TYPE.SUCCESS,
```

2021-04-23 06:54 UTC, andela-hpopoola commented on notifications/index.js
> +    description: 'Your prperty has been flagged',
```suggestion
    description: 'Your property has been flagged',
```

2021-04-23 06:54 UTC, andela-hpopoola commented on notifications/index.js
> +    type: NOTIFICATION_TYPE.INFO,
```suggestion
    type: NOTIFICATION_TYPE.SUCCESS,
```

2021-04-23 06:54 UTC, andela-hpopoola commented on server/controllers/notification.controllers.js
> +  getOneNotification(req, res, next) {
I think you missed the last part where we agreed that this might not be needed when we checked out GitHub's notification system. No worries, feel free to leave it.

2021-04-25 07:06 UTC, andela-hpopoola requested changes
Thank you for working on this. I left a few comments on perfecting this so this should be ready to merge once you fixed the raised issues.

2021-04-26 15:20 UTC, tobieeniafe commented on test/controllers/notification.controller.test.js
> +            .set('authorization', [adminToken, vendorToken, editorToken][index])
The test is testing if other users can mark the notification of another user as read. In this case, trying to mark the notification of the `regularUser` as read.

2021-04-26 16:41 UTC, andela-hpopoola requested changes
Thank you for the hard work. I left one comment on ensuring we tested the saved notification the right way. I believe it should take too much time, however, feel free to move to other stories if you are stuck on it instead of wasting time on it for the rest of the day. We can discuss the implementation during stand up tomorrow. The next stories are 
- loading unread notifications for the `who-am-i` endpoint
- Add all notifications to the right services.

Thank you.

2021-04-26 16:41 UTC, andela-hpopoola commented on test/services/user.service.test.js
> +        expect(currentCountedNotifications).to.eql(countedNotifications + 1);
This looks good but counting the notification is prone to lots of errors as we might be saving the wrong notification or saving the notification for the wrong user. 

It would be better to retrieve the saved notification from the database and compare the value that was saved. At least, we need to confirm the following to be sure that the right notification was saved:
1. userId
2. type
3. description

You should import the notification file and compare the values with this. The best way is to create a test function (like pagination test functions) that we would pass the notification type and userId. The test function would get the last notification and compare every necessary detail that was passed.

2021-04-27 06:38 UTC, andela-hpopoola approved these changes
Thank you for working on this. This looks good to go 💯

2021-04-27 06:38 UTC, andela-hpopoola commented on test/helpers.js
> +    it('adds a new notification for user', async () => {
This doesn't seem like an async function

```suggestion
    it('adds a new notification for user', () => {
```

2021-04-27 06:38 UTC, andela-hpopoola commented on test/services/user.service.test.js
> +      expectNewNotificationToBeAdded(user._id, NOTIFICATIONS.WELCOME_MESSAGE);
Awesome. Implemented as discussed 🙌🏽

2021-04-27 06:42 UTC, andela-hpopoola commented on server/services/notification.service.js
> +    return Notification.updateMany({ userId }, { $set: { read: true } }, { new: true });
Any luck with this ☝🏽

2021-04-27 11:55 UTC, merged