#177737617 enable seeding of models
Highrachy/ballers-api pull request #163
Opened 2021-04-30 01:52 UTC by tobieeniafe

#### What does this PR do?
Enable seeding of models for auto-population of database

#### Description of Task to be completed?
Enable seeding of models for auto-population of database

#### How should this be manually tested?
`npm run seed`
`SEED=model LIMIT=number`

#### What are the relevant pivotal tracker stories?
#177737617

2021-04-30 05:32 UTC, andela-hpopoola requested changes
Thank you for working on this. This is a good start but I left a few comments to make it even better.

2021-04-30 05:32 UTC, andela-hpopoola commented on seeding/index.js
> +  const model = process.env.SEED;
We should have a constant that defines all the models that we can seed in the database. For now, it would contain USER, RESET, UNKNOWN.
```suggestion
  const model = process.env.MODEL || MODEL.UNKNOWN;
```

2021-04-30 05:32 UTC, andela-hpopoola commented on seeding/index.js
> +  const limit = process.env.LIMIT;
```suggestion
  const limit = process.env.LIMIT || 1;
```

2021-04-30 05:32 UTC, andela-hpopoola commented on seeding/index.js
> +        case 'user':
```suggestion
        case MODEL.USER:
```

2021-04-30 05:32 UTC, andela-hpopoola commented on seeding/index.js
> +          seedUsers(limit);
We should pass the role of the user here, we would use the role to determine the type of user we wish to seed.

2021-04-30 05:32 UTC, andela-hpopoola commented on seeding/index.js
> +        case 'vendor':
This is not needed as it is not scalable since we have other roles.

2021-04-30 05:32 UTC, andela-hpopoola commented on seeding/index.js
> +        default:
We need to add a message here to tell the user that they have input an invalid MODEL and also list the available models that are supported via seeding.

2021-04-30 05:32 UTC, andela-hpopoola commented on seeding/index.js
> +    if (model) {
This is also not needed. I feel it is safer for us to only seed when we know the model the user wants to seed.

2021-04-30 05:32 UTC, andela-hpopoola commented on seeding/index.js
> +      seedUsers(limit);
This is not needed as it would be defined in RESET. This should be a function when we would clear the database and create a new set of models.

2021-04-30 05:32 UTC, andela-hpopoola commented on seeding/user.seeding.js
> +export const seedVendors = async (number = 1) => {
I think a new function for vendors is not needed as it can be embedded in the `seedUsers` function above. The vendor object defined below should be used if the role of the user is `vendor`. This ensures that we are maintaining only 1 function instead of 2 when we start adding more functionalities to the function. It also prevents us from creating additional functions for other roles.

2021-04-30 05:32 UTC, andela-hpopoola commented on package.json
> +    "faker": "^5.5.3",
This should be installed as a `devDependencies` (see line 29 on this file) as it is only needed on the dev environment. Can you uninstall and reinstall with ` --save-dev`. Something like this:

```
npm install faker --save-dev
```

2021-04-30 05:32 UTC, andela-hpopoola commented on seeding/index.js
> +    logger.info('done');
Lets use `chalk` instead of logger here. This will enable us to use green colour for success, yellow for loading, blue for info, and red for errors.

https://www.npmjs.com/package/chalk

2021-05-01 19:50 UTC, tobieeniafe commented on package.json
> +    "faker": "^5.5.3",
This throws an error about importing a dev dependency. Can't seem to find a way around it

2021-05-02 11:19 UTC, andela-hpopoola requested changes
Thank you for working on this. I left more comments on some of the areas you missed. Hopefully, we are almost through with the first part of the seeding.

2021-05-02 11:19 UTC, andela-hpopoola commented on package.json
> +    "seed:dev": "nodemon --exec babel-node ./seeding/index.js",
Not sure why you added this as seeding is only needed in development (and maybe staging). I believe we only need the one above as seeding is meant to be a 1-time thing. This can be removed 🙏🏽

2021-05-02 11:19 UTC, andela-hpopoola commented on seeding/index.js
> +  USER: 'user',
Lets ensure that that the values of the `env` variables we are getting from the user is in uppercase for consistency sake:

```suggestion
  USER: 'USER',
```

Please update the one below too for `RESET`

2021-05-02 11:19 UTC, andela-hpopoola commented on seeding/index.js
> +  const model = process.env.MODEL;
Let's convert the value of model to uppercase if a valid model is given.

2021-05-02 11:19 UTC, andela-hpopoola commented on seeding/index.js
> +        logInfo(`Invalid model input. Available models are: ${Object.values(MODEL)}`);
I think this is better as an Error.

```suggestion
        logError(`Invalid model input. Available models are: ${Object.values(MODEL)}`);
```

2021-05-02 11:19 UTC, andela-hpopoola commented on seeding/user.seeding.js
> +const seedUsers = async (limit, role) => {
We should be able to pass in some default values here so that we can consistent results when we reset the database. So for default we should always create at least 1 user type each  for each role with the same email to avoid thinking about the email or password of the created user.

2021-05-02 11:19 UTC, andela-hpopoola commented on seeding/user.seeding.js
> +    role: USER_ROLE[role.toUpperCase()],
It looks like `password` field is missing here. Can you please add it and use a default password of `passworded` for all created users 🙏🏽. 

Also, can we add other fields like
- activationDate,
- phone2 (Try getting a random number from 0 to 1, if it is greater than 0.5 then you should add a phone2 else you will leave it as null)
- profileImage

2021-05-02 11:23 UTC, andela-hpopoola commented on package.json
> +    "faker": "^5.5.3",
Strange! From the docs, this shouldn't throw an error

https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md

Let me know if this continues so that we can explicitly disable it from eslint.

2021-05-04 07:42 UTC, andela-hpopoola requested changes
Looks much better, thank you for working on this.

2021-05-04 07:42 UTC, andela-hpopoola commented on seeding/index.js
> +  const model = process.env.MODEL.toUpperCase();
You might need to add chaining here in case `MODEL` is undefined to prevent an error.

```
   const model = process.env.MODEL?.toUpperCase();
```

2021-05-04 07:42 UTC, andela-hpopoola commented on seeding/reset.seeding.js
> +    return setTimeout(resolve, 5000);
I believe the Promise here is for testing purposes, can we remove it if it doesn't add value to the code.

2021-05-04 07:42 UTC, andela-hpopoola commented on seeding/reset.seeding.js
> +    await Promise.all(
🙌🏽 Awesome. 

Nice concept here. However, can we place it in a different function so that we don't congest these sections when we add more models?

Lets create a function called `addDefaultUsers` and call the function here.

2021-05-04 07:42 UTC, andela-hpopoola commented on seeding/user.seeding.js
> +    confirmPassword: 'passworded',
This is not needed as we are inserting the user details into the database directly.

2021-05-04 07:42 UTC, andela-hpopoola commented on seeding/user.seeding.js
> +    password: 'passworded',
This should be hashed. We can used the `hashPassword` helper class in `user.service.js`

2021-05-04 11:52 UTC, tobieeniafe commented on seeding/reset.seeding.js
> +    return setTimeout(resolve, 5000);
I noticed that when there's data in the database, there's usually a concurrent background event from `seedUsers` trying to add users throwing a duplicate error. So the promise is to delay till the database is cleared before running.

2021-05-06 05:37 UTC, andela-hpopoola commented on seeding/reset.seeding.js
> +    return setTimeout(resolve, 5000);
Adding the setTimeout would not fix the problem you alighted above and looks like a hack that wouldn't work every time or on every machine. Also, we don't need the unnecessary delay (it's unproductive). 


The best fix in my own opinion is to wait for the promise clearing the database to resolve. That way we are sure that that the database has been cleared and we can continue with the addition of the data.

2021-05-06 06:17 UTC, andela-hpopoola requested changes
Thank you for the updates on this. Here are some more things to fix

- Disconnect from the database after seeding
- Ensure that seeding is only done on the Development Environment (we don't want to mistakenly seed on the Production Database)
- Improve logs (maybe I will work on this on a later PR)

Thank you.

2021-05-06 06:17 UTC, andela-hpopoola commented on seeding/seed-helpers.js
> +import logger from '../server/config/winston';
Since we are making this a development stuff only, lets remove `logger` and use `console.log` for simplicity. Also, you would need to add `/* eslint-disable no-console */` at the top of the file to disable this.

2021-05-06 06:17 UTC, andela-hpopoola commented on seeding/user.seeding.js
> +  const roleValue = Object.keys(ROLE).find((key) => ROLE[key] === role);
Lets have a default roleValue of `User` here is the role is not given.

2021-05-06 06:17 UTC, andela-hpopoola commented on seeding/user.seeding.js
> +  const hashedPassword = await hashPassword('passworded');
Lets create a DEFAULT_PASSWORD constant in the constant file so that it is easier to update (incase anyone wants to update the DEFAULT PASSWORD for their own use case).

2021-05-06 06:17 UTC, andela-hpopoola commented on seeding/user.seeding.js
> +      logLoading(`${limit} ${parseInt(limit, 10) === 1 ? role : `${role}s`} created`);
We would need to out a list of all the user's email and password created in the seed. You can use the package below:

https://www.npmjs.com/package/console.table

2021-05-07 01:52 UTC, tobieeniafe commented on seeding/user.seeding.js
> +  const roleValue = Object.keys(ROLE).find((key) => ROLE[key] === role);
The role is already `user` by default.

2021-05-07 05:36 UTC, andela-hpopoola commented on seeding/reset.seeding.js
> +    return setTimeout(resolve, 5000);
Can you look this and see if you can fix this without using `setTimeout`?

2021-05-07 05:51 UTC, andela-hpopoola requested changes
Thank you for working on this. I left a few comments but the most important one is finding a way to remove the setTimeout used when clearing the database. Once that is resolved, this should be safe to merge. Thank you.

2021-05-07 05:51 UTC, andela-hpopoola commented on seeding/user.seeding.js
> +  const hashedPassword = await hashPassword(customValues.password || DEFAULT_PASSWORD);
We can get the password first before hashing the password so that it can be reused in multiple places instead of using `customValues.password || DEFAULT_PASSWORD`.

```js
const password = customValues.password || DEFAULT_PASSWORD;
const hashedPassword = await hashPassword(password);
```

2021-05-07 05:51 UTC, andela-hpopoola commented on seeding/user.seeding.js
> +        table.push({ email: user.email, password: customValues.password || DEFAULT_PASSWORD });
Take note of the capital `E` in email and `P` in password.

```suggestion
        table.push({ Email: user.email, Password: password });
```

2021-05-07 05:51 UTC, andela-hpopoola commented on seeding/index.js
> +  logError('Seeding is only available in development');
```suggestion
  logError('Seeding is only available in `development environment`');
```

2021-05-08 05:30 UTC, andela-hpopoola approved these changes
Looks good to me. Thank you for working on this 🙌🏽

2021-05-08 09:26 UTC, merged