#178279062 link offer to referral model
Highrachy/ballers-api pull request #175
Opened 2021-05-25 23:44 UTC by tobieeniafe

#### What does this PR do?
Link offer to referral model when offer is accepted

#### Description of Task to be completed?
Link offer to referral model when offer is accepted

#### How should this be manually tested?
`PUT /api/v1/offer/accept`

#### What are the relevant pivotal tracker stories?
#178279062

2021-05-26 06:38 UTC, andela-hpopoola requested changes
Thank you for working on this. I left a few comments but I think we are in the right direction. Can you write tests for this so that we can proceed to the next story 🙏🏽 . Thank you.

2021-05-26 06:38 UTC, andela-hpopoola commented on server/services/offer.service.js
> +  const { isReferred, referralId } = await userIsReferredWithoutActiveReferral(offer.userId);
I think we don't need the `isReferred` variable here as we can make use of `referralId` to confirm if a user has a pending referral. If `referralId` is null, then `isReferred` will be false, hence making it obsolete.

Also, we can update the function to `getPendingUserReferral` and return the `referralId` only.

```suggestion
  const referralId = await getPendingUserReferral(offer.userId);
```

2021-05-26 06:38 UTC, andela-hpopoola commented on server/services/referral.service.js
> +  return { isReferred: referral.length !== 0, referralId: referral[0]?._id || null };
I think this should work 🤷🏽‍♂️ 

```suggestion
  return referral?.[0]?._id
```

2021-05-26 06:38 UTC, andela-hpopoola commented on server/services/offer.service.js
> +    await startReferral({ referralId, offerId: offer._id });
Not sure if this will make the code better, but I think we can combine the `userIsReferredWithoutActiveReferral`  and the `startReferral` function together into a single function like `activateReferral` so that the checking if the referral exist and the actual updates is handled by one function.

2021-05-26 06:38 UTC, andela-hpopoola commented on server/services/referral.service.js
> +  const referral = await Referral.aggregate([
Can we destructure this to make it easier to use:
```suggestion
  const [referral] = await Referral.aggregate([
```

2021-05-26 18:31 UTC, andela-hpopoola requested changes
Thank you for making the updates, I added a few nits to improve the code quality. Thank you.

2021-05-26 18:31 UTC, andela-hpopoola commented on server/services/referral.service.js
> +export const getPendingUserReferral = async ({ userId, offerId }) => {
This should be `activatePendingUserReferral` instead of `getPendingUserReferral` as the main purpose of this function is to update the reward status to `Started` and not to get the Referral information.

2021-05-26 18:31 UTC, andela-hpopoola commented on server/services/referral.service.js
> +  try {
I would be careful to only run this try block if and only if `referral` is not empty. We don't want to update when `referralId` is null 🤷🏽‍♂️

2021-05-26 18:31 UTC, andela-hpopoola commented on server/services/referral.service.js
> +  const referral = await Referral.find({
I think I would want to use findOne here since we are expecting the returned referral to be 1.

2021-05-26 18:31 UTC, andela-hpopoola commented on server/services/referral.service.js
> +  const referralId = referral?.[0]?._id;
If we use `findOne` above, this will no longer be necessary as we can check if referral is empty and get referralId with `referral._id` if referral is not empty.

2021-05-26 20:12 UTC, andela-hpopoola requested changes
Thank you for making the changes. I left a few comments but the most important on is adding the calculated amount to the referral model, adding more tests and fixing the broken tests. Thank you.

2021-05-26 20:12 UTC, andela-hpopoola commented on server/services/referral.service.js
> +  try {
This has not been resolved. We should not update the Referral model if referral is null. Apart from throwing an error on line 231 for `referral._id`,  we are making a request that is not needed.

2021-05-26 20:12 UTC, andela-hpopoola commented on test/controllers/referral.controller.test.js
> +              expect(res).to.have.status(500);
This looks strange. I would expect `res.status` and `error.statusCode` on line 606 to have the same value.

2021-05-26 20:12 UTC, andela-hpopoola commented on test/services/offer.service.test.js
> +          expect(updatedReferral.referrerId).to.eql(user2._id);
I think we should also update the referral amount (1.5%) when linking the offer to the referral.

2021-05-26 20:12 UTC, andela-hpopoola commented on test/services/offer.service.test.js
> +      context('when all is valid', () => {
```suggestion
      context('when the referral is pending', () => {
```

We need to confirm that the reward status is only updated when it is `PENDING`. You might need to use a loop to test for other reward status.

2021-05-26 20:12 UTC, andela-hpopoola commented on test/services/offer.service.test.js
> +    describe('when user was referred', () => {
Also, we need to add tests for situations where the user is not referred.

2021-05-26 20:18 UTC, andela-hpopoola commented on server/services/referral.service.js
> +    'reward.status': REWARD_STATUS.PENDING,
I think we also need to check that `referral.status` is `REFERRAL_STATUS.REGISTERED` to cater for situations where more than one person referral a user and use the actual referralId that they registered with.

You would also need to add tests to verify this (i.e when a user is referred multiple times, we only get the one they registered with and add one more test to confirm that we don't get a referral with `REFERRAL_STATUS` of `REWARDED`)

2021-05-27 07:51 UTC, tobieeniafe commented on test/controllers/referral.controller.test.js
> +              expect(res).to.have.status(500);
The error is thrown from line `146` `referral.service.js` when the `getReferralById` function is called by the `updateReferralToRewarded`.

2021-05-27 16:35 UTC, andela-hpopoola requested changes
Thank you for your hardwork on this. I left a few comments to conclude this. Nice work.

2021-05-27 16:35 UTC, andela-hpopoola commented on server/services/offer.service.js
> +  await activatePendingUserReferral({ userId: offer.userId, offer });
I think it makes more sense to just pass `offer` only here since we can get the `userId` from offer.

```suggestion
  await activatePendingUserReferral({ offer });
```

2021-05-27 16:35 UTC, andela-hpopoola commented on test/controllers/referral.controller.test.js
> +              expect(res).to.have.status(500);
Lets remove this, please. It is so confusing.

2021-05-27 16:35 UTC, andela-hpopoola commented on test/services/offer.service.test.js
> +        delete startedReferralStatuses[0];
You will need to be more explicit here, that is to provide the key of the object you are deleting. This will be problematic if a new status is added as index 0 to REWARD_STATUS

2021-05-27 16:35 UTC, andela-hpopoola commented on test/services/offer.service.test.js
> +          status: REFERRAL_STATUS.REGISTERED,
I think we would need another set of tests to confirm that the updates are made when status is `REFERRAL_STATUS.REGISTERED`

2021-05-28 06:27 UTC, andela-hpopoola approved these changes
Looks good to me. Thank you for working on this.

2021-05-28 06:27 UTC, andela-hpopoola commented on test/services/offer.service.test.js
> +        const startedReferralStatuses = Object.keys(REWARD_STATUS).filter(
```suggestion
        const nonPendingReferralStatuses = Object.keys(REWARD_STATUS).filter(
```

2021-05-28 13:25 UTC, merged