#178601149 add bank details to user model
Highrachy/ballers-api pull request #191
Opened 2021-06-21 22:19 UTC by tobieeniafe

#### What does this PR do?
Add bank details to user model

#### Description of Task to be completed?
Add bank details to user model

#### How should this be manually tested?
NA

#### What are the relevant pivotal tracker stories?
#178601149

2021-06-22 05:26 UTC, andela-hpopoola requested changes
Thank you for working on this. I think we need 2 more things to wrap up this PR:

1. Let's return the additionalInfo object only when the user or an admin views the user information
2. Add tests to ensure that a user can correctly add his bank account details via the update endpoint for users.

Thank you.

2021-06-23 05:17 UTC, andela-hpopoola requested changes
Thank you for working on this. This looks good enough but your implementation seems off. Also, I think you missed this:

> Let's return the additionalInfo object only when the user or an admin views the user information

We would also need to add tests for this too.

2021-06-23 05:17 UTC, andela-hpopoola commented on server/controllers/user.controllers.js
> +    updateUser({ ...updatedUser, id: req.user._id })
Not sure why you are removing this 🤷🏽‍♂️

2021-06-23 05:17 UTC, andela-hpopoola commented on server/services/user.service.js
> +  const user = await getUserById(updatedUser.id);
Getting the user information just to update their information seems wrong. If this is necessary, then the previous implementation seems better than your new implementation. Not sure why you made the changes though.

2021-06-23 05:17 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> -      context('with invalid updated user', () => {
Not sure why you removed this.

2021-06-23 08:03 UTC, tobieeniafe commented on test/controllers/user.controller.test.js
> -      context('with invalid updated user', () => {
The test was passing because no body was being sent. Now that the fields are all optional, it'd fail.

2021-06-23 20:27 UTC, andela-hpopoola requested changes
Thank you for making the changes. I think the PR is still missing this:

> Let's return the additionalInfo object only when the user or an admin views the user information

2021-06-24 00:02 UTC, tobieeniafe commented
> Thank you for making the changes. I think the PR is still missing this:
> 
> > Let's return the additionalInfo object only when the user or an admin views the user information

The endpoints `/user/all` and `/user/:id` only list what data not to project. Unless you have another endpoint in mind.

2021-06-24 06:22 UTC, andela-hpopoola commented
> > Thank you for making the changes. I think the PR is still missing this:
> > > Let's return the additionalInfo object only when the user or an admin views the user information
> 
> The endpoints `/user/all` and `/user/:id` only list what data not to project. Unless you have another endpoint in mind.

Yes, however we need to consider all the places where the following are used to be sure that the bankDetails are returned only where necessary and for admins and or users:

- NON_PROJECTED_USER_INFO
- PROJECTED_ASSIGNED_USER_INFO
- NON_PROJECTED_USER_INFO
-  projectedReferralInfoForAdmin - For this, we would want to include the bank details of the referral.

Please note that I didn't check the usage of the 3 constants above -- I am leaving it to you to confirm that the bankDetails is safe where they are used.

2021-06-24 06:25 UTC, andela-hpopoola commented
Also, we might also write tests (one-liner tests ) to ensure that `additional info` is returned or not returned where it is needed. Something like `expect additionalInfo to (not) be present/ exist/ not empty` should work.

2021-06-25 05:28 UTC, andela-hpopoola approved these changes
Thank you for making the changes. Looks good to me.

2021-06-25 06:08 UTC, merged