#178601157 allow admin change user referral percentage
Highrachy/ballers-api pull request #194
Opened 2021-06-28 02:15 UTC by tobieeniafe

#### What does this PR do?
Allow admin change user referral percentage

#### Description of Task to be completed?
Allow admin change user referral percentage

#### How should this be manually tested?
`PUT /api/v1/referral/percentage`
#### What are the relevant pivotal tracker stories?
#178601157

2021-06-28 18:52 UTC, andela-hpopoola requested changes
Thank you for working on this. The referral percentage should be in the user model as discussed in the morning. I am dropping this comment just to be sure that we are on the same page. Thank you.

2021-06-29 05:49 UTC, andela-hpopoola approved these changes
Looks good to me. Thank you for working on this.

2021-06-29 05:49 UTC, andela-hpopoola commented on server/models/user.model.js
> +        type: Number,
Can we make the default the current REFERRAL_PERCENTAGE for consistency?

2021-06-29 05:49 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +        { role: USER_ROLE.VENDOR, activated: true, 'additionalInfo.referralPercentage': 1.5 },
Lets add the default referral percentage value of 1.5  to the user factory.

2021-06-29 21:34 UTC, tobieeniafe commented on test/controllers/user.controller.test.js
> +        { role: USER_ROLE.VENDOR, activated: true, 'additionalInfo.referralPercentage': 1.5 },
Adding it to the factory breaks the tests because of Joi.

2021-06-29 22:49 UTC, merged