#178703269 add automated badges
Highrachy/ballers-api pull request #204
Opened 2021-07-07 00:25 UTC by tobieeniafe

#### What does this PR do?
Add automated badges

#### Description of Task to be completed?
Add automated badges

#### How should this be manually tested?
NA

#### What are the relevant pivotal tracker stories?
#178703269

2021-07-07 06:12 UTC, andela-hpopoola requested changes
Thank you for working on this. I left a few comments to ensure that the implementation is done in the right way. Also, you would need to create a custom function test to make testing automatic badges easier.

2021-07-07 06:12 UTC, andela-hpopoola commented on server/helpers/automatedBadges.js
> +const AUTOMATED_BADGES = {
We need to be more explicit with the defaults defined here as we have done for `mailer/index.js`. We should define the name, slug, assignedRole, icon name (can be set to 'default'), and colour.

2021-07-07 06:12 UTC, andela-hpopoola commented on server/services/assignedBadge.service.js
> +    badge = await addBadge({ name: slug });
We should add the whole badge object with a valid name, role and icon information -- not using a generated name from the slug.

2021-07-07 06:12 UTC, andela-hpopoola commented on server/services/assignedBadge.service.js
> +export const assignBadgeAutomatically = async (slug, userId) => {
I think it is better we pass the user object here to confirm that the user has the right role before we assign the badge to them.

2021-07-07 06:12 UTC, andela-hpopoola commented on server/services/transaction.service.js
> +// eslint-disable-next-line import/no-cycle
I don't think this is necessary as the transaction service is not used in assignedBadge, can you re-verify?

2021-07-07 16:15 UTC, tobieeniafe commented on server/services/assignedBadge.service.js
> +  let badge;
`badge` can't be a constant here, because it's going to be reassigned to the generated badge if the slug does not exist.

2021-07-08 02:25 UTC, tobieeniafe commented on server/services/assignedBadge.service.js
> +export const assignBadgeAutomatically = async (slug, userId) => {
This check is already carried out in the `assignBadge` service

2021-07-08 06:28 UTC, andela-hpopoola approved these changes
Thank you for making the updates. I left a few more comments on this, however, this should be good to go once you fix the comments. Thank you and nice work.

2021-07-08 06:28 UTC, andela-hpopoola commented on test/services/transaction.service.test.js
> +        context('when badge is assigned', () => {
```suggestion
        context('when user makes their first payment', () => {
```

2021-07-08 06:28 UTC, andela-hpopoola commented on test/services/transaction.service.test.js
> +      context('when badge is assigned', () => {
```suggestion
      context("when its the vendor's first sale", () => {
```

2021-07-08 06:28 UTC, andela-hpopoola commented on test/services/user.service.test.js
> +      context('when new notification is added & badge is assigned', () => {
Lets separate the tests please 🙏🏽 ? It is better for the badge test to be in a new test case.

2021-07-08 06:28 UTC, andela-hpopoola commented on test/services/user.service.test.js
> +        expectBadgeToBeAssignedAutomatically(AUTOMATED_BADGES.VENDOR_VERIFIED, vendor._id);
This is not supposed to be under the notifications context as it would make the tests difficult to understand in the future.

2021-07-08 06:28 UTC, andela-hpopoola commented on server/services/assignedBadge.service.js
> +  let badge;
Your comment is well-noted and very correct. 

However, the point is not about the `const`, it is about not using the `badgeFromSlug` variable as it is not relevant in the code. 

If you need to use `let` instead of `const` , then this can be written as:

```suggestion
  let [badge] = await getBadgeBySlug(slug)
```

2021-07-08 06:28 UTC, andela-hpopoola commented on server/services/assignedBadge.service.js
> +  if (!badge.automated) {
Can we write tests to trigger this error 🙏🏽

2021-07-08 13:24 UTC, merged