#178926255 add video to property
Highrachy/ballers-api pull request #211
Opened 2021-07-22 11:52 UTC by tobieeniafe

#### What does this PR do?
Add video to property

#### Description of Task to be completed?
Add video to property

#### How should this be manually tested?
`POST /api/v1/property/:id/videos`
`PUT /api/v1/property/:id/videos`
`DELETE /api/v1/property/:id/videos`

#### What are the relevant pivotal tracker stories?
#178926255

2021-07-22 18:57 UTC, andela-hpopoola requested changes
Thank you for working on this. This looks good but I noticed a flaw we need to avoid. We need the admin to verify the videos that would be linked before displaying them to the users. Apologies for just realizing that 🤦🏽. 

The problem is that the current implementation will make it difficult to load newly uploaded videos for the admin to approve. If you think this can be achieved in a very easy way, let's continue with this implementation, however, if you think it would be difficult to achieve this, I would suggest we move the property video implementationinto its own model and link it to the property model. The current implementation can be easily converted to support a custom video model, so I don't really see it as a major waste of time.

Thank you.

2021-07-22 18:57 UTC, andela-hpopoola commented on server/models/property.model.js
> +        },
I think we need to add `approved` (with other necessary information) here to know the videos that have been approved by the admin.

2021-07-24 18:09 UTC, andela-hpopoola requested changes
Thank you for working on this. A couple of suggestions to improve

- The model should be called property-videos so that it doesn't disturb us if we want to add another video model in the future
- We should enforce that the videos are loaded when a single property is loaded (like gallery). 
- We need to write tests to ensure the code works as expected.

2021-07-24 18:09 UTC, andela-hpopoola commented on server/schemas/video.schema.js
> +  videoId: requiredObjectId('Video id'),
Let's make this one `id`

```suggestion
  id: requiredObjectId('Video id'),
```

2021-07-24 18:09 UTC, andela-hpopoola commented on server/services/video.service.js
> +  if (user.role === USER_ROLE.VENDOR) {
This can be merged into a single statement:

```suggestion
  if (user.role === USER_ROLE.VENDOR && user._id.toString() !== property.addedBy.toString()) {
```

2021-07-24 18:09 UTC, andela-hpopoola commented on server/services/video.service.js
> +export const getAllVideos = async (user, propertyId, { page = 1, limit = 10, ...query } = {}) => {
This is only needed for an admin. For users and vendors, the video should be loaded with the property (like Gallery).

For users, only approved videos should be loaded for a single property. For admin and vendors, all videos should be loaded.

2021-07-24 18:09 UTC, andela-hpopoola commented on server/services/video.service.js
> +        from: 'assignedbadges',
I believe this is not caught in the tests because you have not written the tests yet. This is video not badges. Please fix in other places too.

2021-07-24 18:09 UTC, andela-hpopoola commented on server/models/property.model.js
> +    videos: {
Lets be careful about this and only use it if there are no alternative. It might make video maintenance difficult.

2021-07-26 07:46 UTC, andela-hpopoola approved these changes
Thank you for working on this. As discussed, I have taken a look through it and let a few comments to fix before merging. Thank you for the great work.

2021-07-26 07:46 UTC, andela-hpopoola commented on server/models/propertyVideo.model.js
> +      type: ObjectId,
`required: true` is needed here.

2021-07-26 07:46 UTC, andela-hpopoola commented on server/helpers/filters.js
> +export const PROPERTY_VIDEO_FILTERS = {
Lets add `url` here to ensure that people can search videos via URL too.

2021-07-26 07:46 UTC, andela-hpopoola commented on server/models/propertyVideo.model.js
> +const PropertyVideoSchema = new mongoose.Schema(
Lets arrange the schema in alphabetical order. As a standard now, we would ensure that our schemas are arranged in alphabetical order. I had issues searching through offer letters for a field since the schema wasn't arranged in alphabetical order.

2021-07-26 07:46 UTC, andela-hpopoola commented on server/routes/propertyVideo.routes.js
> +  '/:id/all',
```suggestion
  '/:propertyId/all',
```

In this scenario, we need to use the `propertyId` instead of `id` to differentiate that the id in question is not the video id but the property Id

2021-07-26 07:46 UTC, andela-hpopoola commented on server/services/propertyVideo.service.js
> +
Since we are trying to make the video title to be unique, then we should also check that the updated title doesn't exist in the database (as verified when adding a new video). 

You might need to do this check if the video title is changed i.e  current video title is not equal to the old video title.

2021-07-26 22:51 UTC, tobieeniafe commented on server/routes/propertyVideo.routes.js
> +  '/:id/all',
Using `:propertyId` will prevent Joi from validating the id. The description will be stated in the description.

2021-07-26 23:18 UTC, merged