#177638844 add verification for additional terms and conditions for offer
Highrachy/ballers-api pull request #215
Opened 2021-07-31 01:17 UTC by tobieeniafe

#### What does this PR do?
Add additional terms and condition approval to offer

#### Description of Task to be completed?
Add additional terms and condition approval to offer

#### How should this be manually tested?
`PUT /api/v1/offer/:id/approve-terms`

#### What are the relevant pivotal tracker stories?
#177638844

2021-07-31 07:47 UTC, andela-hpopoola requested changes
Thank you for working on this. I think you need to pay more attention to details (considering the number of hours you worked on this). 

I think you only handled the approval workflow, you didn't specify what would happen if the admin rejects the additional terms and conditions. You need to create a flow for this to complete this story. Maybe this should be done in a different PR.

Here is my thought process:

- The admin should be able to add comments and reject the offer terms and conditions. 
- The vendor would be sent a message and the status would be changed to reflect that the vendor needs to review his terms and condition. 
- The vendor should be able to update these terms and conditions or totally remove them. 
- Totally removing them should make the offer in an approved state (GENERATED) 
- But editing it should subject the offer back to admin approval. The vendor should be able to add comments in case the admin needs clarification on a term.
- The admin should be able to reject again and add more comments.

_Please note that the workflow above is done on the fly to ease your understanding and edge cases are not considered. Ensure you totally improve this (where necessary) before you start the implementation_

Thank you.

2021-07-31 07:47 UTC, andela-hpopoola commented on server/controllers/offer.controllers.js
> +        const contentTop = `You have received an offer via ballers.ng for a "${
As explained before you started work on this, it is better we create a function to generate the mail instead of duplicating it to make it easier to update in the future.

2021-07-31 07:47 UTC, andela-hpopoola commented on server/services/offer.service.js
> +  let status = OFFER_STATUS.GENERATED;
This can be generated in a single liner (I have mentioned this severally).

```suggestion
const status = offer.additionalClause ? OFFER_STATUS.PENDING_APPROVAL : OFFER_STATUS.GENERATED;
```

2021-07-31 07:47 UTC, andela-hpopoola commented on server/services/offer.service.js
> +      await createNotification(NOTIFICATIONS.OFFER_CREATED, user._id, {
Notification creation should be handled in a different function to avoid duplication when the offer is approved.

2021-07-31 07:47 UTC, andela-hpopoola commented on server/services/offer.service.js
> +    });
I think we should also create a notification to inform the vendor that their offer has been approved.

2021-07-31 07:47 UTC, andela-hpopoola commented on server/helpers/constants.js
> +  PENDING_APPROVAL: 'Pending Approval',
```suggestion
  PENDING_ADMIN_APPROVAL: 'Pending Admin Approval',
```

2021-08-02 07:47 UTC, andela-hpopoola requested changes
Thank you for working on this. I did a quick look through and left a few comments. (I will properly review later),

2021-08-02 07:47 UTC, andela-hpopoola commented on server/helpers/filters.js
> +  approvedAdditionalClause: { key: 'additionalClause.approved', type: FILTER_TYPE.BOOLEAN },
This needs to be removed too.

2021-08-02 07:47 UTC, andela-hpopoola commented on server/helpers/funtions.js
> +import EMAIL_CONTENT from '../../mailer';
In a different PR, let's change the file name here to `functions.js`. Not sure how we missed the typo.

2021-08-02 07:47 UTC, andela-hpopoola commented on server/helpers/funtions.js
> +export const sendCreateOfferMail = (offer) => {
I believe this would be better in `offer.service.js` file

2021-08-02 07:47 UTC, andela-hpopoola commented on server/helpers/funtions.js
> +export const sendNotificationForCreatedOffer = async ({ offer, userId }) => {
This too should be moved to `offer.service.js` file

2021-08-02 07:47 UTC, andela-hpopoola commented on server/helpers/notifications.js
> +    description: 'The additional terms of your offer has been approved',
```suggestion
    description: 'The additional terms of your [property name] offer has been approved',
```

2021-08-02 07:47 UTC, andela-hpopoola commented on server/helpers/notifications.js
> +    description: 'A review has been requested on the additional terms of your offer',
```suggestion
    description: 'A review has been requested on the additional terms of your [property name] offer',
```

2021-08-02 07:47 UTC, andela-hpopoola commented on server/services/badge.service.js
> +// eslint-disable-next-line import/no-cycle
When you move the highlighted code to services, this might no longer be necessary.
_You might need to close your VS Code editor and reopen before the ESLint warning goes away_

2021-08-02 07:47 UTC, andela-hpopoola commented on server/services/enquiry.service.js
> +// eslint-disable-next-line import/no-cycle
This too should be removed.

2021-08-02 07:47 UTC, andela-hpopoola commented on server/services/offer.service.js
> +// eslint-disable-next-line import/no-cycle
This too and other related ones should be safe to remove

2021-08-03 06:45 UTC, andela-hpopoola requested changes
Thank you for working on this. I left a few comments but the most important one is adding an additional endpoint to cater to the vendor's response.

2021-08-03 06:45 UTC, andela-hpopoola commented on server/helpers/automatedBadges.js
> +// eslint-disable-next-line import/no-cycle
I believe we should be able to remove this too.

2021-08-03 06:45 UTC, andela-hpopoola commented on server/models/offer.model.js
> +          },
Let's add a `response` field here so that the vendor can respond with an answer to the question where necessary.

2021-08-03 06:45 UTC, andela-hpopoola commented on server/services/transaction.service.js
> +// eslint-disable-next-line import/no-cycle
I think this can be removed too

2021-08-03 06:45 UTC, andela-hpopoola commented on server/routes/offer.routes.js
> +  '/:id/request-terms-review',
Since the admin can request for terms and conditions to be reviewed, there should be another endpoint that would enable the vendor to fix the request. 

To differentiate this, when an admin request for a review, the status of the offer should be changed to `PENDING_VENDOR_REVIEW` to reflect this. 

We would need another endpoint that would enable the vendor to fix the request, write a response and set the offer letter back to `PENDING_ADMIN_APPROVAL`.

2021-08-03 06:45 UTC, andela-hpopoola commented on test/controllers/offer.controller.test.js
> +      const data = { comment: 'Please review clause 2' };
```suggestion
      const data = { comment: 'Please review clause 2' };
```

I noticed that you used `comment` in the test for this instead of `question` used in the model. Lets update the model to `comment` for admin's comment so that it would be in sync. 

Please note that I think `comment` is a better representation in the model than `question` since the admin might not be asking a question.

2021-08-05 07:37 UTC, andela-hpopoola requested changes
Thank you for working on this. I left a few more comments on ensuring that the normal workflow is followed when the terms and condition is removed.

2021-08-05 07:37 UTC, andela-hpopoola commented on test/controllers/offer.controller.test.js
> +    describe('Remove Additional Terms from Offer', () => {
```suggestion
    describe('Respond to Terms Review', () => {
```

2021-08-05 07:37 UTC, andela-hpopoola commented on test/controllers/offer.controller.test.js
> +              expect(res.body.offer.additionalClause.clauses.length).to.be.eql(0);
We need a test to confirm that the email and notifications are sent to the user (owner of the offer).

2021-08-05 07:37 UTC, andela-hpopoola commented on server/models/offer.model.js
> +          dateResponded: {
Lets move this to after `dateAsked` to ensure that they are arranged in alphabetical order.

2021-08-05 07:37 UTC, andela-hpopoola commented on server/services/offer.service.js
> +  }" in "${offer.propertyInfo.name}". This offer is Valid till ${new Date(
```suggestion
  }" in "${offer.propertyInfo.name}". This offer is valid till ${new Date(
```

2021-08-05 07:37 UTC, andela-hpopoola commented on server/services/offer.service.js
> +    Date.parse(offer.expires),
Lets use a related date helper function here

2021-08-05 07:37 UTC, andela-hpopoola commented on server/services/offer.service.js
> +    return Offer.findByIdAndUpdate(
When the additional terms is removed, we should follow the same process as an approved terms and conditions, that is, create notification and send emails to the user.

2021-08-06 05:43 UTC, andela-hpopoola approved these changes
Thank you for working on this. This looks good to me. Feel free to merge.

2021-08-06 05:43 UTC, andela-hpopoola commented on server/services/offer.service.js
> +  const status = offer.additionalClause
I think this can be rewritten as:

```suggestion
  const status = offer.status || offer.additionalClause ? OFFER_STATUS.PENDING_ADMIN_APPROVAL : OFFER_STATUS.GENERATED
```

2021-08-06 07:20 UTC, tobieeniafe commented on server/services/offer.service.js
> +  const status = offer.additionalClause
Not in this scenario. This was written for test cases where `additionalClause` exists, and we want to use a custom status asides `PENDING_ADMIN_APPROVAL` and `GENERATED`

2021-08-06 07:21 UTC, merged