#179316675 user should pay for VAS - Part 3
Highrachy/ballers-api pull request #249
Opened 2021-09-15 00:07 UTC by tobieeniafe

#### What does this PR do?
Update transaction model to accommodate multiple models

#### Description of Task to be completed?
Update transaction model to accommodate multiple models

#### How should this be manually tested?
`/transaction/`

#### What are the relevant pivotal tracker stories?
#179316675

2021-09-15 06:47 UTC, andela-hpopoola requested changes
Thank you for working on this. I left a few comments to ensure we are on the right track for this. Thank you.

2021-09-15 06:47 UTC, andela-hpopoola commented on server/services/transaction.service.js
> +      await generateNextPaymentDate({
Let's add all of the code here in a new function `processOfferTransaction` to make this function lean. This also makes it easier to add more codes for other model types without bloating this function.

2021-09-15 06:47 UTC, andela-hpopoola commented on server/models/transaction.model.js
> -    propertyId: {
You might need to confirm that we didn't use `propertyId` to aggregate transactions anywhere. If we do, we need to think of a way to reimplement this.

2021-09-15 06:47 UTC, andela-hpopoola commented on server/services/transaction.service.js
> +      vendorId: model.vendorId,
This place is a little bit tricky, however, I think we need to confirm that `userId` exists first and use it here instead of vendorId (vendorId is not used by VAS).

```suggestion
      userId: model.userId,
```

For now, we might leave the propertyId and vendorId but will not make them required for now. When we get it right, maybe we will add another object and add all the related models, I am sure of the best solution for now. We need to think of a better way to make this work flawlessly. 

For `addedBy` and `updatedBy`, let's make them optional too. However, we need to use the Id of the user calling this service (if it is available).

2021-09-15 06:47 UTC, andela-hpopoola commented on server/services/transaction.service.js
>  export const addTransaction = async (transaction) => {
To manage expectations, please note that this function is called in 2 ways:

1. Manually - When an admin is resolving offline payment - `resolveOfflinePayment`
2. Automatically - When payment is made via Paystack - `addPaymentToTransaction`

So, lets put this into consideration when making our changes.

2021-09-15 06:47 UTC, andela-hpopoola commented on server/services/vasRequest.service.js
> +// eslint-disable-next-line import/no-cycle
[Tech Debt] To fix the `eslint-disable-next-line` issue in the future, we might need to create a custom file or function for all of the `getMODELById` so that they are not reimported into other files.

2021-09-15 20:20 UTC, andela-hpopoola requested changes
This looks good to me, thank you for working on this. Can you please add some transactions test for VAS (you can replicate some of the tests for offer transactions)?

Also, when getting all transactions, we want to be sure that the updated model loads the right aggregate for offer, property, vas, and vas request.

Lastly, let's not forget to look through the transaction service to be sure that we fix all the updates we made in the model.

Since I will be missing tomorrow's standup, after this, let's please focus on creating Part 4 to conclude the major work and add INITIAL_VAS to the database, Part 5 to fix the `propertyId` and `vendorId` tech debt so that we can accommodate other Ids in the future (like vasRequestId), I will need to work on Part 6 to integrate the updated model into Paystack integration.

Thank you.

2021-09-15 20:20 UTC, andela-hpopoola commented on server/models/transaction.model.js
> - *          vendorId:
Lets restore this for now and the one below.

2021-09-15 20:20 UTC, andela-hpopoola commented on server/services/transaction.service.js
> +  let offerTransactionParameters = {};
This is better as transaction parameters to ensure that it can be reused by other models.
```suggestion
let transactionParameters = {};
```

2021-09-15 20:20 UTC, andela-hpopoola commented on test/controllers/property.controller.test.js
> +        model: { id: offer._id, type: VALID_TRANSACTION_MODELS.OFFER },
Using `MODEL.OFFER` is better here to ensure consistency . Please update for other ones too.

```suggestion
model: { id: offer._id, type: MODELS.OFFER },
```

2021-09-16 00:53 UTC, tobieeniafe commented
@andela-hpopoola  So I came into a jam halfway while trying to add vasRequests to the `/transaction/all` endpoint. The current workflow (which is focused on only offers) is that, when a user visits the endpoint, all transactions made by the user are returned. Using the `userId`. And when it's a vendor, all transactions with the matching `vendorId` are returned.

Now in the case of vasRequests, the vendor can be the user in this case, ie trying to get all vasRequests they've paid for. Which would return zero as a vendor token would match with the `vendorid` key.

Now knowing we would be removing the `vendorId` key soon, this would mean that it's either vendors would not be able to see offer payments made by the user to them, or they wouldn't be able to view their vas requests. For now that is (still trying to figure out a work around for this tho)

2021-09-16 06:28 UTC, andela-hpopoola commented
> @andela-hpopoola So I came into a jam halfway while trying to add vasRequests to the /transaction/all endpoint. The current workflow (which is focused on only offers) is that, when a user visits the endpoint, all transactions made by the user are returned. Using the userId. And when it's a vendor, all transactions with the matching vendorId are returned.

Thank you for pointing this out. This actually doesn't look like a blocker. In the previous implementation, the vendor is not making any payments to us, so we are getting the payments the vendor is receiving via `vendorId`. Now, the vendor is making payment to us via VAS, so we should get the payments the vendor is making (via `userId`) and the one the vendor is  receiving (via `vendorId`)

> Now in the case of vasRequests, the vendor can be the user in this case, ie trying to get all vasRequests they've paid for. Which would return zero as a vendor token would match with the vendorid key.

The vendor doesn't need to be the user, we only need to get what they have paid and what the transaction they are expecting via vendorId and userId. When getting all transactions, we would get all transactions that matches where vendorId=`userId` or userId=`userId`. `userId` here refers to the user id of a vendor (or vendor Id).

> Now knowing we would be removing the vendorId key soon, this would mean that it's either vendors would not be able to see offer payments made by the user to them, or they wouldn't be able to view their vas requests. For now that is (still trying to figure out a work around for this tho)

Not sure what you mean by this and it looks like you are making the wrong assumption. We are not removing `vendorId` key soon, we are only refactoring it (the same way we refactored `offerId` but it might be a different implementation). If the `vendorId` is not needed, we won't add it in the first place. We are only refactoring the Ids that are not primarily involved in the transaction (like vendorId, propertyId, vasRequestId and other unforeseen Ids in the future).

The reason for refactoring this is to accommodate future updates when adding other model Ids to that transaction. For example, for transactions involving VAS, we might need to save the `vasRequestId`, but the `vendorId` and `propertyId` that were previously required are not needed in this case. The focus is to ensure that each transaction contains what is required for it and reducing the number of things that are not required.

I hope this clears the confusion. Please let me know if you need more information or have more questions.

2021-09-17 05:58 UTC, andela-hpopoola requested changes
Thank you for working on this. I left a few comments to ensure that we covered all edges cases for transactions, however, it looked like you missed some other parts too.

2021-09-17 05:58 UTC, andela-hpopoola commented on server/services/transaction.service.js
> -  if (user.role === USER_ROLE.VENDOR) {
I think we still need to match `vendorId` for vendors.

2021-09-17 05:58 UTC, andela-hpopoola commented on test/controllers/transaction.controller.test.js
> -    const vendor2Property = PropertyFactory.build({ addedBy: vendor2._id }, { generateId: true });
It looks like you totally removed the property transactions, can we add it back 🙏🏽

2021-09-17 17:56 UTC, andela-hpopoola approved these changes
Thank you for making the updates. I left a few comments on the tests, but this looks good overall.

2021-09-17 17:56 UTC, andela-hpopoola commented on test/controllers/transaction.controller.test.js
> +                expect(res.body.result[8].remittance.by).to.be.eql(
Remittance and its fields should be null for VAS_REQUESTS transactions. Can we confirm that they are null  or undefined instead of testing them against `vendorVasTransactions[0].remittance.by.toString()`.

Also, let's not forget to test for the amount and the userId.

2021-09-17 17:56 UTC, andela-hpopoola commented on server/services/transaction.service.js
> +      $lookup: {
Can we add another test to confirm that the new values are returned for single transaction for VAS_REQUESTS. That means we would have one test for OFFER transaction and another test for VAS_REQUESTS transaction.

2021-09-18 20:18 UTC, merged