#179637243 add optional ids to support new model type
Highrachy/ballers-api pull request #250
Opened 2021-09-20 21:34 UTC by tobieeniafe

#### What does this PR do?
Add optional ids to support new model type

#### Description of Task to be completed?
Add optional ids to support new model type

#### How should this be manually tested?
`npm run test`

#### What are the relevant pivotal tracker stories?
#179637243

2021-09-21 06:26 UTC, andela-hpopoola requested changes
Thank you for making the changes. I left an important comment on some future issues we might have with the current methodology. I hope we can fix that now instead of postponing it till later. Thank you.

2021-09-21 06:26 UTC, andela-hpopoola commented on server/models/transaction.model.js
> +      offerId: {
I noticed a type confusion pattern here which might give us additional issues in the future.

`vasId` and `offerId` are already part of `model.id` so it is causing unnecessary duplication here. If the the `model.type` is `OFFER` that means that we would need to set `model.id` to the `OFFER` Id and also set `offerId` to the `OFFER` Id. This might cause unnecessary confusion in the future if the value of both fields is different, as we would not be sure of the right one. 

The best fix in my own opinion is to remove `model.id` and use the `modelId` format to get the id. That way, if `model.type` is offer, we will use `offerId`, if it is `vasRequests`, we would use `vasRequestId`. This would prevent unnecessary duplication and future confusion.

The other fix would be to remove the `Id` of those we are certain correlates with transaction (for now VASRequest and Offer). However, the problem of this is that it could cause future issue for situations where we want to save the `offerId` and `vasRequestId` as the same time. We won't be able to do this with `model.id`.

2021-09-21 07:01 UTC, tobieeniafe commented on server/models/transaction.model.js
> +      offerId: {
I understand your concerns, but the `offerId` in this case, refers to the offer that could be gotten from a `vasRequest`.

2021-09-22 05:39 UTC, andela-hpopoola requested changes
Thank you for working on this. 

I have taken a deep look at this and I can confirm that we need to remove the `model.id` implementation to prevent any tight coupling of the model. Lets use the `modelId` format, e.g for `offer` we would use `offerId`, for property, we would use `propertyId`. The main Id will be recognized by the model.type.

This implementation can be done in this PR or a new PR.

Thank you.

2021-09-22 19:38 UTC, merged