#179637116 update offer status when new payment is made
Highrachy/ballers-api pull request #253
Opened 2021-09-23 16:53 UTC by tobieeniafe

#### What does this PR do?
Update offer status when new payment is made

#### Description of Task to be completed?
-Remove `assignedTo` from property model
-Delete `assignPropertyToUser` function

#### How should this be manually tested?
`npm run test`

#### What are the relevant pivotal tracker stories?
#179637116

2021-09-23 18:57 UTC, andela-hpopoola requested changes
Thank you for working on this. I left a few comments on updating the factory to reflect the current changes for consistency. Thank you.

2021-09-23 18:57 UTC, andela-hpopoola commented on server/services/offer.service.js
> +    // offer should be INTERESTED here
A gentle reminder to remove this comment in next commit.

2021-09-23 18:57 UTC, andela-hpopoola commented on test/controllers/enquiry.controller.test.js
> +      { addedBy: vendorUser._id, availableUnits: 4 },
Instead of including `availableUnits` here by default, I think it is better to update the property factory to cater for availableUnits (just as we have implemented the `generatedId` field). Something like this (emphasis on the `.after` part)

```js
export default new Factory()
  .option('generateId', false)
  .option('optionalFields', false)
  .after((property, options) => {
    const additionalOptions = {
      ...(options.generateId && { _id: mongoose.Types.ObjectId() }),
      ...(options.optionalFields && { availableUnits: property.units }),
    };
    return { ...additionalOptions, ...property };
  })
  .sequence('name', (i) => `${i} bedroom apartment`)
...

```

With the above implementation, by default,  when `optionalFields` is set to true (like we do for `generateId`), `availableUnits` will be equal to the default value of `units`. However, if available units is given by default, then that value will be used. 

PS: Even though the updates above might not reduce your typing, however, it ensures that the data we are using are consistent. The problem with your current implementation is that the default units in `property.factory.js` is `5` but you are setting it to `4` here; not sure if this is deliberate or a typo, however, newly created properties should have the same value for `availableUnits` and `units` unless we want to explicitly test for `availableUnits`.

2021-09-24 06:44 UTC, andela-hpopoola requested changes
**PROBLEM STATEMENT**

I noticed that the usage of `OFFER.STATUS` is not consistent with the statuses. This is mainly due to the fact that the statuses we have created are not properly defined. Here are some of the things I noticed:

1. OFFER_STATUS.RESOLVED` - This denotes that a user has completed payment for the property. I think it is better to update this to `COMPLETED_PAYMENT` instead of resolved to make it more explicit.

**Note:** I noticed that `OFFER_STATUS.RESOLVED` is missing in most of the checks we have done. Let's review this and include it where necessary.

2. Some of the places we are comparing multiple statuses seem to be missing one statuses. Also, some statuses are used without being defined. To fix this, lets create custom functions to ensure that the right statuses are used.

1. propertyIsOwnedByUser - Status is ASSIGNED, ALLOCATED OR COMPLETED_PAYMENT 
2. isValidPortfolio - Status is  INTERESTED, ASSIGNED, ALLOCATED OR COMPLETED_PAYMENT
3. isPendingOffers - Status is GENERATED, PENDING_ADMIN_APPROVAL, PENDING_VENDOR_REVIEW, REACTIVATED
4. offerHasBeenTerminated - Status is CANCELLED or EXPIRED

**Todo:** 
- We need a cron job to set the status of expired Offers to `EXPIRED`.
- We need to remove the following offer statuses -  `OFFER_STATUS.NEGLECTED` and `OFFER_STATUS.REJECTED`. OFFER_STATUS.NEGLECTED is used in `acceptOffer` service but it is not defined in OFFER_STATUS.

From the above, here is the breakdown of the analyzed `OFFER_STATUS` :

```js
export const OFFER_STATUS = {
  GENERATED: 'Generated', // Offer has been created by vendor
  INTERESTED: 'Interested', // Offer has been signed by the user, no payment has been made yet
  ASSIGNED: 'Assigned', //  A minimum of first Payment has been made on the Offer
  ALLOCATED: 'Allocated', // User has reached the allocated threshold
  REJECTED: 'Rejected', // maybe we should remove this
  REACTIVATED: 'Reactivated', // Same as Generated, just an updated offer
  CANCELLED: 'Cancelled', // Vendor cancels the offer, e.g when a user is no longer interested (need to think of how to refund)
  RESOLVED: 'Resolved', // should be updated to COMPLETED_PAYMENT
  PENDING_ADMIN_APPROVAL: 'Pending Admin Approval',
  PENDING_VENDOR_REVIEW: 'Pending Vendor Review',
  EXPIRED: 'Expired' // Newly added for automatically expired offers
};
```

2021-09-24 06:44 UTC, andela-hpopoola commented on server/services/totalCount.service.js
> +    propertyMatchObject = { userId: user._id, status: OFFER_STATUS.ALLOCATED };
I think this should be a match for 
- `OFFER_STATUS.ASSIGNED` - user has made at least 1 payment
-  `OFFER_STATUS.ALLOCATED`- user has reached the allocated threshold set by vendor
-  `OFFER_STATUS.RESOLVED` - user has completed payment for the property. We might need to update this to `COMPLETED_PAYMENT` instead of resolved to make it more explicit.

**Note:** I noticed that `OFFER_STATUS.RESOLVED` is missing in most of the checks we have done. Lets review this and include it where necessary.

Also, it makes more sense if we can write functions that explains what they do -

1. OwnedProperty - Status is ASSIGNED, ALLOCATED OR COMPLETED_PAYMENT 
2. ValidPortfolio - Status is  INTERESTED, ASSIGNED, ALLOCATED OR COMPLETED_PAYMENT
3. PendingOffers - Status is GENERATED, PENDING_ADMIN_APPROVAL, PENDING_VENDOR_REVIEW
4. InvalidOffers - Status is CANCELLED or EXPIRED

**Todo:** 
- We need a cron job to set the status of expired Offers to `EXPIRED`.
- We need to remove the following offer statuses -  `OFFER_STATUS.NEGLECTED` and `OFFER_STATUS.REJECTED`. OFFER_STATUS.NEGLECTED is used in `acceptOffer` service but it is not defined in OFFER_STATUS.

From the above, here is the breakdown of the analyzed `OFFER_STATUS` :

```js
export const OFFER_STATUS = {
  GENERATED: 'Generated', // Offer has been created by vendor
  INTERESTED: 'Interested', // Offer has been signed by the user, no payment has been made yet
  ASSIGNED: 'Assigned', //  A minimum of first Payment has been made on the Offer
  ALLOCATED: 'Allocated', // User has reached the allocated threshold
  REJECTED: 'Rejected', // maybe we should remove this
  REACTIVATED: 'Reactivated', // Same as Generated, just an updated offer
  CANCELLED: 'Cancelled', // Vendor cancels the offer, e.g when a user is no longer interested (need to think of how to refund)
  RESOLVED: 'Resolved', // should be updated to COMPLETED_PAYMENT
  PENDING_ADMIN_APPROVAL: 'Pending Admin Approval',
  PENDING_VENDOR_REVIEW: 'Pending Vendor Review',
  EXPIRED: 'Expired' // Newly added for automatically expired offers
};
```

2021-09-28 19:26 UTC, andela-hpopoola requested changes
Thank you for working on this. I left a few comments on ensuring that this is properly implemented. Lets not forget to add the following implementation in the next PRs:

1. Updating OFFER STATUS in all cases where necessary. We should have endpoints that cover all OFFER STATUSES that we have defined.
2. Ensuring that we create a reminder endpoint before an offer expires (maybe 2 days before expiry - we need to confirm from Namo). A similar implementation is used for Offer reminders.

Thank you.

2021-09-28 19:26 UTC, andela-hpopoola commented on server/services/offer.service.js
> +  await Promise.all(
Let's not forget to send emails, notifications (and maybe Slack notifications in the next PR) to the users and vendors with expired offers.

2021-09-28 23:13 UTC, tobieeniafe commented on server/helpers/constants.js
> +  { status: OFFER_STATUS.GENERATED },
`OFFER_STATUS.REACTIVATED` is the status given to an offer that expired, but was reactivated and a new offer generated from it. So I don't belive it should be a pending offer.

2021-09-28 23:16 UTC, tobieeniafe commented on server/helpers/constants.js
>  export const ACTIVE_PORTFOLIO_OFFER = [
`VALID_PORTFOLIO_OFFER` contains ` OFFER_STATUS.COMPLETED_PAYMENT` which means the offer has been completed and can no longer be referred to as active.

2021-09-29 07:41 UTC, andela-hpopoola requested changes
Thank you for working on this. Let's try to resist the urge to add more functionality to this PR, lets try to conclude this by fixing relevant comments now, adding necessary tests and fixing other functionalities in a different PR. Thank you.

2021-09-29 07:41 UTC, andela-hpopoola commented on server/services/transaction.service.js
> +    await assignOffer(model._id);
We need to add tests for this.

2021-09-29 07:41 UTC, andela-hpopoola commented on server/helpers/constants.js
>  export const ACTIVE_PORTFOLIO_OFFER = [
I am not sure of your definition of `active` but looking at the codebase and where the `ACTIVE_PORTFOLIO_OFFER` constant is used, I think it should contain `OFFER_STATUS.COMPLETED_PAYMENT`.

https://github.com/Highrachy/ballers-api/blob/501f98f42ef9ec1ec9b5c95e3b490f49612a1ef0/server/services/transaction.service.js#L283

If you don't add `OFFER_STATUS.COMPLETED_PAYMENT` here or change the implementation, then the person that has a contribution reward of `40 million`, will now have a contribution reward of `0 Naira` after he has completed payment.

2021-09-29 07:41 UTC, andela-hpopoola commented on server/helpers/constants.js
> +  { status: OFFER_STATUS.GENERATED },
`OFFER_STATUS.REACTIVATED` is the same as `OFFER_STATUS.GENERATED` but with the explanation you have given.

> OFFER_STATUS.REACTIVATED is the status given to an offer that expired, but was reactivated and a new offer generated from it. So I don't belive it should be a pending offer.


The only reason we used `OFFER_STATUS.REACTIVATED` is to differentiate it from `OFFER_STATUS.REACTIVATED`. 

`PENDING_OFFER` should contain offers that have not been signed by the user but are active, so `REACTIVATED` falls under this category too.

2021-09-29 07:41 UTC, andela-hpopoola commented on server/controllers/offer.controllers.js
> +        const message = `${pluralizeCount(offers.length, 'offer')} ${pluralize(
```suggestion
        const message = `${pluralizeCount(offers.length, 'offer has', 'offers have')}
```

2021-09-29 07:41 UTC, andela-hpopoola commented on server/services/offer.service.js
> +    return await Offer.findByIdAndUpdate(
Before we assign the property here, I think it makes sense to check if the offer is a `PENDING_OFFER`. Not sure if this has been done.

2021-09-29 07:50 UTC, andela-hpopoola commented on server/helpers/constants.js
> +  { status: OFFER_STATUS.GENERATED },
```
// REACTIVATED: 'Reactivated', // Same as Expired, just informing us that a new offer was created from this.
```

2021-09-30 07:22 UTC, andela-hpopoola approved these changes
Thank you for working on this. I left a few more comments on removing the OfferStatus allocation to enable us to write a better service to cater for this. I am approving this PR now as it is already a mess and very difficult to review. In the future, when the number of edited files exceeds 5 files (without tests), let's start thinking of breaking it down into multiple PR and sticking to one functionality (with discretion).

Here is the collection of the pending stuffs from this PR:

1. offer reminder - add in-app, sms, slack, email notifications
2. revisit cancel offer endpoint (remove enquiry set to false)
3. update available units when a property `units` is updated
4. consolidate assignOffer service to cater for completed payment, allocated, and assigned
5. confirm that `getAllUserOffers` service is still needed(differentiate from get all offers)

2021-09-30 07:22 UTC, andela-hpopoola commented on server/helpers/filters.js
> +  availableUnits: { type: FILTER_TYPE.INTEGER },
I am unresolving this as some tests are still missing that we need to confirm that available unit is returned as expected. The fastest way to add this is to update the `expectResponseToContainNecessaryPropertyData` test function to include availableUnits as a 3rd parameter. If is is given we will use the given value, else we will use the `units`.

2021-10-01 09:58 UTC, merged