#174250315 add payment plan
Highrachy/ballers-api pull request #33
Opened 2020-08-21 05:53 UTC by tobieeniafe

#### What does this PR do?
Add payment plan endpoints

#### Description of Task to be completed?
add endpoints for admin to create, view and delete payment plans

#### How should this be manually tested?
`POST /api/v1/payment/add`
`{
  "planName": "monthly",
  "planDescription": "monthly payment plan",
  "paymentFrequency": "once a month"
}`
`GET /api/v1/payment/all`
`DELETE /api/v1/payment/delete/:id`

#### What are the relevant pivotal tracker stories?
#174250315

2020-08-21 06:14 UTC, andela-hpopoola requested changes
Thank you for working on this. 

Can you integrate the payment plan model into the property model so that when properties are loaded via any of the property endpoint, the payment plan is also returned among the property details. This is the most important reason why this is important in the added to MVP. Thank you.

2020-08-21 06:14 UTC, andela-hpopoola commented on server/controllers/paymentPlan.controllers.js
> +  delete(req, res, next) {
🤔 . This is a dicey situation. We should be careful with the delete feature with everything that deals with money. The delete endpoint for the payment plan should only delete the payment plan if it is not used by any property. A deleted payment plan in use will result in a bug if the property is retrieved.

2020-08-21 06:14 UTC, andela-hpopoola commented on server/models/paymentPlan.model.js
> +    paymentFrequency: {
This should be a number that denotes month. It will be difficult to automate calculations from payment plans if this is a string.

2020-08-21 06:14 UTC, andela-hpopoola commented on server/models/paymentPlan.model.js
> +    planName: {
We could as well use name here (the plan prefix is not necessary, I notice that you do that for most of your naming convention). 

This will make the code more readable, something like `paymentPlan.name` seems better than `paymentPlan.planName`.

2020-08-21 06:14 UTC, andela-hpopoola commented on server/routes/index.js
> +import payment from './paymentPlan.routes';
Lets be explicit with paymentPlan as we don't want a mix up with the payment and transaction model.

```suggestion
import paymentPlan from './paymentPlan.routes';
```

2020-08-21 06:14 UTC, andela-hpopoola commented on server/routes/index.js
> +  app.use('/api/v1/payment', payment);
```suggestion
  app.use('/api/v1/payment-plan', paymentPlan);
```

2020-08-21 06:14 UTC, andela-hpopoola commented on server/routes/paymentPlan.routes.js
> +import addPlanSchema from '../schemas/paymentPlan.schema';
`addPlanSchema` is not explicit enough. The codebase is getting bigger, it is easier to mix things up now.
```suggestion
import addPaymentPlanSchema from '../schemas/paymentPlan.schema';
```

2020-08-21 06:14 UTC, andela-hpopoola commented on server/routes/paymentPlan.routes.js
> + * /payment/add:
Please fix for other endpoints too.
```suggestion
 * /payment-plan/add:
```

2020-08-21 06:14 UTC, andela-hpopoola commented on server/routes/paymentPlan.routes.js
> +
We should have an endpoint to edit payment plans. Editing is important for fixing typos in plan name and making the description more descriptive.

However, the frequency field should not be updated since updating this will affect all the previously calculated price made with this payment plans.

2020-08-25 06:36 UTC, andela-hpopoola requested changes
Thank you for working on this. I believe the implementation can be improved to make the endpoint more effective.

2020-08-25 06:36 UTC, andela-hpopoola commented on server/models/property.model.js
> +    paymentPlan: {
PaymentPlan should be an array of ObjectId. 
(If you study the mockup - you will notice that we have multiple payment plans.)

Your implementation is different from the concept in the mockup 😏  

In the mockup, you need to study all the places the payment plan is used, you will notice that it is returned with the property information.

1. Single Portfolio Page
 This means that the returned result for the `/property/:id` endpoint need to return the names of the payment plan.

<img width="798" alt="Screenshot 2020-08-25 at 07 13 04" src="https://user-images.githubusercontent.com/26963369/91130324-606c7600-e6a3-11ea-8f49-be5e4c9ebebe.png">


2. List of all Properties contains payment plan. We need to ensure that the payment plan is aggregated in all property endpoint so that it is returned as part of the property information.

See another instance here:
<img width="652" alt="Screenshot 2020-08-25 at 07 23 28" src="https://user-images.githubusercontent.com/26963369/91130698-f1435180-e6a3-11ea-9cbc-cbc4db3f3f09.png">

To save time and energy, lets ensure we return the aggregated payment plan for all property endpoints.

2020-08-25 06:36 UTC, andela-hpopoola commented on server/controllers/paymentPlan.controllers.js
> +  assignPaymentPlan(req, res, next) {
This is a great implementation, however, it will cause the user and application bad user experience. I believe payment plans should be added when the user (developer/admin) is adding a new property (not assigned individually). This will be implemented via a multiple Select field in the frontend so that the user can add and edit payment plans at ease.

A better implementation will be to remove this method and add payment plans to add property/update property implementation. The ids of the payment plan are saved in the property model as an array. If you are curious about the multi select, here is a link to the one I used in the application https://react-select.com/home (I am referring to the 2nd example for multiple select field)

I hope you understand, please free to follow up with me if this is unclear or you have a much better implementation in mind.

2020-08-25 20:35 UTC, tobieeniafe commented on server/models/paymentPlan.model.js
> +    propertiesAssignedTo: {
this is to kow is a payment plan is linked to a property, to prevent it from being deleted

2020-08-25 21:12 UTC, andela-hpopoola commented on server/models/paymentPlan.model.js
> +    propertiesAssignedTo: {
I understand your point but this is an extra overhead over the payment plan and it is not necessary(as we will need to add an extra query to add the properties to the payment plan). This is extra work as we will need to keep track of the payment plans in the property model and also keep track of the payment plan model at the same time. If the payment plan field in the property is added, we must add the property field too in the payment plan model. This also applies to when a property is updated and deleted. This will be extra code and extra work (it doesn't worth the stress, abeg)

Moreover, we can know if a payment plan is linked to a property by querying the properties since the payment plan is saved in the property model too. 🤷‍♂️

2020-08-25 23:20 UTC, tobieeniafe commented on server/models/paymentPlan.model.js
> +    propertiesAssignedTo: {
`hasBeenAssignedToProperty` `true` ?🤔

2020-08-26 06:44 UTC, andela-hpopoola commented on server/models/paymentPlan.model.js
> +    propertiesAssignedTo: {
The reason why querying the property model is the best approach is because it will only be done when the admin is deleting. The problem with this are:
1. You will need to write an additional query to update the payment plan `hasBeenAssignedToProperty` field to true every time a new property is added. 
2. We are not assigning payment plans one by one via an endpoint. You will need to remove the assignment endpoint, We are assigning payment plans is multiples -- An admin can assign 4 to 5 payment plan at the same time when he is adding a new property (remember the multi-select field in my earlier comment), that means we will make 4 to 5 queries to update the respective payment plan `hasBeenAssignedToProperty`.
3. Every time a property is updated, we need to check that the payment plan has not been updated because if it has been updated (i.e a payment plan has been removed, and another one has been added) we will need to check if the removed property is the only property with the payment plan and use that to update the value of `hasBeenAssignedToProperty`.

I am actually being considerate by telling you to remove this. However, if you think adding the `asBeenAssignedToProperty` field approach is better, my only plead is for you to write tests to at least simulate my points 2 and 3 so that we are certain that we cover all the edge cases.

2020-08-29 13:55 UTC, andela-hpopoola approved these changes
Thank you for working on this. I left a few non blocking comments. Feel to free to merge it after fixing them.

2020-08-29 13:55 UTC, andela-hpopoola commented on server/schemas/paymentPlan.schema.js
> +export const assignPaymentPlanSchema = Joi.object({
Can we remove this, not sure we need it or what do you think?

2020-08-29 13:55 UTC, andela-hpopoola commented on server/services/paymentPlan.service.js
> +      'Cannot delete payment plan with properties assigned',
Not too important but necessary for User Experience, I believe that the error message will be more informative if we return the name of the properties (as an array) the payment plan is currently assigned to. It will make it easier to locate the property and update it.

2020-08-29 13:55 UTC, andela-hpopoola commented on server/services/paymentPlan.service.js
> +      'Cannot delete payment plan with properties assigned',
It is advisable to make the error message more descriptive. Let's add the number of properties it is assigned to. Please use `property` for 1 property and plural form for more than one property in the updated error message as shown below:

```suggestion
      `Payment plan cannot be deleted as it is currently assigned to 2 properties`,
```

2020-08-30 23:11 UTC, tobieeniafe commented on server/services/paymentPlan.service.js
> +      'Cannot delete payment plan with properties assigned',
any suggestion on how to implement this?

2020-08-31 18:42 UTC, merged