#174250297 add transaction model
Highrachy/ballers-api pull request #36
Opened 2020-08-27 00:25 UTC by tobieeniafe

#### What does this PR do?
Add transaction model and endpoint

#### Description of Task to be completed?
Create transaction model and endpoint to record transactions

#### How should this be manually tested?
`GET /api/v1/transaction/all`
`POST /api/v1/transaction/add`

#### What are the relevant pivotal tracker stories?
#174250297

2020-08-27 08:03 UTC, andela-hpopoola requested changes
Thank you for working on this. This looks good and the implementation makes sense. I left a few comments, but I will test it properly later in the day (after work).

2020-08-27 20:10 UTC, tobieeniafe commented on server/controllers/transaction.controllers.js
> +    if (newTransaction.userId) {
the `userId` isn't compulsory so that the endpoint could be used to create online(user initiated) and offline(admin initiated) transactions

2020-08-27 20:22 UTC, andela-hpopoola commented on server/controllers/transaction.controllers.js
> +    if (newTransaction.userId) {
The userId should actually be compulsory. Let me explain
1. If the user makes an online payment, we will use the userId to know the user that made the payment. Since it is an online payment, we dont need the adminId.

2. For offline payments, the admin need to select the user that has made the payment into his account. Without the userId, there will be no way to query the total transaction (online and offline) made by the user. The admin Id is only compulsory because if there are discrepancies with any offline payment, the adminId can be used to trace the problem.

2020-08-27 20:34 UTC, tobieeniafe commented on server/controllers/transaction.controllers.js
> +    if (newTransaction.userId) {
the intended idea here is, if `userId` isn't sent it automatically uses the id in the user token as the `userId` handling it as an online payment. And if `userId` is present, it uses the id in the token as the `adminid`

2020-08-27 22:36 UTC, andela-hpopoola commented on server/controllers/transaction.controllers.js
> +    if (newTransaction.userId) {
It is not recommended to use the userId in token since this used by the admin and user. We don't want to mistakenly save the admin Id as userId. UserId is the most important field here so it should be required from Joi schema.

If the userId is not returned for whatever reason, it is safer to throw an error than saving the transaction or manipulating the user Id.

2020-08-29 13:21 UTC, andela-hpopoola requested changes
Thank you for working on this. I just had the opportunity to test it and it works great. Left a few comments on improving the code and tests to reduce future bugs. Thank you.

2020-08-29 13:21 UTC, andela-hpopoola commented on test/controllers/transaction.controller.test.js
> +            // expect(res.body.transactions[0].userInfo._id).to.be.eql(_id.toString());
This is a very important test, so I was forced to look into it.

The test was failing because adminId was missing in the transaction. Adding adminId to line 139 fixes the test.

2020-08-29 13:21 UTC, andela-hpopoola commented on test/controllers/transaction.controller.test.js
> +            // expect(res.body.transactions[0].userInfo._id).to.be.eql(_id.toString());
However, we need to test that the second one with no admin Id passes too. This is important because we want the code to return the Paystack record we have saved too and these records will have no admin Id. 

Hence, we need to ensure that line 161 remains like this 
```
await addTransaction(TransactionFactory.build());
``` 

and ensure we update the transaction aggregage to return for fields with no adminId. 

I found this, not sure if it will help 
https://stackoverflow.com/questions/48354575/mongodb-mongoose-make-aggregate-lookup-as-optional

**Very Important** 
You might need to look at other models and ensure that the aggregate function used in the code doesn't omit any field when joined. Lets ensure that this bug doesn't exist please.

Thank you.

2020-09-01 07:37 UTC, andela-hpopoola requested changes
Thank you for working on this. I added more comments on adding more endpoints to make it easier and secured to get transaction information for the admin and user.

2020-09-01 07:37 UTC, andela-hpopoola commented on server/models/transaction.model.js
> +    paidOn: {
This should be required. It is important to set the date the payment is paid when the admin inputs the payment details.

2020-09-01 07:37 UTC, andela-hpopoola commented on server/controllers/transaction.controllers.js
> +  getUserTransactionsByPropertyAndUser(req, res, next) {
I think your current implementation of this comment is just one out of the multiple endpoint that should be created. We cannot use this to generate all transaction details for a user.

https://github.com/Highrachy/ballers-api/pull/36/files#r479644834

An easier way to get a user transaction is to create a single endpoint where the userId is gotten from the token and returns all the payments with the userId but grouped by propertyId. You can take it further by using the database to calculate the sum of returned values.

For the admin, we need another endpoint to get all the payments made for a property via the propertyId. This will get all the payments and user info to enable the admin to know all the payments made to him/her at a glance.

The last part is the one you have implemented, which enables the admin to getUserTransactions By Property Id. We need to protect it with the admin authentication middleware and ensure that the admin is the owner of the property he is viewing. We don't want to make random people see other people transactions.

Not sure if I make any sense, I will try to explain better during standup.

2020-09-01 07:37 UTC, andela-hpopoola commented on test/controllers/transaction.controller.test.js
> +  context('with invalid ttransaction', () => {
Typo:
```suggestion
  context('with invalid transaction', () => {
```

2020-09-01 21:43 UTC, andela-hpopoola commented on server/routes/transaction.routes.js
> +  getTransactionsBypropertySchema,
```suggestion
  getTransactionsByPropertySchema,
```

2020-09-01 21:51 UTC, andela-hpopoola reviewed
I did a quick look and this looks good. I will test it on my system tomorrow morning.

2020-09-01 21:51 UTC, andela-hpopoola commented on server/routes/transaction.routes.js
> + * /transaction/personal:
```suggestion
 * /transaction/user:
```

2020-09-01 21:51 UTC, andela-hpopoola commented on test/controllers/transaction.controller.test.js
> +            expect(res.body.transactions[0].propertyInfo._id).to.be.eql(propertyId.toString());
I think it is a better idea to test at least the property name and property image are returned via this endpoint.

2020-09-01 21:51 UTC, andela-hpopoola commented on test/controllers/transaction.controller.test.js
> +            expect(res.body.transactions[0]._id).to.be.eql(transactionId.toString());
I think it is a better idea to test for other transaction fields here (remember that omitting this type of test introduced the main image bug)

2020-09-01 21:51 UTC, andela-hpopoola commented on test/controllers/transaction.controller.test.js
> +    context('with a valid token & id', async () => {
Can you please add another test for an empty `adminId` so that we are sure this works when used with Paystack services.

2020-09-02 07:08 UTC, andela-hpopoola approved these changes
Thank you for working on this. I left a  comment on replacing the transaction details endpoint with transaction properties to make it more meaningful. It is actually a blocking comment, but I trust you will fix it right.

Feel free to merge after you have made these changes. Thank you.

2020-09-02 07:08 UTC, andela-hpopoola commented on server/routes/transaction.routes.js
> + * /transaction/details:
This is not getting the transaction, rather it is getting all transactions for a given property. Imho, I feel this is better as a get request and the endpoint can be updated to reflect that it is for property. 

In the nearest future, we will need to create a transaction details endpoint that gets the transaction details of a single transaction based on the transaction Id.

```suggestion
 * /transaction/property/:propertyId:
```

2020-09-02 18:12 UTC, merged