#174250401 add offer letter routes
Highrachy/ballers-api pull request #40
Opened 2020-09-06 16:32 UTC by tobieeniafe

#### What does this PR do?
Add offer letter routes

#### Description of Task to be completed?
add routes for creating, accepting, assigning and viewing offers

#### How should this be manually tested?
`POST /api/v1/offer/create`
`PUT /api/v1/offer/respond`
`PUT /api/v1/offer/assign`
`GET /api/v1/offer/all`
`GET /api/v1/offer/:id`

#### What are the relevant pivotal tracker stories?
#174250401

2020-09-06 18:29 UTC, andela-hpopoola requested changes

2020-09-08 06:41 UTC, andela-hpopoola requested changes
Thank you for working on this. This is taking the right shape. Here are the next things I think you might be missing:

1. Get Active User Portfolio: Get all offers that DOESN'T have the REJECTED and NEGLECTED
<img width="766" alt="Screenshot 2020-09-08 at 07 31 03" src="https://user-images.githubusercontent.com/26963369/92441118-84e94780-f1a5-11ea-8634-e8d5663d80f9.png">

2. Update the schema from OfferLetter to Offer. This is necessary because the model has more functionality than using it to generate offer letters only. It might not look like a big deal but this can make the model confusing when we start adding more functionality. Don't forget to change all offerLetter.**.js file to offer.**.js file.

Thank you.

2020-09-08 06:41 UTC, andela-hpopoola commented on mailer/index.js
> +  OFFER_RESPONSE: {
Can you add the current subject and content to the email template slide to serve as placeholder while you follow up with Namo on getting the right content.
https://docs.google.com/presentation/d/1l9XZHtV9-uFomT5bjZF5AAcE7pcOq8WrHmFUvHOdSjc/edit#slide=id.p

2020-09-08 06:41 UTC, andela-hpopoola commented on server/controllers/offerLetter.controllers.js
> +        res.status(httpStatus.CREATED).json({ success: true, message: 'Offer created', offer });
We need to send a mail to the user too here.

This mail will inform them that they have an offer letter waiting for them to be signed. It should also include the expiry date of the offer letter.

2020-09-08 06:41 UTC, andela-hpopoola commented on server/helpers/constants.js
> +export const USER_ROLE = {
🙌

2020-09-08 06:41 UTC, andela-hpopoola commented on server/models/offerLetter.model.js
> + *           status: interested
Can we update this to the right casing -- 'Interested'. Not sure if this might throw an error since it is not in the right case.

2020-09-08 06:41 UTC, andela-hpopoola commented on server/models/offerLetter.model.js
> +      default: 'Generated',
```suggestion
      default: OFFER_STATUS.GENERATED,
```

2020-09-08 06:41 UTC, andela-hpopoola commented on server/routes/index.js
> +  app.use('/api/v1/offer-letter', offerLetter);
No, I mean we should change all instances of offer-letter to offer. Let me explain better:

A vendor will create an offer for a user that is interested in a property. The user will accept the offer via the offer letter. We will get the user's offer from the offer model and so on and so forth...

Lets update all OfferLetter filename to offer and the routes to offer 🙏

2020-09-08 06:41 UTC, andela-hpopoola commented on server/schemas/offerLetter.schema.js
> +  allocationInPercentage: Joi.number().label('Allocation In Percentage').required(),
Gentle reminder to use Joi's min and max here to ensure the number is valid percentage between 1 - 100.

2020-09-08 06:41 UTC, andela-hpopoola commented on server/models/offerLetter.model.js
> + *      OfferLetter:
Lets change this to Offer to make it more explicit, please. The offer Letter will be generated from the offer model.

2020-09-08 06:41 UTC, andela-hpopoola commented on server/models/offerLetter.model.js
> +const OfferLetterSchema = new mongoose.Schema(
```suggestion
const OfferSchema = new mongoose.Schema(
```

2020-09-08 06:41 UTC, andela-hpopoola commented on server/models/offerLetter.model.js
> +const OfferLetter = mongoose.model('OfferLetter', OfferLetterSchema);
```suggestion
const Offer = mongoose.model('Offer', OfferSchema);
```

2020-09-09 07:11 UTC, andela-hpopoola requested changes
Thank you for working on this. I went through your most recent changes and it seems there are still lots of things to be done. I will watch out for the next commit and review it again accordingly.

2020-09-10 08:09 UTC, andela-hpopoola reviewed
Need to jump off now to start my engagement. I will review this properly later in the day. Thank you and nice work.

2020-09-10 08:09 UTC, andela-hpopoola commented on server/controllers/offer.controllers.js
> +        const contentBottom = `Dear ${user.firstName}, ${offer.vendorInfo.lastName} ${
I am sure we are not using the Vendor last name / first Name as a content to be sent to the user. Can you replace this with Ballers/Highrachy?

2020-09-10 18:50 UTC, andela-hpopoola requested changes
Thank you for working on this. I left a few comments on this but I am mostly concerned about the reference code generation (We could do that in a later PR to save time). 

Also, is it the whole controller test that is failing? You didn't leave a comment so I am not sure why you commented them out.

2020-09-10 18:50 UTC, andela-hpopoola commented on server/controllers/offer.controllers.js
> +        const contentBottom = `Dear ${vendor.firstName}, your offer on ${offer[0].propertyInfo.name} has been accepted. Check your dashboard for more details.`;
Can you update this too, please?

2020-09-10 18:50 UTC, andela-hpopoola commented on server/models/offer.model.js
> + *           userId: 5f2b39035a086cfc4b7fa7f6
Even though this doesn't really count, the example would make more sense to use a slightly different id for the userId, vendorId, and other Ids.

2020-09-10 18:50 UTC, andela-hpopoola commented on server/models/offer.model.js
> +    deliveryState: {
Can you add the reference code we discussed via mail to the model too?

2020-09-10 18:50 UTC, andela-hpopoola commented on server/services/offer.service.js
> +    const newOffer = await new Offer(offer).save();
Dont forget to generate the reference code here, so that it can be saved in the db.

2020-09-10 18:50 UTC, andela-hpopoola commented on test/services/offer.service.test.js
> +    const offer1 = OfferFactory.build({
Instead of repeating the same fields in the new objects, you can create the fields in an object and spread out the object in each new fields.

```js
const offerDetails = { userId, enquiryId, propertyId, vendorId: userId };
const offer1 = OfferFactory.build({ ...offerDetails, status: OFFER_STATUS.ASSIGNED });
...
```

2020-09-10 18:57 UTC, tobieeniafe commented
> Thank you for working on this. I left a few comments on this but I am mostly concerned about the reference code generation (We could do that in a later PR to save time).
> 
> Also, is it the whole controller test that is failing? You didn't leave a comment so I am not sure why you commented them out.

the tests only fail when the offer controller tests run

2020-09-12 12:46 UTC, andela-hpopoola commented on server/routes/offer.routes.js
> +router.get('/all', authenticate, OfferController.getAll);
It looks like this gets all the offers for a single user. Can we update the route so that it is more explicit.

```suggestion
router.get('/user/all', authenticate, OfferController.getAll);
```

Can we also create an equivalent route for an admin?

2020-09-12 12:46 UTC, andela-hpopoola commented on server/routes/offer.routes.js
> + *     description: Get all offers
```suggestion
 *     description: Get active offers
```

2020-09-12 12:46 UTC, andela-hpopoola commented on server/services/offer.service.js
> +    await Offer.findByIdAndUpdate(
Can you check the expiry date of the offer before updating? Users should be unable to accept an expired offer.

2020-09-12 16:29 UTC, tobieeniafe commented on server/routes/offer.routes.js
> +router.get('/all', authenticate, OfferController.getAll);
this gets all the offers for a user based on their `userId`.

2020-09-12 18:06 UTC, andela-hpopoola commented on test/controllers/offer.controller.test.js
> +// beforeEach(async () => {
I believe this is the culprit. It is adding property and enquiry before all the tests are ran.
Can you try enclosing it in a describe block.

i.e Copy everything from line 28 to the end of the file and wrap them in a describe block
```js
describe('Offer Controller', () => {
  beforeEach(async () => {
    adminToken = await addUser(adminUser);
    userToken = await addUser(regualarUser);
    await addProperty(property);
    await addEnquiry(enquiry);
  });

  describe('Create Offer Route', () => {
  ...
})
```

2020-09-14 19:44 UTC, andela-hpopoola requested changes
Nice work with the test and implementation. This looks good from the code review point of view. I need to test in on my machine before approving.

Also, I would recommend you pay more attention to typographical errors. If you are unsure of any spelling, feel free to check the right spelling from Google or a dictionary. Avoiding typographical is a great way of preventing silly bugs that would be so difficult to debug.

2020-09-14 19:44 UTC, andela-hpopoola commented on server/controllers/offer.controllers.js
> +  getAllUser(req, res, next) {
```suggestion
  getAllUserOffers(req, res, next) {
```

2020-09-14 19:44 UTC, andela-hpopoola commented on server/controllers/offer.controllers.js
> +  getAllAdmin(req, res, next) {
```suggestion
  getAllAdminOffers(req, res, next) {
```

2020-09-14 19:44 UTC, andela-hpopoola commented on server/services/offer.service.js
>      const offerInfo = await getOffer(newOffer._id);
I still believe you dont need to make this additional call since you have all the needed information from newOffer and enquiry

2020-09-14 19:44 UTC, andela-hpopoola commented on server/services/offer.service.js
> +  if (Date.now() > expiryDate) {
It would be more preferable to install and use a package to manage Date. Something like date_fns would come in handy.

2020-09-14 19:44 UTC, andela-hpopoola commented on test/controllers/offer.controller.test.js
> +const regualarUser = UserFactory.build({ _id: userId, role: 1, activated: true });
Typo:
```suggestion
const regularUser = UserFactory.build({ _id: userId, role: 1, activated: true });
```

2020-09-14 19:44 UTC, andela-hpopoola commented on test/controllers/offer.controller.test.js
> +describe('Offer Routes', () => {
The test is for Controllers not Routes
```suggestion
describe('Offer Controller', () => {
```

2020-09-14 19:44 UTC, andela-hpopoola commented on test/controllers/offer.controller.test.js
> +            expect(res.body.offer).to.have.property('vendorInfo');
I have complained about this several times that it is not proper to test via `.have.property` if you can test for the exact value. This can be misleading as the value can have the property but the property can be null which is not the expected outcome (yet the test will pass). 

I hope this doesn't cause an unnecessary error when the app makes it production. I will disassociate myself from such bug.

2020-09-14 19:44 UTC, andela-hpopoola commented on test/controllers/offer.controller.test.js
> +    context('when user token is used', () => {
Since you are deleting the token, I feel it is better to explicitly state that an invalid token is used here
```suggestion
    context('when an invalid token is used', () => {
```

2020-09-14 19:44 UTC, andela-hpopoola commented on test/controllers/offer.controller.test.js
> +      context('when allocation in percentage is empty', () => {
It also makes sense to add test to ensure that this falls within 1 - 100 .i.e try adding a number less than 1, and another test with a number greater than 100.

2020-09-14 19:44 UTC, andela-hpopoola commented on test/controllers/offer.controller.test.js
> +      context('when expires is empty', () => {
```suggestion
      context('when expiry date is empty', () => {
```

2020-09-14 19:44 UTC, andela-hpopoola commented on test/controllers/offer.controller.test.js
> +              expect(res.body.error).to.be.eql('"Expires" must be a valid date');
Can we change this to reflect an easier to understand sentence. Please update the schema as well.
```suggestion
              expect(res.body.error).to.be.eql('"Expiry Date" must be a valid date');
```

2020-09-14 23:43 UTC, tobieeniafe commented on server/services/offer.service.js
>      const offerInfo = await getOffer(newOffer._id);
`newOffer` only contains the `propertyId` and not he name. The property name is needed when sending the mail in the offer controller

2020-09-15 08:08 UTC, andela-hpopoola reviewed
I have tested a few of the endpoints and they look good. I will approve this when I test the remaining ones.

2020-09-15 17:12 UTC, andela-hpopoola approved these changes
Thank you for working on this. This PR has really been a roller coaster of comments 😄 

I left a couple of comments but the most important one is to ensure that an offer has been accepted by the user before the admin can assign it (from the code, you just assigned with no validation).

Feel free to merge when you have resolved all the comments.

Here are the next stuffs missing from the endpoint -
1. Lets add `Cancelled` to the offer status so that an admin can cancel an offer letter. `Rejected` and `Neglected` are still placeholders for now. We will revisit them later.

2. The reference code generation -- Please refer to Namo's explanation in the mail

Thank you and Nice work.

2020-09-15 17:12 UTC, andela-hpopoola commented on server/services/offer.service.js
> +export const assignOffer = async (offerId) => {
[Very Important] We need to ensure that the offer has been accepted by the user before the admin can assign it.

2020-09-16 15:40 UTC, merged