#175070987 account overview endpoint
Highrachy/ballers-api pull request #52
Opened 2020-10-05 21:53 UTC by tobieeniafe

#### What does this PR do?
Add account overview endpoint

#### Description of Task to be completed?
Add endpoint to return financial overview of user account 

#### How should this be manually tested?
`GET /api/v1/user/overview`

#### What are the relevant pivotal tracker stories?
#175070987

2020-10-06 06:52 UTC, andela-hpopoola requested changes
Thank you for working on this. 

I thought we agreed that we should add the referral rewards too to this and use test to verify that it works accordingly? Please lets add this so that we can wrap this up. Thank you.

2020-10-06 06:52 UTC, andela-hpopoola commented on server/services/user.service.js
> +  const overview = {
This serves no purpose, we can return the whole object.

2020-10-06 06:52 UTC, andela-hpopoola commented on server/services/user.service.js
> +  return overview;
```suggestion
  return { 
     contributionReward,
    totalAmountPaid,
  };
```

2020-10-06 20:35 UTC, andela-hpopoola requested changes
Thank you for making the changes. This looks good to me, only a few nits to ensure that we improve the code quality. I will also need to test on my computer to be sure that we covered all edge cases. Thank you for making this work.

2020-10-06 20:35 UTC, andela-hpopoola commented on server/routes/user.routes.js
> + *  /user/overview:
Overview is too generic, lets make this to be account-overview so that it can be explicit.
```suggestion
 *  /user/account-overview:
```

2020-10-06 20:35 UTC, andela-hpopoola commented on server/controllers/user.controllers.js
> +          overview,
I prefer we should be more explicit to make the endpoint easier to work with.
```suggestion
          accountOverview,
```

2020-10-06 20:35 UTC, andela-hpopoola commented on server/routes/user.routes.js
> +router.get('/overview', authenticate, UserController.getAccountOverview);
```suggestion
router.get('/account-overview', authenticate, UserController.getAccountOverview);
```

2020-10-06 20:35 UTC, andela-hpopoola commented on server/services/user.service.js
> +  let contributionReward = await calculateContributionReward(userId);
**Code Smell**

Reassigning contributionReward from an array to a number is not a good programming pattern. Lets create different variables to cater for this.

```js
const calculatedContributionReward = await calculateContributionReward(userId);
const contributionReward = calculatedContributionReward.length > 0 ? calculatedContributionReward[0].contributionReward : 0;
```

Please, lets fix this for totalAmountPaid and referralRewards too 🙏

2020-10-06 20:35 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +        it('returns contribution reward of one million', (done) => {
If we update the number and it returns a contribution reward of 2 million, we would be forced to update the test description which is not necessary.

```suggestion
        it('returns a valid contribution reward', (done) => {
```

2020-10-06 20:35 UTC, andela-hpopoola commented on test/services/user.service.test.js
> +        expect(overview.contributionReward).to.eql(0);
Can we add test that referralRewards and totalAmountPaid is valid here too 🙏

2020-10-06 20:35 UTC, andela-hpopoola commented on test/services/user.service.test.js
> +        expect(overview.contributionReward).to.eql(2000000);
Can we add test that referralRewards and totalAmountPaid is valid here too 🙏

2020-10-08 06:20 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +              expect(res.body.accountOverview.contributionReward).to.be.eql(1000000);
Magic numbers are very difficult to understand when reading. This can be improved to something more meaningful like:
```suggestion     expect(res.body.accountOverview.contributionReward).to.be.eql(property.price - offer.totalAmountPayable);
```

2020-10-08 06:26 UTC, andela-hpopoola approved these changes
Thank you for working on this. Feel free to merge after getting rid of all the magic numbers.

2020-10-08 06:26 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +              expect(res.body.accountOverview.contributionReward).to.be.eql(1000000);
Magic numbers are very difficult to understand when reading. This can be improved to something more meaningful like:

```suggestion
              expect(res.body.accountOverview.contributionReward).to.be.eql(property.price - offer.totalAmountPayable);
```

2020-10-08 06:26 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +              expect(res.body.accountOverview.totalAmountPaid).to.be.eql(250000);
```suggestion
              expect(res.body.accountOverview.totalAmountPaid).to.be.eql(transaction.amount);
```

2020-10-08 06:26 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +              expect(res.body.accountOverview.referralRewards).to.be.eql(50000);
Can you fix this and other related tests too as suggested above? The problem of using magic numbers is that it would make the test more difficult to update in the future which could make you waste more time debugging the cause of the bug.

2020-10-08 06:26 UTC, andela-hpopoola commented on test/services/user.service.test.js
> +        expect(overview.contributionReward).to.eql(2000000);
Can we get rid of the magic numbers here too 🙏

2020-10-08 07:05 UTC, andela-hpopoola requested changes
I will have to un-approve this as I noticed that the property section is still missing. From the pivotal tracker story, the returned account overview should be like this:

```
accountOverview: {
           properties: [
              {
                  name : "Property A",
                  paid: "150000",
              },
              {
                 ...
              }
           ],
          totalAmountPaid: 1500000,
          referralRewards: 10000,
          contributionReward: 500000,
}
```

Can we add the property section and test that it really exists please?

2020-10-08 19:09 UTC, tobieeniafe commented
> I will have to un-approve this as I noticed that the property section is still missing. From the pivotal tracker story, the returned account overview should be like this:
> 
> ```
> accountOverview: {
>            properties: [
>               {
>                   name : "Property A",
>                   paid: "150000",
>               },
>               { 
>                  ...
>               }
>            ],
>           totalAmountPaid: 1500000,
>           referralRewards: 10000,
>           contributionReward: 500000,
> }
> ```
> 
> Can we add the property section and test that it really exists please?

that would be implemented when story #175070906 is complete. As it would use the same service.

2020-10-09 06:07 UTC, andela-hpopoola approved these changes
Thank you for working on this. In case the list of properties takes a longer time to implement, I feel it is safer to merge this and make those changes in a later PR. 

Feel free to merge this but implement the below comment in another PR to speed up our work. Thank you.

https://github.com/Highrachy/ballers-api/pull/52#pullrequestreview-504481806

2020-10-09 07:08 UTC, merged