#175335976 update email content
Highrachy/ballers-api pull request #64
Opened 2020-10-20 10:03 UTC by tobieeniafe

#### What does this PR do?
Update all email contents

#### Description of Task to be completed?
Update all email contents

#### How should this be manually tested?
`PUT /api/v1/offer/accept`

#### Any background context you want to provide?
[Email templates](https://docs.google.com/presentation/d/1l9XZHtV9-uFomT5bjZF5AAcE7pcOq8WrHmFUvHOdSjc/edit?ts=5f55d6f2#slide=id.p)

#### What are the relevant pivotal tracker stories?
#175335976

2020-10-20 18:32 UTC, andela-hpopoola requested changes
Thank you for working on this. I left a comment on ensuring that the right name is used.

2020-10-20 18:32 UTC, andela-hpopoola commented on server/controllers/offer.controllers.js
> +        const contentTop = `Note that your offer to ${user.lastName} ${user.firstName} on ${offerResponse.propertyInfo.name} has been accepted. Check your dashboard for more details.`;
I think the name here should be gotten from Enquiry, not User. Remember, the user might be buying the property for another person.

2020-10-21 21:01 UTC, andela-hpopoola approved these changes
Thank you for working on this. Looks good to me.

2020-10-22 14:16 UTC, tobieeniafe commented
> Thank you for working on this. Looks good to me. I will approve when you fix the failing test.

I don't understand what's happening, but the test pass locally, but keep failing on travis here also

2020-10-29 05:32 UTC, andela-hpopoola approved these changes
Thank you for updating this. Feel free to merge this when ready.

2020-10-29 07:43 UTC, merged