#175261571 endpoint to raise concern
Highrachy/ballers-api pull request #65
Opened 2020-10-23 00:44 UTC by tobieeniafe

#### What does this PR do?
Add endpoint to raise and resolve concern for offer

#### Description of Task to be completed?
Add endpoint to raise and resolve concern for offer

#### How should this be manually tested?
`PUT api/v1/offer/raise-concern`
`PUT api/v1/offer/resolve-concern`

#### What are the relevant pivotal tracker stories?
#175261571

2020-10-23 06:03 UTC, andela-hpopoola requested changes
Thank you for working on this. My major concern is ensuring that a user can raise multiple concerns on an offer irrespective of whether the first concern has been resolved or not.

2020-10-23 06:03 UTC, andela-hpopoola commented on server/models/offer.model.js
> +    concern: {
This allows only 1 concern, we should allow the model to allow multiple concerns as most users will always raise more concern irrespective of whether their concern has been resolved or not.

2020-10-23 06:03 UTC, andela-hpopoola commented on server/controllers/offer.controllers.js
> +      .then((offer) => {
We might need to send another mail when the concern has been resolved too.

2020-10-23 06:03 UTC, andela-hpopoola commented on mailer/index.js
> +    contentTop: `A concern has been raised on your offer to [User name]. The question states [question]. `,
Kindly inform and remind Namo on getting or reviewing the contents for this mail.

2020-10-27 05:53 UTC, andela-hpopoola requested changes
Thank you for working on this. You did a great work in the comment implementation. I have more comments on test 🙏 

1. Can we write tests to ensure that the user can raise another concern after raising the first concern. This is just to test that the implementation supports multiple questions (I know it supports it but the test ensure we don't break this in the future)

2. Can we also write tests to ensure that the concerns are loaded every time an offer is loaded. You might need to update existing tests to ensure that they are loaded as expected since we just implement concerns. This should be done in all important places where `Offers are loaded` in the controller tests. This ensures that the concerns are available for the users and the admin always.

I will test this on my local machine and approve once you have implemented this above fixes. Thank you and Nice work.

2020-10-27 05:53 UTC, andela-hpopoola commented on server/models/offer.model.js
> +        status: {
Let's add a date to know when the question was asked and another date for when the response is given.

2020-10-27 05:53 UTC, andela-hpopoola commented on test/controllers/offer.controller.test.js
> +    describe('when offers exist in db', () => {
```suggestion
    describe('when an offer exist in db', () => {
```

2020-10-27 05:53 UTC, andela-hpopoola commented on test/controllers/offer.controller.test.js
> +        it('returns successful payload', (done) => {
```suggestion
        it('resolves the right concern', (done) => {
```

2020-10-27 05:53 UTC, andela-hpopoola commented on mailer/index.js
> +    contentTop: `Your raised concern has been resolved. Check your dashboard for more information.`,
Not really bothered about the implementation here, but I think it would make more sense if the question and the response is given in the mail so that the user can read them without logging into the dashboard.

```suggestion
contentTop: `Your raised concern has been resolved. <br /> <strong>[Question]</strong> <br /> <br /> [Response]`,
```

2020-10-28 05:26 UTC, andela-hpopoola commented
Thank you for working on this.

> Can we also write tests to ensure that the concerns are loaded every time an offer is loaded. You might need to update existing tests to ensure that they are loaded as expected since we just implement concerns. This should be done in all important places where Offers are loaded in the controller tests. This ensures that the concerns are available for the users and the admin always.

I believe you need to add more expectations to ensure that the concerns loads for the admin and users. The trick is to look at all the offer routes and add an expectation to test for concerns for all the `GET` routes. 

Just a single line to test that concerns are returned is enough for each of these routes.

2020-10-28 18:26 UTC, andela-hpopoola reviewed
Thank you for working on this. I will approve when I fix the test.

2020-10-28 18:26 UTC, andela-hpopoola commented on test/controllers/offer.controller.test.js
> +              expect(res.body.offers[1]).to.have.property('concern');
Not sure why you used offers[1] instead of 0 here. I believe that if we test for the index of 0 only, it will cover for 1 too. 

```suggestion
              expect(res.body.offers[0]).to.have.property('concern');
```

2020-10-28 18:26 UTC, andela-hpopoola commented on test/controllers/offer.controller.test.js
> +              expect(res.body.offers[1]).to.have.property('concern');
OR this will work too
```suggestion
              expect(res.body.offers[1].concern.length).to.be.eql(0);
```

2020-10-28 20:06 UTC, tobieeniafe commented on test/controllers/offer.controller.test.js
> +              expect(res.body.offers[1]).to.have.property('concern');
exists already in line `948`

2020-10-29 05:33 UTC, andela-hpopoola approved these changes
Thank you for updating this. Feel free to merge this when ready.

2020-10-29 08:13 UTC, merged