#175634790 search for content property
Highrachy/ballers-api pull request #75
Opened 2020-11-14 17:09 UTC by tobieeniafe

#### What does this PR do?
Search for content property

#### Description of Task to be completed?
Search for content property based on state, area & house type

#### How should this be manually tested?
`GET api/v1/area/`
`GET api/v1/area/?state=oyo`
`GET /api/v1/content-property/area/:id`

#### What are the relevant pivotal tracker stories?
#175634790

2020-11-14 17:54 UTC, andela-hpopoola requested changes
Great work on this. This looks good to me. Apart from splitting the states and areas into different endpoints to make it easier to maintain and follow best practices, the implementation looks great. 

Waiting for the tests so that we can merge this asap. Great work and thank you for the lovely implementation.

2020-11-14 17:54 UTC, andela-hpopoola commented on server/controllers/area.controllers.js
> +  search(req, res, next) {
Lets use another name for this instead of search. This is not actually searching but getting the states and areas.

2020-11-14 17:54 UTC, andela-hpopoola commented on server/controllers/area.controllers.js
> +    getStateAndArea(state)
Let's separate this into 2 different endpoints (one to get the states and another to get the areas), please 🙏 ? The idea of returning location for both states and areas doesn't follow the best practises.

2020-11-14 17:54 UTC, andela-hpopoola commented on server/controllers/contentProperty.controllers.js
> +  search(req, res, next) {
This is getting the house types, so using search here is not explanatory enough.

2020-11-15 17:16 UTC, andela-hpopoola requested changes
Thank you for your work on this. The implementation looks solid but I left a few comments to ensure to improve the code quality and ensure we don't run into future endpoint issues.

2020-11-15 17:16 UTC, andela-hpopoola commented on server/services/area.service.js
> +  const areas = await Area.find({ state });
I believe the below lines are not needed since we don't know the format the frontend will need. It is better to just return the id and area as an array and let the frontend convert it to the needed format. 

```suggestion
  const areas = await Area.find({ state }).select('area');
  return { areas };
```

2020-11-15 17:16 UTC, andela-hpopoola commented on server/services/area.service.js
> +export const getStateAndArea = async (state) => {
Lets separate this service and have different services for state and another one for the area 🙏 . Combining them together doesn't give us any advantage, we will still call the controller 2 times to retrieve them so it is better to leave them separated for now.

2020-11-15 17:16 UTC, andela-hpopoola commented on test/controllers/area.controller.test.js
> +      it('returns array of five states', (done) => {
Not sure why you used 5 states here:
```suggestion
      it('returns array of two states', (done) => {
```

2020-11-15 17:16 UTC, andela-hpopoola commented on test/controllers/area.controller.test.js
> +      it('returns array of five states', (done) => {
Same comment as above

2020-11-15 17:16 UTC, andela-hpopoola commented on test/controllers/area.controller.test.js
> +      it('returns array of five states', (done) => {
```suggestion
      it('returns array of five areas', (done) => {
```

2020-11-15 17:16 UTC, andela-hpopoola commented on test/controllers/area.controller.test.js
> +    context('when editor token is used', () => {
We need to add tests that the endpoint returns distinct states.

We will also need to add a test that adds 5 areas for 1 state and try to get the state so that we are sure that the state endpoint returns just 1 state (to be sure that it returns distinct state).

2020-11-15 17:16 UTC, andela-hpopoola commented on test/controllers/area.controller.test.js
> +  describe('Get all areas', () => {
**Bug Alert:** Not sure how I missed this, we need to ensure that we add tests to ensure that the editor or admin cannot add an existing area in the same state.

This will cause lots of confusion in the application if we dont have the check. Sorry I missed it when reviewing your previous code 😞

2020-11-15 17:16 UTC, andela-hpopoola commented on test/controllers/contentProperty.controller.test.js
> +
Same comment with returning distinct states above.

We need to add tests that the endpoint returns distinct house Types.

2020-11-16 22:06 UTC, andela-hpopoola approved these changes
Awesome job @tobieeniafe. This looks good to me, just a few nits to ensure that the code is correct grammatically. Feel free to merge when you fix the non-blocking comments. Nice work and Thank you.

2020-11-16 22:06 UTC, andela-hpopoola commented on test/factories/area.factory.js
> +  .sequence('area', (i) => `lekki phase ${i}`)
Can we leave this as the normal case format since we are already converting the saved area and state to lowercase:

```suggestion
  .sequence('area', (i) => `Lekki Phase ${i}`)
```

2020-11-16 22:06 UTC, andela-hpopoola commented on server/services/area.service.js
> +export const getState = async () => {
One last thing please, to make this method semantically correct, let's update it to the plural form; getStates not getState. 

```suggestion
export const getStates = async () => {
```

2020-11-16 22:06 UTC, andela-hpopoola commented on server/controllers/area.controllers.js
> +    getArea(state)
Just to point out that we are retrieving multiple areas: The same applies to `getState` too 🙏 

```suggestion
    getAreas(state)
```

2020-11-17 17:16 UTC, tobieeniafe commented on test/factories/area.factory.js
> +  .sequence('area', (i) => `lekki phase ${i}`)
this makes the test fail because the value exists in uppercase but the returned value is in lowercase

2020-11-17 19:22 UTC, merged