#175735113 add route to list all areas
Highrachy/ballers-api pull request #79
Opened 2020-11-20 00:23 UTC by tobieeniafe

#### What does this PR do?
Add route to list all areas

#### Description of Task to be completed?
Add route to list all areas with number of properties under them with corresponding minimum, maximum & average values of properties 

#### How should this be manually tested?
`GET /api/v1/area`

#### What are the relevant pivotal tracker stories?
#175735113

2020-11-20 07:20 UTC, andela-hpopoola requested changes
This is looking good. Thank you for working on this. I have not tested this, but can you add tests while I test later in the day.

2020-11-20 07:20 UTC, andela-hpopoola commented on server/routes/area.routes.js
> +router.get('/', authenticate, isEditorOrAdmin, AreaController.getAllAreas);
I believe this should follow the `all` convention for other endpoints
```suggestion
router.get('/all', authenticate, isEditorOrAdmin, AreaController.getAllAreas);
```

2020-11-20 19:20 UTC, andela-hpopoola requested changes
Thank you for your work on this. I left a few comments but I believe this should be good to go after you fix. Feel free to ignore the ones for later PR (please don't close them as I am using them as a reminder for myself). Thank you.

2020-11-20 19:20 UTC, andela-hpopoola commented on test/controllers/area.controller.test.js
> +  describe('Get all areas and correponding properties', () => {
```suggestion
  describe('Get all areas and corresponding properties', () => {
```

2020-11-20 19:20 UTC, andela-hpopoola commented on test/controllers/area.controller.test.js
> +    const ajah = AreaFactory.build({ area: 'ajah' });
Can we add this as a normal case since that is how it will be submitted in the form 🙏?  It looks weird writing the name of an area in lowercase.

```suggestion
    const ajah = AreaFactory.build({ area: 'Ajah' });
```

2020-11-20 19:20 UTC, andela-hpopoola commented on test/controllers/area.controller.test.js
> +    const lekki = AreaFactory.build({ _id: lekkiId, area: 'lekki' });
Same here.

2020-11-20 19:20 UTC, andela-hpopoola commented on test/controllers/area.controller.test.js
> +            expect(res.body.areas[1].area).to.be.eql(lekki.area);
This should fix the changes
```suggestion
            expect(res.body.areas[1].area).to.be.eql(lekki.area.toLowercase());
```

2020-11-20 19:20 UTC, andela-hpopoola commented on test/controllers/area.controller.test.js
> +            expect(res.body.areas[1].minimumPrice).to.be.eql(100000);
I am not comfortable using the same value for the minimumPrice, maximumPrice and averagePrice. Can we use a varying price to be more certain that there is no bug with the implementation.

2020-11-20 19:20 UTC, andela-hpopoola commented on test/controllers/area.controller.test.js
> +    context('when admin token is used', () => {
In the future, it is better to use just one test and use a function or array mapping since this test is the same as the one above. Something like this:

```js
[editorToken, adminToken].map((token) => {
it('returns all areas and properties', (done) => {
        request()
          .get('/api/v1/area/all')
          .set('authorization', token) // <---- the token is replaced here
          .end((err, res) => {
              ...
          }
});
```

Remember, you are a programmer, you need to be extremely creative 😉

2020-11-20 19:20 UTC, andela-hpopoola commented on test/controllers/area.controller.test.js
> +    context('when user token is is used', () => {
We need to right a function test for this test (and the 2 tests below) and replace all instances to save time. Maybe a later PR.

2020-11-22 23:30 UTC, tobieeniafe commented on test/controllers/area.controller.test.js
> +    context('when admin token is used', () => {
`context('when admin or editor token is used', () => {
      [editorToken, adminToken].map((token) => {
        it('returns all areas and properties', (done) => {
          request()
            .get('/api/v1/area/all')
            .set('authorization', token)
            .end((err, res) => {
              ...
              done();
            });
        });
      });
    });
`

returns undefined for authorization tho 😬

2020-11-23 19:35 UTC, andela-hpopoola commented on test/controllers/area.controller.test.js
> +    context('when admin token is used', () => {
I think I understand why that wasn't working, it's because the tokens are defined in the beforeEach block, so they are undefined before the `it block`. This can be resolved by defining the token in the`it block`.

Enough grammar, this should work though:

```js
    context('when a valid token is used', () => {
      [...new Array(2)].map((_, index) =>
        it('returns all areas and properties', (done) => {
          request()
            .get('/api/v1/area/all')
            .set('authorization', [editorToken, adminToken][index])
            .end((err, res) => {
              expect(res).to.have.status(200);
              expect(res.body.success).to.be.eql(true);
              expect(res.body.areas.length).to.be.eql(2);
              expect(res.body.areas[0].area).to.be.eql(ajah.area.toLowerCase());
              expect(res.body.areas[0].numOfProperties).to.be.eql(0);
              expect(res.body.areas[0].minimumPrice).to.be.eql(null);
              expect(res.body.areas[0].maximumPrice).to.be.eql(null);
              expect(res.body.areas[0].averagePrice).to.be.eql(null);
              expect(res.body.areas[1]._id).to.be.eql(lekkiId.toString());
              expect(res.body.areas[1].area).to.be.eql(lekki.area.toLowerCase());
              expect(res.body.areas[1].numOfProperties).to.be.eql(5);
              expect(res.body.areas[1].minimumPrice).to.be.eql(100000);
              expect(res.body.areas[1].maximumPrice).to.be.eql(500000);
              expect(res.body.areas[1].averagePrice).to.be.eql(180000);
              done();
            });
        }),
      );
    });
```

2020-11-23 19:37 UTC, andela-hpopoola approved these changes
Thank you for your hard work. This should be good to go. Feel feel to fix the test comment so that you can use the same technique in similar tests.

2020-11-23 20:55 UTC, merged