#175634768 add vendor object to user model
Highrachy/ballers-api pull request #80
Opened 2020-11-20 00:29 UTC by tobieeniafe

#### What does this PR do?
Add vendor object to user model

#### Description of Task to be completed?
Add vendor object to user model

#### How should this be manually tested?
NA

#### What are the relevant pivotal tracker stories?
#175634768

2020-11-20 07:26 UTC, andela-hpopoola requested changes
Thank you for working on this.
To make this useful, can you update the registration endpoint to support vendor registration. I think the logic is to check if the logic is to check if the payload contains an optional companyName, then save the payload as a vendor.

For the required firstName and lastName, I believe they should still be required, however, from the frontend the firstName will be the supplied company name and the last name will be 'Company'. This is nothing you should be bothered about in the endpoint, just explaining to clear your doubts.

2020-11-20 19:31 UTC, andela-hpopoola requested changes
Thank you for your updates. I left a few comments. Can you work on the logic for vendor registration as stated here:

> To make this useful, can you update the registration endpoint to support vendor registration. I think the logic is to check if the payload contains an optional `companyName`, then save the payload as a vendor with the company name.

To add more context, when anyone wants to register as a vendor, instead of asking them for the firstName and lastName in the frontend, we will ask them for the company name. Every other thing is the same as the normal registration.

2020-11-20 19:31 UTC, andela-hpopoola commented on server/schemas/user.schema.js
> +  vendor,
Awesome work. Unfortunately, this should contain only the `companyName`, the vendor is adding everything after registration (not before). 

Notwithstanding, the `vendor` schema might be useful for user updates. So it is not a wasted effort.

2020-11-20 19:31 UTC, andela-hpopoola commented on server/models/user.model.js
> +      phone: {
The phone number and email address are not needed here. The existing one in the user model will be used to avoid confusion.

2020-11-23 19:46 UTC, andela-hpopoola requested changes
Thank you for your hard work here. I left a couple of comments. Next is the test to wrap this up asap.

2020-11-23 19:46 UTC, andela-hpopoola commented on server/models/user.model.js
> +      directors: [
This should be improved based on the latest Figma design:

We need the following IMHO,
```
Name - required string
Phone Number - optional string
isSignatory - true / false
signature - optional string
```

2020-11-23 19:46 UTC, andela-hpopoola commented on server/schemas/user.schema.js
> +// const directors = [
Can we remove the comments here, you can always come back to this commit here on GitHub to copy them if you need them later in the future.

2020-11-23 19:46 UTC, andela-hpopoola commented on server/services/user.service.js
> +  let user = newUser;
I don't think this is needed. We can check if the vendor is present and update roles instead of updating the user object.

2020-11-23 19:46 UTC, andela-hpopoola commented on server/services/user.service.js
> +  if (user.vendor && user.vendor.companyName) {
I think it is better to update the role:

```js
const role = user.vendor && user.vendor.companyName ? USER_ROLE.VENDOR : USER_ROLE.USER;

2020-11-23 19:47 UTC, andela-hpopoola commented on server/models/user.model.js
> +      companyName: {
You will also need to add the company logo to the vendor schema.

2020-11-23 23:44 UTC, tobieeniafe commented on server/services/user.service.js
> +  if (user.vendor && user.vendor.companyName) {
adding this line breaks the test across all models. can't seem to find the reason

2020-11-24 06:27 UTC, andela-hpopoola commented on server/services/user.service.js
> +  if (user.vendor && user.vendor.companyName) {
Thank you for pointing that out. It is kind of obvious that the error is from the fact that admins are created from the test and this is setting the default to User. So the tests for admins will fail (I believe you should have figured it out since the error messages from the test clearly point to this). 

This should work rather:

```js
  const role = user.vendor && user.vendor.companyName ? USER_ROLE.VENDOR : newUser.role;
```

2020-11-24 06:31 UTC, andela-hpopoola requested changes

2020-11-24 06:31 UTC, andela-hpopoola commented on server/models/user.model.js
> +    vendor: {
Can we move this down a little bit so that the newly added `vendor` object is arranged alphabetically with the existing schema. Let it come before the timestamp. It is a good practise to arrange object values alphabetically (makes it easier to detect a value quickly and easily detect duplicate / existing values).

2020-11-24 18:37 UTC, tobieeniafe commented on server/services/user.service.js
> +  if (user.vendor && user.vendor.companyName) {
`newUser` is undefined tho. for some reason, it only works when the `user` object is modified

2020-11-25 06:07 UTC, andela-hpopoola commented on server/services/user.service.js
> +  if (user.vendor && user.vendor.companyName) {
Of course, `newUser` will be undefined now since you have removed `newUser` from the code. Previously you had something like this:

```js
const user = newUser; // <----- where newUser was defined in the method parameter 
```

Since you have removed this and decided to use `user` directly, so `user.role` will be appropriate. The purpose is just to get the role that is sent over when the user is created.

Please note that the codes I write in PRs are for illustrative purposes only, I believe you should be able to figure the exact code once you understand the intention behind the change. Most times I don't test them, while at other times they would be affected by the changes you have made (always keep that in mind please) 

So this will work:

```js
  const role = user.vendor && user.vendor.companyName ? USER_ROLE.VENDOR : newUser.role;
```

2020-11-25 06:11 UTC, andela-hpopoola requested changes
Thank you for the updates and arranging the vendor object alphabetically. Still expecting the tests to wrap this up.

2020-11-25 06:11 UTC, andela-hpopoola commented on server/models/user.model.js
> +      vendorCode: {
If we are adding the vendorCode, I think it is a good idea to generate it during registration. What do you think?

2020-11-25 09:35 UTC, tobieeniafe commented on server/models/user.model.js
> +      vendorCode: {
remember we mentioned something about vendor code being unique to each vendor during offer letter generation? So I just left it till we made a decision

2020-11-25 17:24 UTC, andela-hpopoola requested changes
Thank you for the hardwork here. I left a few comments but I am more concerned on ensuring that we pull out the company name when we are sending a mail to the vendor. Once that is fixed, I believe this PR is good to go.

2020-11-25 17:24 UTC, andela-hpopoola commented on server/models/user.model.js
> +      vendorCode: {
Yes, we can add a number in front of the vendor code to differentiate them as they would be unique. Let's defer this to a later PR then and ask the content team the best way we would generate the vendor code.

2020-11-25 17:24 UTC, andela-hpopoola commented on server/services/user.service.js
> +  const user = newUser;
I think you got my comment here slightly wrong, this is no longer needed. I was referring to why I used newUser instead of `user`. Let's revert line 74 to `user` and remove this line. It is not doing anything.

2020-11-25 17:24 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +              expect(res.body.message).to.be.eql('User registered');
I think we should update this:

```suggestion
              expect(res.body.message).to.be.eql('Company registered');
```

2020-11-25 17:24 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +                vendor,
Vendor uses `companyName` instead of `firstName` so the logic here can cause unexpected bug; A random firstName is used here but it is supposed to use the companyName (as FirstName), We have 2 options in the code though.

1. We can assign companyName to firstName when saving and ensure we update the firstName when the companyName has been updated. This makes the vendor object to work flawlessly with the mail.
2. Create a logic in the mail service to cater for companyName if it is present. The advantage of this is that once it detects that the passed-in object has a `vendor.companyName` value, it uses that instead of firstName.

I prefer the second one though since it is more explicit and handles the vendor directly instead of changing the concept of the vendor.

2020-11-26 00:09 UTC, tobieeniafe commented on test/controllers/user.controller.test.js
> +              expect(res.body.message).to.be.eql('User registered');
my approach to this causes an error tho

2020-11-26 06:32 UTC, andela-hpopoola requested changes
We are almost there with this PR. Thank you for the hard work.

2020-11-26 06:32 UTC, andela-hpopoola commented on server/services/mailer.service.js
> +    firstName: user.firstName || user.vendor.companyName ? user.vendor.companyName : null,
I am not sure this will work as expected since `firstName` is a required field so it will always be present and the `companyName` will never be used here:

Not 100% sure too, but this looks better:
```suggestion
    firstName: user.vendor && user.vendor.companyName ? user.vendor.companyName : user.firstName || null,
```

2020-11-26 06:32 UTC, andela-hpopoola commented on server/services/user.service.js
> +    // return { token: generateToken(savedUser._id), userType: isVendor ? 'Company' : 'User' };
Not sure why you commented this out though

2020-11-26 22:13 UTC, andela-hpopoola approved these changes
Thank you for the hard work here. This looks good to me.

2020-11-26 23:32 UTC, merged