#175846239 add routes to return single content property and area
Highrachy/ballers-api pull request #81
Opened 2020-11-23 21:09 UTC by tobieeniafe

#### What does this PR do?
Add routes to return single content property and area

#### Description of Task to be completed?
Add routes to return single content property and area

#### How should this be manually tested?
`GET /api/v1/content-property/:id`
`GET /api/v1/area/:id`

#### What are the relevant pivotal tracker stories?
#175846239

2020-11-23 21:39 UTC, andela-hpopoola requested changes
Thank you for working on this. This is looking good. Can you add the tests while I take another look at it tomorrow?

2020-11-23 21:39 UTC, andela-hpopoola commented on server/controllers/area.controllers.js
> +        if (area === null) {
```suggestion
        if (!area) {
```

2020-11-23 21:39 UTC, andela-hpopoola commented on server/services/property.service.js
> +export const getOneProperty = async (propertyId) =>
🙌 Thank you for fixing this.

2020-11-24 07:13 UTC, andela-hpopoola requested changes
Thank you for making these updates. I left a few comments but the most important ones are:

- Add content properties to returned areas
- Ensure we add test assertions for all returned values

2020-11-24 07:13 UTC, andela-hpopoola commented on server/controllers/area.controllers.js
> +    getAreaById(id)
Can we get all the content properties associated with an area and maybe the maximumPrice, miminumPrice and averagePrice of all the properties. This will make the area information more productive for anyone consuming the endpoint.

2020-11-24 20:19 UTC, andela-hpopoola commented on server/controllers/area.controllers.js
> +  getAreaAndContentPropertiesByAreaId,
Not sure why you changed this though, I feel `getAreaById` is a better name though since the focus is in getting on the details pertaining to the area 🤷‍♂️

2020-11-24 20:21 UTC, andela-hpopoola commented on test/controllers/area.controller.test.js
> +  describe('Get area by id', () => {
Can you add an extra test for an area without content properties, please 🙏

2020-11-24 20:22 UTC, andela-hpopoola requested changes
Thank you for the hard work here. This looks great, and your implementation looks brilliant. Waiting to you to resolve the merge conflict and fix the minor comments I added so that I can approve this. Nice work and Thank you once again.

2020-11-24 20:25 UTC, tobieeniafe commented on server/controllers/area.controllers.js
> +  getAreaAndContentPropertiesByAreaId,
`getAreaById` is an existing function that uses the `findById` method

2020-11-24 20:30 UTC, andela-hpopoola commented on server/controllers/area.controllers.js
> +  getAreaAndContentPropertiesByAreaId,
Makes perfect sense to me. Let's leave it like that. Thank you for the explanation.

2020-11-25 05:52 UTC, andela-hpopoola approved these changes
This looks good to me. Thank you for making the changes. Nice work. You can merge it asap.

2020-11-25 09:44 UTC, merged