#175928810 load vendor info for verification
Highrachy/ballers-api pull request #85
Opened 2020-12-02 01:43 UTC by tobieeniafe

#### What does this PR do?
Load vendor info for verification

#### Description of Task to be completed?
Load vendor info for verification

#### How should this be manually tested?
`GET /api/v1/user/vendor/all`

#### What are the relevant pivotal tracker stories?
#175928810

2020-12-02 05:28 UTC, andela-hpopoola requested changes
Thank you for working on this. This looks good. Can you try updating the pagination tests as functions as stated in the story description on Pivotal Tracker?

> ...
Also, can you try to customize the pagination tests as a function so that we don't waste time repeating the same tests over and over again?
...

2020-12-02 10:59 UTC, tobieeniafe commented
> Thank you for working on this. This looks good. Can you try updating the pagination tests as functions as stated in the story description on Pivotal Tracker?
> 
> > ...
> > Also, can you try to customize the pagination tests as a function so that we don't waste time repeating the same tests over and over again?
> > ...

I was able to do this, but I kept running into an `undefined` error on the `adminToken` & `userToken`

2020-12-02 18:28 UTC, andela-hpopoola requested changes
Thank you for the great work. Great thinking and implementation. Once, we are through with this, it would reduce the number of tests we write, the size of our tests file and improve the time wasted in writing recurring tests.

I left a few comments of separating some of the tests so that we will be able to reuse them for similar stuff. This is to save time later as the same function can be reused for other tests in the codebase.

2020-12-02 18:28 UTC, andela-hpopoola commented on test/helpers.js
> +export const paginationTest = ({ validToken, invalidToken, endpoint, model, modelMethod }) => {
```suggestion
export const itReturnsTheRightPaginationValue = ({ validToken, invalidToken, endpoint, model, modelMethod }) => {
```

2020-12-02 18:28 UTC, andela-hpopoola commented on test/helpers.js
> +  context('when no parameters are passed', () => {
```suggestion
  context('when no pagination parameter is passed', () => {
```

2020-12-02 18:28 UTC, andela-hpopoola commented on test/helpers.js
> +  context('with a invalid access token', () => {
Let's write another function for an invalid access token and not tie them to pagination tests. The reason is that we might want to paginate for public endpoints that would be valid when no token is added. Something like `itReturnsForBiddenForInvalidToken`

Also, a separate function for invalid tokens would ensure that we can replace similar tests in the other test files.

2020-12-02 18:28 UTC, andela-hpopoola commented on test/helpers.js
> +  context('without token', () => {
Same comment as above on creating another function for this too. The new function name can be something like `itReturnsAnErrorWhenNoTokenIsPresent`.

2020-12-02 18:28 UTC, andela-hpopoola commented on test/helpers.js
> +  context('when service fails', () => {
Same comment as above on creating another function for this too. The new function name can be something like `itReturnsAnErrorWhenServiceFails`.

2020-12-02 18:28 UTC, andela-hpopoola commented on test/helpers.js
> +export const paginationTest = ({ validToken, invalidToken, endpoint, model, modelMethod }) => {
Separating the pagination tests into independent tests should reduce the parameters used to 3:

```suggestion
export const itReturnsTheRightPaginationValue= ({ endpoint, model, token }) => {
```

2020-12-02 18:28 UTC, andela-hpopoola commented on test/helpers.js
> +      sinon.stub(model, `${modelMethod}`).throws(new Error('Type Error'));
Not sure why you added this as a string, I believe we can remove the string interpolation:

```suggestion
      sinon.stub(model, modelMethod).throws(new Error('Type Error'));
```

2020-12-03 05:27 UTC, andela-hpopoola approved these changes
Thank you for the updates on this. I left a few more comments on ensuring that the functions are consistent to make it easier to use for a new developer. Feel free to merge after making the changes.

2020-12-03 05:27 UTC, andela-hpopoola commented on test/helpers.js
> +export const itReturnsTheRightPaginationValue = (token, endpoint) => {
Can we ensure that the `endpoint` comes first before token since endpoint is needed for all of the functions you have created. From Javascript documentation, that is how similar functions are treated to make it easier to remember the parameter order.

```js
itReturnsTheRightPaginationValue(endpoint, token)
itReturnsForbiddenForInvalidToken(endpoint, token)
itReturnsForbiddenForNoToken(endpoint)
itReturnsAnErrorWhenServiceFails(endpoint, token, model, modelMethod)
```

2020-12-03 05:27 UTC, andela-hpopoola commented on test/helpers.js
> +export const itReturnsAnErrorWhenServiceFails = (token, endpoint, model, modelMethod) => {
We can set a default here for modelMethod since it is setup for 'aggregate' to ensure that we can omit the last parameter when we use this function for aggregate.

```suggestion
export const itReturnsAnErrorWhenServiceFails = (token, endpoint, model, modelMethod = "aggregate")
```

2020-12-03 05:27 UTC, andela-hpopoola commented on test/helpers.js
> +export const itReturnsForbiddenForInvalidToken = (invalidToken, endpoint) => {
Let's change the `invalidToken` here to `token` for consistency's sake. The function name already specifies that the token is invalid (and also the test will fail if you use a valid token)

2020-12-03 19:17 UTC, merged