#176029266 update visitation for vendor
Highrachy/ballers-api pull request #88
Opened 2020-12-08 00:05 UTC by tobieeniafe

#### What does this PR do?
Update visitation schedule for vendor

#### Description of Task to be completed?
Update visitation schedule for vendor

#### How should this be manually tested?
`POST /api/v1/visitation/schedule`

#### What are the relevant pivotal tracker stories?
#176029266

2020-12-08 06:21 UTC, andela-hpopoola requested changes
Thank you for working on this. This looks good but I am most concerned about updating the `visitation.controller.test.js` to ensure we test for vendor and also ensure we test the mail we are sending out. Thank you.

2020-12-08 06:21 UTC, andela-hpopoola commented on server/services/visitation.service.js
> +      return { newSchedule, vendorEmail: vendor.email };
Nice changes here. Even though it doesn't really matter here because the number of changes you made is not too much, it might be better to leave this as schedule to avoid making those changes.

```suggestion
      return { schedule: newSchedule, vendorEmail: vendor.email };
```

2020-12-08 06:21 UTC, andela-hpopoola commented on server/controllers/visitation.controllers.js
> +        sendMail(EMAIL_CONTENT.SCHEDULE_VISIT, { email: vendorEmail }, { contentBottom });
We need to update the test in the controller file to be sure from `admin` user to a vendor. 

https://github.com/Highrachy/ballers-api/blob/b5cc8e0b234de242ff5f90eaa0467758c9d84fec/test/controllers/visitation.controller.test.js#L32

Also for each of our mail tests, we want to ensure that we send the right mail and to the right email. So it is important to add a test like this line to the test too so that we can test the content being sent and the email it is sending it to.

https://github.com/Highrachy/ballers-api/blob/b5cc8e0b234de242ff5f90eaa0467758c9d84fec/test/controllers/user.controller.test.js#L69

2020-12-09 06:27 UTC, andela-hpopoola requested changes
Thank you for making the changes. We are almost there, I left a couple of comments to ensure we get the implementation right. I am sure that once we get this right, other endpoints will be easier to implement for you. Thank you and Nice work.

2020-12-09 06:27 UTC, andela-hpopoola commented on test/controllers/visitation.controller.test.js
> +              expect(userId.equals(res.body.schedules[0].userId)).to.be.eql(true);
To make this test more logical, this should test that the `vendorId` is equal to this VendorId Testing that it is true will not catch the bug if the test is returning the wrong Vendor property.

2020-12-09 06:27 UTC, andela-hpopoola commented on server/controllers/visitation.controllers.js
> +        sendMail(EMAIL_CONTENT.SCHEDULE_VISIT, { email: vendorEmail }, { contentBottom });
Nice thinking here. However, we want the mail to also retrieve the company name, so we might need to add the vendor company name here so that it can work as expected. 

https://github.com/Highrachy/ballers-api/blob/76129cd26df03c27bc2518302c3965ecd7de6cbb/server/services/mailer.service.js#L64

I didn't test it though, you can start by passing the whole vendor Object where vendor stands for all the user information.

```suggestion
        sendMail(EMAIL_CONTENT.SCHEDULE_VISIT, vendor, { contentBottom });
```

2020-12-09 06:27 UTC, andela-hpopoola commented on server/controllers/visitation.controllers.js
> +            .json({ success: false, message: 'No schedules available' });
Even though the schedules array is empty, we need to add it here so that it can be consistent with line 32 and so that we can also test that it is 0.

```suggestion
            .json({ success: false, message: 'No schedules available', schedules });
```

2020-12-09 06:27 UTC, andela-hpopoola commented on server/services/visitation.service.js
> +      { $match: { vendorId: ObjectId(userId) } },
Since this is the only difference between the 2 queries, we can use 1 query instead of splitting them off, and add the $match if it is a vendor that is making the request.

2020-12-09 06:27 UTC, andela-hpopoola commented on server/controllers/visitation.controllers.js
> +    const userId = req.user._id;
We can send the whole user object instead of getting the `_id` only here.
```suggestion
    const { user } = req;
```

2020-12-09 06:27 UTC, andela-hpopoola commented on server/services/visitation.service.js
> +  const user = await getUserById(userId).catch((error) => {
I dont think this is necessary, I think we should already have the user object defined in the `req` variable in the controller, we can pass that here instead of making an additional request.

2020-12-09 06:27 UTC, andela-hpopoola commented on test/controllers/visitation.controller.test.js
> +    vendorToken = await addUser(vendor);
Can we add another vendor here again and test that each vendor is getting their own content. This is necessary because we want to ensure that each of the vendors get their own information only. Using one vendor for the test might not catch this, so it is better to add 2 vendors and test that the information returned is for the right vendor.

Feel free to use a loop or a function to make the test easier.

2020-12-09 06:27 UTC, andela-hpopoola commented on test/controllers/visitation.controller.test.js
> +            expect(demoPropertyId.equals(res.body.schedule.propertyId)).to.be.eql(true);
Can we update this to a more readable format, 🙏 

```suggestion
            expect(demoPropertyId.toString()).to.be.eql(res.body.schedule.propertyId.toString());
```

2020-12-09 06:27 UTC, andela-hpopoola commented on test/controllers/visitation.controller.test.js
> +            expect(sendMailStub).to.have.be.calledWith();
Not sure why this line passed but this is not necessary.

2020-12-09 06:27 UTC, andela-hpopoola commented on test/controllers/visitation.controller.test.js
> +      context('when an admin token is used', () => {
Lets add 3 scheduled visitations, 
1. for admin
2. for vendor1
3. for vendor2

Lets write tests to ensure that 3 is returned for admin, vendor1 and vendor2 returns just 1 scheduled visits and the id matches their property.

2020-12-09 06:27 UTC, andela-hpopoola commented on test/services/visitation.service.test.js
>      context('when schedule added is valid', () => {
We can use a loop here to make the tests available for an admin and a vendor. This is optional though (to save time) as we already have tests for this in the controller.

2020-12-09 20:30 UTC, tobieeniafe commented on test/controllers/visitation.controller.test.js
> +            expect(demoPropertyId.equals(res.body.schedule.propertyId)).to.be.eql(true);
you suggested this format a while back tho

2020-12-09 22:46 UTC, tobieeniafe commented on server/services/visitation.service.js
> +      { $match: { vendorId: ObjectId(userId) } },
couldn't find a solution for this. suggestions?

2020-12-10 05:44 UTC, andela-hpopoola requested changes
Thank you for your hard work on this. I left more comments to ensure we get this totally right.

Also, we need to add pagination to the `all` endpoint. Anytime we are working with any `all` endpoint, it makes sense to add pagination to it.



Can we substitute the test on line 439 
```
      context('when admin token is not available', () => {
```
for the `itReturnsAnErrorForInvalidToken` helper test and ensure we test for an admin and a single vendor.

Also, Line 456 and Line 470 can be substituted too with the right helper test.

2020-12-10 05:44 UTC, andela-hpopoola commented on server/services/visitation.service.js
> +export const getAllVisitations = async (user) => {
I thought I left a comment on ensuring that we use just one options for the vendor and admin. This should work:

```js
export const getAllVisitations = async (user) => {
  const scheduleOptions = [
    {
      $lookup: {
        from: 'properties',
        localField: 'propertyId',
        foreignField: '_id',
        as: 'propertyInfo',
      },
    },
  ];

  if (user.role === USER_ROLE.VENDOR) {
    scheduleOptions.push({ $match: { vendorId: ObjectId(user._id) } });
  }

  const schedules = await Visitation.aggregate(scheduleOptions);

  return schedules;
};
```

2020-12-10 05:44 UTC, andela-hpopoola commented on test/controllers/visitation.controller.test.js
> -            expect(res).to.have.status(200);
Can we revert the tests here, please? I prefer we use 404 when an individual item is not found not when no visitation present in the database. If no visitation is not in the database, we can assume that the request is successful and doesn't require an error message. However, if we are trying to get a single visitation and it is not found, we should use 404 for that.

This is the pattern we adopted for this project. Changing it now would force us to change for other endpoints which will be time-consuming. Consistency matters a lot when developing APIs, so let's try to ensure we are consistent for all implementation. 

Lets revert this, please.

2020-12-10 05:44 UTC, andela-hpopoola commented on test/controllers/visitation.controller.test.js
> +const user = UserFactory.build({ _id: userId, role: USER_ROLE.USER, activated: true });
Instead of defining the userId and user factory generation separately, you can define the userId within the user factory by using the option we defined in the factory:

https://github.com/Highrachy/ballers-api/blob/a502bdb3b690501378058ff9f9e49e0dcc6c9446/test/factories/user.factory.js#L7

Here is an example of where it is used
https://github.com/Highrachy/ballers-api/blob/a502bdb3b690501378058ff9f9e49e0dcc6c9446/test/controllers/property.controller.test.js#L1717

In places you need the Id, you could as well get them by using `vendor._id` or `user._id` depending on the name of the factory.

2020-12-10 05:44 UTC, andela-hpopoola commented on test/controllers/visitation.controller.test.js
> +    const testAdminProperty = PropertyFactory.build({
Can we remove the testAdminProperty? This is to prevent the test from failing in the future. When using the application, the admin should be unable to add properties but should only be able to view all the visitations.

2020-12-10 05:44 UTC, andela-hpopoola commented on test/controllers/visitation.controller.test.js
> +      context('when an vendor token is used', () => {
```suggestion
      context('when another vendor token is used', () => {
```

2020-12-12 15:48 UTC, tobieeniafe commented
@andela-hpopoola is there anything left to complete on this PR? so we can merge and proceed

2020-12-12 16:18 UTC, andela-hpopoola approved these changes
Apologies, I have forgotten that I need to approve this. I have fixed the test typo so feel free to merge anytime you want.

2020-12-12 16:46 UTC, merged