#176337881 edit & remove directors or signatories
Highrachy/ballers-api pull request #94
Opened 2021-01-05 21:20 UTC by tobieeniafe

#### What does this PR do?
Add routes to edit & remove directors or signatories

#### Description of Task to be completed?
Add routes to edit & remove directors or signatories

#### How should this be manually tested?
`PUT /api/v1/user/vendor/director/add`
`DELETE /api/v1/user/vendor/director/remove/:id`

#### What are the relevant pivotal tracker stories?
#176337881

2021-01-06 06:20 UTC, andela-hpopoola requested changes
Thank you for working on this. I think the most important part is that you need to add an id to the director's schema to ensure that we are updating/deleting the right directors.

2021-01-06 06:20 UTC, andela-hpopoola commented on server/services/user.service.js
> +  directors = directors.filter((director) => director._id.toString() !== directorId.toString());
I believe the two lines can be merged together into 1
```suggestion
  const signatories = directors.filter((director) => director._id.toString() !== directorId.toString() && director.isSignatory);
```

You can then proceed to check if there are signatories for verified vendors

```js
if (signatories.length === 0 && user.vendor.verified) {
...
```

2021-01-06 06:20 UTC, andela-hpopoola commented on server/services/user.service.js
> +  const signatoryExists = directors.some((director) => director.isSignatory === true);
This is no longer necessary based on the suggestion above

2021-01-06 06:20 UTC, andela-hpopoola commented on server/services/user.service.js
> +      'Last account signatory cannot be deleted',
```suggestion
      'Signatory cannot be deleted. Verified vendors must have at least one signatory.',
```

2021-01-06 06:20 UTC, andela-hpopoola commented on server/controllers/user.controllers.js
> +    const directorId = req.params.id;
`directorId` is currently missing in the director schema. Ensure you add this to make this to work as expected.

2021-01-06 06:20 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +                name: 'John',
Not sure why you omitted an `_id` for this. You can automatically generate an id for this with
 
```js
_id: mongoose.Types.ObjectId()
```

2021-01-06 06:20 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +      const invalidUser = UserFactory.build({ role: USER_ROLE.ADMIN }, { generateId: true });
It is preferable to use a USER role for an invalid user here. An Admin role for be used for subsequent tests

```suggestion
        const invalidUser = UserFactory.build({ role: USER_ROLE.USER }, { generateId: true });
```

2021-01-06 06:20 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +      context('when id passed is last account signatory', () => {
Lets ensure that we test this for verified and unverified users.

2021-01-06 06:20 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +    describe('Add director or signatories', () => {
Can we ensure that this test for updates not addition.

2021-01-06 06:20 UTC, andela-hpopoola commented on server/controllers/user.controllers.js
> +    addDirector({ directorInfo, userId })
The director id is needed here to be sure of the director the user wish to update.

2021-01-06 20:23 UTC, andela-hpopoola reviewed
Just added a few more comments to clear doubts on some of my previous comments.

2021-01-06 20:23 UTC, andela-hpopoola commented on server/controllers/user.controllers.js
> +    removeDirector({ directorId, vendor })
Might be better to use `user` here to prevent using something like vendor.vendor.

```js
const { user } = req;

removeDirector({ directorId, vendor })
```

2021-01-06 20:23 UTC, andela-hpopoola commented on server/services/user.service.js
> +  directors = directors.filter((director) => director._id.toString() !== directorId.toString());
Feel free to ignore the above comment since you are replacing the whole director array (though I prefer using mongodb to remove it). However, you might want to make a few updates to prevent mutating the director array and making the code to make it more understandable:

```js
const { directors } = vendor.vendor;

  const updatedDirectors = directors.filter((director) => director._id.toString() !== directorId.toString());
...
```

2021-01-06 20:47 UTC, tobieeniafe commented on server/services/user.service.js
> +  directors = directors.filter((director) => director._id.toString() !== directorId.toString());
care to clarify on the ```js if (signatories.length === 0 && user.vendor.verified) ``` part and why adding `&& director.isSignatory`?

2021-01-06 20:51 UTC, andela-hpopoola commented on server/services/user.service.js
> +  directors = directors.filter((director) => director._id.toString() !== directorId.toString());
Explained the reason here and told you to feel free to ignore it here
https://github.com/Highrachy/ballers-api/pull/94/files#r552943592

2021-01-07 06:38 UTC, andela-hpopoola requested changes
Thank you for working on this. I left a few more comments to make the code quality better.

2021-01-07 06:38 UTC, andela-hpopoola commented on server/controllers/user.controllers.js
> +        res.status(httpStatus.OK).json({ success: true, message: 'Director removed' });
Can you please return the updated user to make the returned object similar to edit directors. 

```suggestion
        res.status(httpStatus.OK).json({ success: true, message: 'Director removed', user: updatedUser });
```

2021-01-07 06:38 UTC, andela-hpopoola commented on server/schemas/user.schema.js
> +  directorId: Joi.objectId().label('Director id').required(),
I think it is preferable to use the exact name here for the id to make it easier to send from any part.
```suggestion
  _id: Joi.objectId().label('Director id').required(),
```

2021-01-07 06:38 UTC, andela-hpopoola commented on server/services/user.service.js
>    const user = await getUserById(userId).catch((error) => {
I believe we can get the user from the controller so this line is not necessary.

2021-01-07 06:38 UTC, andela-hpopoola commented on server/controllers/user.controllers.js
> +    editDirector({ directorInfo, userId })
I believe it is preferable to send the user object into the edit Director to prevent retrieving the user details again. You might need to update other user variable to `updatedUser`

```suggestion
    const { user } = req;
    editDirector({ directorInfo, user })
```

2021-01-07 06:38 UTC, andela-hpopoola commented on server/services/user.service.js
> +  const vendorIsForDirector = (director) =>
The variable name is so confusing. Can we merge the function with the validVendor some statement below to make it more understandable

2021-01-07 06:38 UTC, andela-hpopoola commented on server/services/user.service.js
> +  const validVendor = user.vendor.directors.some(vendorIsForDirector);
`validVendor` is a confusing variable name since we are checking if the director is valid. You can choose a better name or use this:

```suggestion
  const directorIsValid = user.vendor.directors.some(vendorIsForDirector);
```

2021-01-07 06:38 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
>                expect(res.body.message).to.be.eql('Director removed');
We need to test that the returned user doesn't have the deleted director to be 100% sure the director has been removed.

2021-01-07 06:38 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +            verified: true,
We need to add test to be sure that the last director can be deleted when verified is false.

2021-01-07 06:38 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
>              directors: [
I believe it is preferable to use at least 3 director information to be sure that the edit director is editing the right director. As long as you are editing the first the first one, I believe the test should still be valid.

2021-01-07 06:38 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +              expect(res.body.user.vendor.directors[0]._id).to.be.eql(signatoryId.toString());
We need to test that the length of the returned director is the same (to be sure that the code didn't add it as a new director). 

Also, we need to test that the other 2 directors don't have the updated information after testing that the right director information is updated.

2021-01-07 06:38 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +        {
This is the second time of using this in this PR. Might make sense to have a vendor factory to simplify vendor creation in the future.  It is not compulsory that factories should only match the models we have 🤷🏽‍♂️ .

2021-01-08 06:13 UTC, andela-hpopoola approved these changes
Thank you for working on this. I have approved this PR, so you should be able to merge once you have fixed the pending comments. Thank you.

2021-01-08 06:13 UTC, andela-hpopoola commented on test/controllers/user.controller.test.js
> +              expect(res.body.user.vendor.directors[0].name).to.be.eql(data.name);
The 4 assertions for the directors[0] can be combined into a single test assertion as done for directors[1] and directors[2]

2021-01-08 12:52 UTC, merged