#176408984 make enquiries support vendor
Highrachy/ballers-api pull request #97
Opened 2021-01-10 12:27 UTC by tobieeniafe

#### What does this PR do?
Make enquiries support vendor

#### Description of Task to be completed?
Make enquiries support vendor

#### What are the relevant pivotal tracker stories?
#176408984

2021-01-11 17:39 UTC, andela-hpopoola requested changes
Awesome. You did a great job here.

Thank you for working on this. The implementation makes sense but I am not satisfied with the tests as some of them are not comprehensive enough.

Can you try to always follow this implementation when writing tests for pagination: Please read this thoroughly to ensure that you understand them and always use them as reference for pagination tests.

1. Test when nothing is in the database (when database table contains no data)
2. Test that the pagination returns the right value (use pagination test 99% of the time, the remaining 1% is for edge case)
3. Test that the right values is returned.  The pagination test only deals with the numbers returned, not the validity of the data returned, so the pagination test cannot replace this

4. Add more customized tests based on the scenarios you are testing. These are tests directly related to the code. Examples are 
    - Testing for Valid user
    - Ensuring that vendor2 doesn't have access to vendor 1 information
    - Ensuring that user2 gets his own message
    - Testing for all if statements used in code with the else part
    - E.t.c.

2021-01-11 17:39 UTC, andela-hpopoola commented on test/controllers/enquiry.controller.test.js
>        it('returns a approved enquiry', (done) => {
```suggestion
      it('returns an approved enquiry', (done) => {
```

2021-01-11 17:39 UTC, andela-hpopoola commented on test/controllers/enquiry.controller.test.js
>          await addEnquiry(enquiry);
Not sure why you left this. I believe you can remove that line and use the custom pagination test 🤷🏽‍♂️

2021-01-11 17:39 UTC, andela-hpopoola commented on test/controllers/enquiry.controller.test.js
> -              expect(res.body).to.have.property('enquiries');
Can you reintroduce this tests back as the new test doesn't replace it. In testing an endpoint with pagination, lets try to keep the following in mind. In this case, we have admin, user and vendor. 

Based on the information on the comment section, here is the breakdown
1. Test when nothing is in the database for the three  (already done on line 727)
2. Test that the pagination returns the right value for the three 
   - It is preferable to use the custom pagination test as it contains multiple test
   - A recurring mistake I notice is that you usually try to force the test in a single test assertion (i.e a describe/context block), it is not compulsory to do this. You might split the test into different blocks to make it more readable and better organized.
   - user test for this seems missing
3. Test that the right value is returned. 
    - The pagination test only deals with the numbers returned, not the validity of the data returned, so the pagination test cannot replace this
    - You will need to reintroduce this test you removed.
4. Add more tests based on the scenarios you are testing. Some of this can be incorporated in the pagination test setup:
   - You added some here like testing that vendor2 cannot access vendor1 enquiries
   - You can add more like ensuring that a user can only access his enquiry
   - Admin should be able to view all enquiries (This can be incorporated in the pagination test)

2021-01-11 17:39 UTC, andela-hpopoola commented on server/services/enquiry.service.js
> +  if (user.role === USER_ROLE.VENDOR) {
Tests should be written to validate that this is works as expected.

2021-01-11 17:39 UTC, andela-hpopoola commented on server/services/enquiry.service.js
> +  if (user.role === USER_ROLE.USER) {
Tests should be written to validate that this works too.

2021-01-11 17:39 UTC, andela-hpopoola commented on server/models/enquiry.model.js
> +    vendorId: {
I believe this should be added to `test/factories/enquiry.factory.js` too since it is required to make it easier to generate test objects for enquiries.

2021-01-11 17:39 UTC, andela-hpopoola commented on server/services/enquiry.service.js
> +    if (vendor.role === USER_ROLE.VENDOR && vendor._id.toString() !== enquiry.vendorId.toString()) {
We might need to add a test to ensure that this works as expected too.

2021-01-11 20:02 UTC, tobieeniafe commented on test/controllers/enquiry.controller.test.js
>          await addEnquiry(enquiry);
this was added to be sure that the user and admin do not return the same data. the user token uses the pagination tests

2021-01-11 22:26 UTC, tobieeniafe commented on server/models/enquiry.model.js
> +    vendorId: {
this is added automatically in service. gotten from id of the owner of the property

2021-01-12 06:45 UTC, andela-hpopoola requested changes
Thank you for working on this and implementing the requested changes. Thank you for the response to the comments too, they are really on point 👍🏽 .

I left a few comments on proper naming and removing the eslint comments. I should have approved this but would love you to fix the failing test assertion before approving. Thank you and nice work.

2021-01-12 06:45 UTC, andela-hpopoola commented on test/controllers/enquiry.controller.test.js
> +    const vendor2 = UserFactory.build(
Lets make this `vendorUser2` to make it consistent with `vendorUser`.

2021-01-12 06:45 UTC, andela-hpopoola commented on test/controllers/enquiry.controller.test.js
> +      [demoUser, vendor2].map((user) => {
Instead of `demoUser`, lets use something like `regularUser2` to make it easier to relate it.  It will even make more sense to add if you can add `1` to the the first one too.

That way, `regularUser1` makes an enquiry on `vendorUser1` property called `enquiry1` and `regularUser2` makes an enquiry on `vendorUser2` called `enquiry2`. This will make it easier to understand the user, vendor and enquiry you are referring to without stress.

Reading through the code was kinda of difficult to relate with because of the naming convention. I had to revisit the variable definition to understand what they are doing.

2021-01-12 06:45 UTC, andela-hpopoola commented on test/controllers/enquiry.controller.test.js
> +      // eslint-disable-next-line array-callback-return
Lets remove this and add `return null` at the end of the test block.

2021-01-12 06:45 UTC, andela-hpopoola commented on test/controllers/enquiry.controller.test.js
> +    context('with a token with invalid access', () => {
The token actually has a valid access but they are not authorized to view another user's enquiry.

```suggestion
    context('when viewing an unauthorized enquiry', () => {
```

2021-01-12 06:45 UTC, andela-hpopoola commented on test/controllers/enquiry.controller.test.js
> +    context('with a token with valid access', () => {
```suggestion
	    context('when viewing an authorized enquiry', () => {
```

2021-01-12 06:45 UTC, andela-hpopoola commented on test/controllers/enquiry.controller.test.js
> +          .get(`/api/v1/enquiry/${vendorEnquiry._id}`)
Can we revert the variable back to `enquiry`. `vendorEnquiry` sometimes give the enquiry a different meaning as the enquiry is made by the user. Lets use `enquiry` to be more neutral.

2021-01-13 05:28 UTC, andela-hpopoola approved these changes
Thank you for making the changes. This looks good to me.

2021-01-13 09:22 UTC, merged